### ISSUE TITLE
if app is not in app store yet, it crashes

### ISSUE THREAD

**Issue by jarimartens10** [ArtSabintsev/Siren#1]
Change processVersionCheckResults() to this to fix the issue (first check if app is available)

    private func processVersionCheckResults(results: [String : AnyObject]) {
        
            if results["results"]?.count > 0 {
                self.currentAppStoreVersion = results["results"]?[0]["version"] as? String
                if let currentAppStoreVersion = self.currentAppStoreVersion {
                    if self.isAppStoreVersionNewer() {
                        self.showAlertIfCurrentAppStoreVersionNotSkipped()
                    }
                } else {
                    if self.debugEnabled {
                        println("[Siren] Error retrieving App Store version number")
                    }
                }
            }
            else {
                if self.debugEnabled {
                    println("[Siren] App not found")
                }
            }
        
        
        }

**Comment by getaaron** [comment]
I think a more elegant change would be:

    self.currentAppStoreVersion = results["results"]?[0]?["version"]? as? String

@jarimartens10 does that resolve the issue for you?

**Comment by ArtSabintsev** [comment]
@getaaron Still crashes on my end. Looking into it right now as is.

**Comment by ArtSabintsev** [comment]
@getaaron ah, this is on a new branch - got it. Checking it now.

**Comment by ArtSabintsev** [comment]
Ya, still crashes on the new branch if you put in a fake/wrong AppID.

**Comment by ArtSabintsev** [comment]
Pushed v0.1.2. Built it on top of your change, @getaaron.
