### ISSUE TITLE
testing without an app store app

### ISSUE THREAD

**Issue by adhsu** [ArtSabintsev/Siren#102]
Hey - thanks for the great work on Siren.  I'm trying to test it without an app store app and tried the suggestion of changing our bundle ID in xcode to 'com.apple.itunesconnect.mobile.' Unfortunately, Xcode won't let me build to device anymore since my provisioning profile isn't valid for that app. Any ideas?

**Comment by ArtSabintsev** [comment]
Hey!

You can't test without the app store ID on a device, only on the sim. If it works on the sim with the fake ID, then it'll work on the device.
