### ISSUE TITLE
xcode 8.1

### ISSUE THREAD

**Issue by xedla** [ArtSabintsev/Siren#104]
installing with cocoapods in my project  Xcode want convert to swift 3 but my project was already for swift 3.

**Comment by ArtSabintsev** [comment]
The library is also in Swift 3.

Are you installing with this command: `pod 'Siren'`

If so, it should just work.

**Comment by xedla** [comment]
I did “a single view application” from Xcode template.
created this simple podfile:

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'tryme' do
  use_frameworks!

  pod 'Siren'
end


after pod install

Analyzing dependencies
Downloading dependencies
Installing Siren (1.1.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `tryme.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total
pod installed.

open xcode 


What is my mistake? 

thanks

**Comment by ArtSabintsev** [comment]
This means everything is successful :)

```
Pod installation complete! There is 1 dependency from the Podfile and 1 total
pod installed.
```

Just open `tryme.xcworkspace` instead of `tryme.xcproj` from here on out.
