### ISSUE TITLE
Can't test unless app is live in the app store.

### ISSUE THREAD

**Issue by jeffjvick** [ArtSabintsev/Siren#11]
I want to test on Siren however I do not currently have a version live in the app store so I can't "Temporarily change the version string in Xcode to an older version than the one that's currently available in the App Store" as is specified in the ReadMe.

Here are the results from turning on debug:

[Siren] iTunes Lookup URL: https://itunes.apple.com/lookup?id=XXXXXXXXX (I'm obscuring my app id)
[Siren] JSON results: [resultCount: 0, results: (
)]
[Siren] Error retrieving App Store verson number as results returns an empty array

Currently I'm just finding a random app on the app store and using their app id for testing.

**Comment by ArtSabintsev** [comment]
Thad exactly how I test it with newer apps. I use an existing app, and change the version of my project to a version older than the app in testing against. Does that work for you?

**Comment by jeffjvick** [comment]
That's fine.  I would suggest adding that to the "How to test siren" section of the ReadMe as it was not an obvious solution to me at first and I've seen others ask the same question.

You might also want to add a comment about using siren.enableDebug = true to help with testing.

Oh and the Setup Instructions it should be "let siren = Siren.sharedInstance" not "let siren = Siren.SharedInstance" ('s' should not be capitalized).

Thanks
