### ISSUE TITLE
Error retrieving iOS version number as there was no data returned.

### ISSUE THREAD

**Issue by christoph-peters** [ArtSabintsev/Siren#113]
I am trying to add Siren to our app, but it seems to fail to receive data.
I added the following:
`let siren = Siren.sharedInstance`
`siren.alertType = .option`
`siren.checkVersion(checkType: .immediately)`

The log shows:
[Siren] Error retrieving iOS version number as there was no data returned.
[Siren] Error parsing App Store JSON data.
[Siren] Error retrieving iOS version number as there was no data returned.
[Siren] Error parsing App Store JSON data.

I tried it both with our bundle identifier and the  "com.apple.itunesconnect.mobile".
Any idea how I can investigate the problem?

**Comment by christoph-peters** [comment]
I forgot the country code:

`siren.countryCode = "se"`

Would be nice if that could be highlighted  in the Readme.

**Comment by ArtSabintsev** [comment]
@christoph-peters Glad to figured it out.

There are so many options, that I only listed the most common ones, while listing the other ones in the same project, and calling it out in the first line of the SETUP section:

https://github.com/ArtSabintsev/Siren#setup
