### ISSUE TITLE
Error retrieving

### ISSUE THREAD

**Issue by J-Arji** [ArtSabintsev/Siren#117]
I am trying to add Siren to our app, but it seems to fail to receive data.
I added code  the following:
` let siren = Siren.sharedInstance
        // Optional
        siren.delegate = self
        
        // Optional
        siren.debugEnabled = true
        
        // Optional - Defaults to .Option
        siren.alertType = .Option 
        
              siren.majorUpdateAlertType = .Option
        siren.minorUpdateAlertType = .Option
        siren.patchUpdateAlertType = .Option
        siren.revisionUpdateAlertType = .Option
            siren.checkVersion(.Immediately)
`
 but when run app  print following error : 
```
sirenDidFailVersionCheck Error Domain=Siren Error Domain Code=1005 "Error retrieving iOS version number as there was no data returned." UserInfo={NSLocalizedDescription=Error retrieving iOS version number as there was no data returned.}
[Siren] Error retrieving iOS version number as there was no data returned.
sirenDidFailVersionCheck Error Domain=Siren Error Domain Code=1004 "Error parsing App Store JSON data." UserInfo={NSLocalizedDescription=Error parsing App Store JSON data.}
[Siren] Error parsing App Store JSON data.
```

**Comment by getaaron** [comment]
What's the actual response you get from the iTunes API?

**Comment by ArtSabintsev** [comment]
Also, is your app in the US App Store?

**Comment by J-Arji** [comment]
@ArtSabintsev 
I did not do it in the App Store. But soon I will

**Comment by ArtSabintsev** [comment]
Alright, for Siren to work you need to use the bundleID for an app that's in the store. If the app isn't in the store, it'll throw back errors, like the one you saw.

To get around that, change the bundleID to that of the one in the sample project in this repository and try again. It should work.

Next, will your application be in the US App Store? If it won't be, there's another step you have to follow (look in the AppDelegate file in the sample project)

**Comment by ArtSabintsev** [comment]
Closing this issue as there's no update. Feel free to re-open it if you have further questions.

**Comment by kiraninfogird** [comment]
// for swift 3 : it will give me below error of version : whats the solution for that????

sirenDidFailVersionCheck(error:) Error Domain=Siren Error Domain Code=1005 "Error retrieving iOS version number as there was no data returned." UserInfo={NSLocalizedDescription=Error retrieving iOS version number as there was no data returned.}

**Comment by ArtSabintsev** [comment]
What Region/Country is your app being released in? What's your app's bundleID?

**Comment by kiraninfogird** [comment]
Region/Country :  India

bundle ID : com.IIPL.HRGirdESS

**Comment by ArtSabintsev** [comment]
Ok, did you set the country code to India?

**Comment by ArtSabintsev** [comment]
And is your app live in the store?

**Comment by kiraninfogird** [comment]
@ArtSabintsev:
1.Ok, did you set the country code to India?  
-> how set it and where???

2. And is your app live in the store?
-> YES

**Comment by kiraninfogird** [comment]
Thanks,,,


i was done that.....!👍

**Comment by ArtSabintsev** [comment]
Everything works now?

**Comment by kiraninfogird** [comment]
Yes....!

Thanks Again for your help.....

**Comment by ArtSabintsev** [comment]
Great! Thanks for the update!

**Comment by ajayiivo** [comment]
Hello,
my application is live on UK app store .
Also, set the country code  = en_UK

but i am getting error. 
**below is my code** 

     let siren = Siren.shared
        siren.delegate = self
        siren.debugEnabled = true
        siren.countryCode = "en_UK"
       siren.alertType = .option
        
        siren.majorUpdateAlertType = .option
        siren.minorUpdateAlertType = .option
        siren.patchUpdateAlertType = .option
        siren.revisionUpdateAlertType = .option
        siren.checkVersion(checkType: .immediately)

**Getting error :** 

sirenDidFailVersionCheck(error:) Error Domain=Siren Error Domain Code=1005 "Error retrieving iOS version number as there was no data returned." UserInfo={NSLocalizedDescription=Error retrieving iOS version number as there was no data returned.}

Please help me in this .

thank you
