### ISSUE TITLE
Alert not showing up for app store release build

### ISSUE THREAD

**Issue by gbertb** [ArtSabintsev/Siren#119]
Would there be a reason for the alert to not show up on an app store version vs. running the app on my device via xcode? I can simulate the alert through xcode by changing the version number, but the alert doesn't show on the official release of the app. 

Any clues? 

Here are my siren settings:

    let siren = Siren.sharedInstance
    siren.majorUpdateAlertType = .Force
    siren.minorUpdateAlertType = .Force
    siren.patchUpdateAlertType = .Force
    siren.revisionUpdateAlertType = .Option
    siren.debugEnabled = false
    siren.checkVersion(.Immediately)

Here's the lookup https://itunes.apple.com/lookup?bundleId=org.litterati.LitteratiApp. This seems to reflect the newest version. 

Thanks

**Comment by ArtSabintsev** [comment]
Closing this issue in favor of the response given in #120.
