### ISSUE TITLE
Version in AppStore not showing update alert.

### ISSUE THREAD

**Issue by sherm4n90** [ArtSabintsev/Siren#121]
Im having a problem with the AppStore version. The lookup returns the latest version and also the AppStore app shows the option to update the current version, so this means the new version is ready in my territory.
Im using:
`siren.revisionUpdateAlertType = .Skip`
`siren.patchUpdateAlertType = .Skip`
`siren.minorUpdateAlertType = .Option`
`siren.majorUpdateAlertType = .Force `
`siren.checkVersion(.Immediately)`

But the update alert still does not appear.
Testing in the simulator it is shown correctly though.

**Update:** If I request a lookup with a browser or postman the version number shows the latest one. But while debugging it shows `currentAppStoreVersion` same as the current one, thats why the alert never appears.

**Comment by ArtSabintsev** [comment]
What version of Siren are you using?

**Comment by sherm4n90** [comment]
@ArtSabintsev Im using the swift 2.3 branch.
`pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift2.3'`

**Comment by sherm4n90** [comment]
**Update:** Running the exact same thing in a device and a simulator and only works in the simulator.

**Comment by ArtSabintsev** [comment]
Ah, ok. There's a fix in the Swift 3 branch with respect to `URLSession` caching that isn't in the Swift 2.3 branch. Would you mind implementing and testing the fix and opening a PR against the swift2.3 branch?

Here's the fix in the swift 3 branch: https://github.com/ArtSabintsev/Siren/blob/master/Siren/Siren.swift#L260

**Comment by sherm4n90** [comment]
@ArtSabintsev Thanks, it is working now! I will open the PR soon.

**Comment by sherm4n90** [comment]
@ArtSabintsev Im going to close the issue. ANy other important fix that I should copy from the master branch?

**Comment by ArtSabintsev** [comment]
No, no other fix I can think of. Thanks.
