### ISSUE TITLE
Error retrieving iOS version number as there was no data returned

### ISSUE THREAD

**Issue by rmvz3** [ArtSabintsev/Siren#123]
I'm trying to use your library but I always get this error.

The bundleId is right, the version string is set to a previous number and there is a previously released app on the store but the support call always retrieves an invalid json.

I've tried Harpy and others similar libraries too and it happens the same thing. Maybe Apple changed anything?

**Comment by bre7** [comment]
Have you tried retrieving the JSON data manually and linting it ?
URL: https://itunes.apple.com/lookup?bundleId=BUNDLE_ID

**Comment by rmvz3** [comment]
Oops! This  is embarrassing. You're right. My client only enabled the local Appstore. It works like a charm now.

Thank you.

**Comment by bre7** [comment]
👍 There should be a noticeable alert in the README about it

**Comment by ArtSabintsev** [comment]
@rmvz3 Glad you figured it out@

@bre7 Thanks for assisting and for making the  issue template PR. That's been on my backlog for a long time. Will review it soon.
