### ISSUE TITLE
What happens to the app, if we discontinue the app on the store?

### ISSUE THREAD

**Issue by jimijon** [ArtSabintsev/Siren#129]
We are looking to change our app to a Freemium version. As such we need to remove our current app from the store. We have been forcing our users to upgrade. What happens to the users app if there is no app on the store? Will the user be stuck? Or will Siren ignore and not show any alerts?

**Comment by getaaron** [comment]
See the `processVersionCheck()` method. If no app is available in the store, no newer version is available, so Siren won't show an alert.

That said, you may want to release an update directing your users to the new app.
