### ISSUE TITLE
Patch version not prompting

### ISSUE THREAD

**Issue by dylanbromby** [ArtSabintsev/Siren#133]
Hi there -

We're seeing an issue in the Swift 3 branch. We introduced Siren into version 1.4.0 of our app. 1.4.1 was released today and is in the App Store but opening 1.4.0 does not prompt the user to update. Is there some kind of delay in the process Siren uses to acquire the latest release version from the App Store?

**Comment by ArtSabintsev** [comment]
Hey @dylanbromby!

On occasion, the JSON updates before the app propagates to the AppStore CDN. Typically, it's less than 6 hours. 

Can you provide me with your bundleID and the AppStore link? If you don't feel comfortable posting that information here, feel free to DM me on Twitter (@ArtSabintsev). My DMs are open.

Also, is your app available in the US App Store?

**Comment by ArtSabintsev** [comment]
As we discussed on a different channel, the issue is with Apple's unstable JSON API. I will address this in the README and offer solutions.

Thanks!

**Comment by ArtSabintsev** [comment]
Updated the README per our conversation: https://github.com/ArtSabintsev/Siren#words-of-caution

**Comment by ArtSabintsev** [comment]
Hey - just wanted to let you know that this issue has been fixed as of v2.0.0: https://github.com/ArtSabintsev/Siren/releases/tag/2.0.0
