### ISSUE TITLE
Force update stuck even after update to new version

### ISSUE THREAD

**Issue by aliasad106** [ArtSabintsev/Siren#135]
When we enable force update. User updates to new version but still see alert.

**Comment by ArtSabintsev** [comment]
I am going to fix this very soon. If you look at the other Issues that've come about, you'll see that it's a problem on Apple's side.

**Comment by shshlomi** [comment]
Hi,
Can you please give us a ball park figure so we'll be able to decide whether to update a new version with a weakly alert update  or wait for the fix.

Thank you.

**Comment by aliasad106** [comment]
I think you should add a warning for force update. I get this is Apple's slowness caused it but What developers expect is a quick update but sometimes apple's API gives response with version available whereas the version is still not available for update in Appstore. This caused a lot of frustration on User's end and the app loses some good users. Please add some documentation for that. Thanks

**Comment by ArtSabintsev** [comment]
I will have a fix for this by Sunday. I already know how I want to do it, but I need some time to implement it.

**Comment by ArtSabintsev** [comment]
Alright, the quick fix is to set `showAlertAfterCurrentVersionHasBeenReleasedForDays` to `1`.

I'm going to push out version 2.0.0 of the app where it does this automatically: https://github.com/ArtSabintsev/Siren/pull/136

**Comment by gbertb** [comment]
Great work! @ArtSabintsev

**Comment by ArtSabintsev** [comment]
Thanks - hope it addresses the issue for you both!

**Comment by shshlomi** [comment]
Fantastic!! Thank you for the quick responsiveness @ArtSabintsev 👍

**Comment by ArtSabintsev** [comment]
My pleasure!
