### ISSUE TITLE
Linker command error when building with Carthage

### ISSUE THREAD

**Issue by tatimagdalena** [ArtSabintsev/Siren#137]
(related to issue #125 )

Xcode (8.1) is giving me a linker command error when building from Carthage and trying to access some properties.

I've found this kind of error when trying to use differentiated Alerts for Major, Minor and Patch, and when trying to set appName.

For example, when adding this line: `siren.majorUpdateAlertType = .force`, the following error appears:

`Undefined symbols for architecture x86_64:
  "direct field offset for Siren.Siren.(majorUpdateAlertType.storage in _7DFB1BC200A6C64FBED860A3A8153B65) : Siren.Siren.AlertType?", referenced from:
      CarthageTeste.AppDelegate.application (__ObjC.UIApplication, didFinishLaunchingWithOptions : [__C.UIApplicationLaunchOptionsKey : Any]?) -> Swift.Bool in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

If I don't use these properties, everything works just fine.

**Comment by ArtSabintsev** [comment]
Thanks for the post.

A couple questions:

- What version of Carthage are you using?
  - Is it the latest version? 
- Why are you not using Xcode 8.3.x?

**Comment by tatimagdalena** [comment]
My first try was with Xcode 8.2.x. I tried again with 8.1 just to provide you with the error output.

I'm using the most recent version of Carthage (0.20.1), but apparently it was the Xcode version. I updated it  now and everything is working.

Thanks for your attention!

**Comment by ArtSabintsev** [comment]
Glad it works now!
