### ISSUE TITLE
Set dialog title & content

### ISSUE THREAD

**Issue by OnlyMyRailgun** [ArtSabintsev/Siren#138]
Can I set dialog title & content without implement the dialog by myself?
I think using delegate for notification without alert can achieve that, but I have to do a lot of unnecessary works that this framework has done.

**Comment by ArtSabintsev** [comment]
Yes, you should be able to use your own dialog if you use this delegate method:

```
sirenDidDetectNewVersionWithoutAlert
```

Here's some more info here:

https://github.com/ArtSabintsev/Siren#prompting-for-updates-without-alerts
