### ISSUE TITLE
Customise alert text

### ISSUE THREAD

**Issue by talkabhishek** [ArtSabintsev/Siren#142]
HI,
Can we update Alert action Text like "Next Time" changes to "Remind me Later"

Basically, I need to customise below method somehow

```
private extension Siren {
    func localizedNewVersionMessage() -> String {
        let newVersionMessageToLocalize = "A new version of %@ is available. Please update to version %@ now."
        let newVersionMessage = Bundle().localizedString(stringKey: newVersionMessageToLocalize, forceLanguageLocalization: forceLanguageLocalization)

        guard let currentAppStoreVersion = currentAppStoreVersion else {
            return String(format: newVersionMessage, appName, "Unknown")
        }

        return String(format: newVersionMessage, appName, currentAppStoreVersion)
    }

    func localizedUpdateButtonTitle() -> String {
        return Bundle().localizedString(stringKey: "Update", forceLanguageLocalization: forceLanguageLocalization)
    }

    func localizedNextTimeButtonTitle() -> String {
        return Bundle().localizedString(stringKey: "Next time", forceLanguageLocalization: forceLanguageLocalization)
    }

    func localizedSkipButtonTitle() -> String {
        return Bundle().localizedString(stringKey: "Skip this version", forceLanguageLocalization: forceLanguageLocalization)
    }
}
```

**Comment by ArtSabintsev** [comment]
@talkabhishek 

Thanks for the message. You can create and customize your own alert using the delegate method: 

```swift
func sirenDidDetectNewVersionWithoutAlert(message: String)
```

The reason I don't allow for customization is due to localization. We have those specific phrases localized for multiple languages, and it seems to be the most innocent/standard way of communicating those messages.

Hope this helps.

Arthur

(Closing this issue, but feel free to follow-up).

**Comment by talkabhishek** [comment]
@ArtSabintsev 
Thanks for the help.

**Comment by Oyashirox** [comment]
I feel like this is a deal-breaker. Using the delegate prevent me from using the `launchAppStore()`, so I would have to duplicate a lot of code. Let the user override the message and handle the localization seems acceptable.

**Comment by ArtSabintsev** [comment]
Would making `launchAppStore()` a public method make it easier?

**Comment by flchappa** [comment]
I think so, we could customize the way we want to present the message to the user, and continue with the nominal flow. What do you think ?

**Comment by ArtSabintsev** [comment]
sure, can you fork the repo, and try it out with that change. If it satisfies your needs, I'll make the change and push it out.

**Comment by Oyashirox** [comment]
I think so, we could customize the way we want to present the message to the user, and continue with the nominal flow. What do you think ?

**Comment by ArtSabintsev** [comment]
Try it out and see if that works for you.

**Comment by Oyashirox** [comment]
So it appears to be more complicated than expected. I would need to create a custom window and handle it as you do, so that's still too much code duplication in my opinion. Do you think a message and title override would be too disruptive ?

**Comment by ArtSabintsev** [comment]
Oh ya, I forgot about that change.

Yes, overriding any of the strings would disrupt the localization logic I have. Is there any reason the existing solution with the existing test is not good enough, esecpailly with all the benefits of localization that you get?

**Comment by Oyashirox** [comment]
Simply because my client wants to add a warning in the popup, and that
needs to be translated in the officially supported languages

**Comment by ArtSabintsev** [comment]
Well, what I would do in your position is just fork   this repository, and make the changes that you need specifically for your project. If you just change the text of the alert, nothing should really break.
