### ISSUE TITLE
isAppStoreVersionNewer() is not working as expected

### ISSUE THREAD

**Issue by simonlinj** [ArtSabintsev/Siren#146]
https://github.com/ArtSabintsev/Siren/blob/master/Sources/Siren.swift#L413

```swift
    func isAppStoreVersionNewer() -> Bool {
        var newVersionExists = false

        if let currentInstalledVersion = currentInstalledVersion,
            let currentAppStoreVersion = currentAppStoreVersion,
            (currentInstalledVersion.compare(currentAppStoreVersion, options: .numeric) == .orderedAscending) {

            newVersionExists = true
        }

        return newVersionExists
    }
```

Playground Test

![screen shot 2017-06-06 at 11 12 54 pm](https://user-images.githubusercontent.com/1506890/26860761-b48d7f66-4b0d-11e7-822a-07cb9f9e2591.png)

**Comment by ArtSabintsev** [comment]
In your example, the Installed Version > App Store Version. 

In this case, isAppStoreVersionNewer should return false, which translates to `Not OrderAscending` in your example.

It works as expected.

Am I missing something here?

Closing this issue, but feel free to continue the conversation.

**Comment by simonlinj** [comment]
oops my bad... I was testing the other way around =P 

by enabling the debug option I got the reason I wasn't getting the alert "Your app has been released for 0 days, but Siren cannot prompt the user until 1 days have passed."

Sorry for bothering.

**Comment by ArtSabintsev** [comment]
No problem!

You can have siren prompt earlier if you change the `showAlertAfterCurrentVersionHasBeenReleasedForDays` value to 0. It'll prompt instantly.
