### ISSUE TITLE
Version Cache & always show prompt

### ISSUE THREAD

**Issue by andiesupriyatna** [ArtSabintsev/Siren#148]
Hi Siren Team

I've issue in using siren
i've app in appstore with version 3.0.0 and it's already used siren for update
so i update it from appstore, and after finish update
when i open my app, there's always show prompt that there's new version 3.0.0 in appstore.
is there's a cache version inside siren? if yes how to set it?

condition: i used force update and check Immediately

thank you

**Comment by ArtSabintsev** [comment]
Hi,

What version of Siren are you using?

**Comment by ArtSabintsev** [comment]
Also, can you copy/paste a snippet of your code so I can see how everything is setup?

**Comment by ArtSabintsev** [comment]
Closing due to lack of response. Feel free to reopen it.
