### ISSUE TITLE
branch swift 2.3 is deleted? cannot download in cocoaPods

### ISSUE THREAD

**Issue by xiaoxiongke** [ArtSabintsev/Siren#149]
thanks..

**Comment by ArtSabintsev** [comment]
I deleted a few weeks because I didn't think anyone was still using it, since there was such a huge push to migrate to Swift 3. 

I've restored the branch just now for you. Try now.

**Comment by xiaoxiongke** [comment]
Great thanks,I think swift with higher version is the future,i'll switch to swift 3 soon~:)

**Comment by ArtSabintsev** [comment]
Sounds good!
