### ISSUE TITLE
Adding bundleIdentifier

### ISSUE THREAD

**Issue by jibrilg** [ArtSabintsev/Siren#153]
Hello,

Can you expose `appId` so we can set it as we want?

`
    /// The bundle identifier of your app.
`
`
    /// By default, it's set to the bundle identifier of the app that's stored in your plist.
`
`
    public lazy var appBundleIdentifier = Bundle.main.bundleIdentifier ?? ""
`

Then you can change line 244 to:

`
var items: [URLQueryItem] = [URLQueryItem(name: "bundleId", value: appBundleIdentifier)]
`

Cheers

**Comment by ArtSabintsev** [comment]
I used to have that open, however, the bundleID gets you the same JSON for free without an extra line of configuration. Why not use the bundleID?

**Comment by ArtSabintsev** [comment]
Closing this issue due to lack of follow-up. Feel free to re-open if you need further assistance.
