### ISSUE TITLE
Get wrong version 

### ISSUE THREAD

**Issue by willyaako** [ArtSabintsev/Siren#154]
Hello,

I get the link and download the txt and found app store version is "1.2",
but I use debug mode and get the version is "1.0"
I'm sure that bundle ID, app name and Apple ID are all correct.
Why this happened?

dubug mode print
![image](https://user-images.githubusercontent.com/17444185/28853993-dec9e4b0-7766-11e7-9a9a-f10e9a7d5d3d.png)

txt
![image](https://user-images.githubusercontent.com/17444185/28854006-0cf5cff2-7767-11e7-9684-ecf5edd88306.png)

**Comment by ArtSabintsev** [comment]
What's your bundleID?

**Comment by willyaako** [comment]
This is my bundleID  [Pouchen.PCMST.IoT.Conference]

**Comment by ArtSabintsev** [comment]
What country is your app released in? There's an error with that bundleID for the US App Store? Did you set the Country Code using `countryCode` if your app is released outside the US App Store?

**Comment by willyaako** [comment]
Sorry, I forget to tell you countryCode.

> countryCode = "TW"

**Comment by ArtSabintsev** [comment]
The App Store JSON only returns v1.0, which is what you have seen as well.  

When did you release v1.2?

This is out of my control as the JSON is produced by Apple.

**Comment by willyaako** [comment]
I have release v1.2 the day before yesterday.
Here is the the app store screenshot of my app.

![image](https://user-images.githubusercontent.com/17444185/28858708-11893bc6-7785-11e7-9efc-f12757e3109c.png)

That is very strange.

**Comment by ArtSabintsev** [comment]
hmm, very odd. Can you send me the link to the App Store URL? I'll look into this more tomorrow.

**Comment by willyaako** [comment]
[Here](https://itunes.apple.com/us/app/pcg%E6%9C%83%E8%AD%B0%E5%AE%A4%E9%A0%90%E5%80%9F%E7%B3%BB%E7%B5%B1/id1263346057?l=zh&ls=1&mt=8) is my app
I will delete it when you get it, thx.

**Comment by ArtSabintsev** [comment]
That is really odd, but I'm glad it works!
