### ISSUE TITLE
urgent error

### ISSUE THREAD

**Issue by waleednour** [ArtSabintsev/Siren#155]
i received this error: 
fatal error: An attempt to reach sirenDidFailVersionCheck(error:) failed as it was called without being implemented.: /Pods/Siren/Sources/SirenDelegate.swift, line 58

**Comment by ArtSabintsev** [comment]
Ah, that happens because you have enabled the `delegate`, but have not declared that method in your implementation. 

I'm assuming you need the delegate, just not that delegate method, right?

I may need to remove those `assertionFailures` in the SirenDelegate class. Let me think on it.

**Comment by ArtSabintsev** [comment]
Alright, so I need to remove the default implementation of each function. I'll do that later today and push a new version. Sorry for the troubles!

**Comment by ArtSabintsev** [comment]
I'll be fixing this on Saturday. Haven't had a chance today.

**Comment by ndduong97** [comment]
+1 I'm having the same issue

**Comment by ArtSabintsev** [comment]
Fixing it as we speak.

**Comment by ArtSabintsev** [comment]
Fixed and available via all package managers as v2.0.7: https://github.com/ArtSabintsev/Siren/releases/tag/2.0.7
