### ISSUE TITLE
Podspec list iOS 8 as supported platform

### ISSUE THREAD

**Issue by zmian** [ArtSabintsev/Siren#16]
Can we updated the podspec to support iOS 7?

**Comment by ArtSabintsev** [comment]
Oversight on my part. Will do it in a moment.

**Comment by zmian** [comment]
thank you

**Comment by ArtSabintsev** [comment]
Oh you know what, this isn't possible due to the following:

 -> Siren (0.3.6)
    - ERROR | [iOS] Swift support uses dynamic frameworks and is therefore only supported on iOS > 8.

**Comment by ArtSabintsev** [comment]
Which is why I left a comment in the README about it. I should have read what I wrote =p

**Comment by ArtSabintsev** [comment]
Closing this issue - you'll have to do a manual install. Also, I suggest dropping support for iOS 7 as soon as you can, as iOS 8 is at 80% penetration.

**Comment by zmian** [comment]
I did manual install. Trust me I want too. Thanks for your help.

**Comment by ArtSabintsev** [comment]
No problem - best of luck!

**Comment by getaaron** [comment]
BTW, I looked at Carthage too, which has the same limitation.

**Comment by ArtSabintsev** [comment]
I did research into this manner last time it came up (on a different project). It's an issue with a setting the Apple has set for Dynamic Libraries(dylib). By default, they only on iOS 8. After some fiddling, they can run on iOS 7. Unfortunately, if you try to submit an iOS 7+ app with a dylib, the App validator rejects the binary.

Great SO post about it over here: http://stackoverflow.com/a/25910262/814861
