### ISSUE TITLE
'' is inaccessible due to 'private' protection level errors Xcode 9 GM Release

### ISSUE THREAD

**Issue by iJasonWade** [ArtSabintsev/Siren#161]
After updating to the Siren 4.0 release for iOS 11 support I ran a build on my app and I am getting many errors in Siren.swift. 

Siren.swift:296:35: 'alertViewIsVisible' is inaccessible due to 'private' protection level
Siren.swift:204:14: 'appID' is inaccessible due to 'private' protection level
Siren.swift:197:9: 'storeVersionCheckDate' is inaccessible due to 'private' protection level
Siren.swift:417:9: 'lastVersionCheckPerformedOnDate' is inaccessible due to 'private' protection level

These should be set as fileprivate to resolve this issue.

**Comment by ArtSabintsev** [comment]
can you open a PR? I'll get it merged in an hour or less.

Thanks!

**Comment by iJasonWade** [comment]
I think you meant to put 4.0.1 into the pod spec but accidentally put 3.0.1, thanks for getting that fix out so fast!
