### ISSUE TITLE
add support for custom JSON url (for consistency with Android counterpart)

### ISSUE THREAD

**Issue by saraht129** [ArtSabintsev/Siren#164]
Hi there,

I saw on your documentation that 'remotely disabling Siren' is possible but isn't sure whether that's a built-in function (not seeing that in your documentation). 

If that's to be manually implemented, I imagine there should be a way to add a custom URL to "remotely" disable the version check? If that so, would it be possible to implement a JSON parse like how the Android counterpart does? This enables consistency between the two platforms and potentially allows a "minimumAppVersion" check.

Thank you!

**Comment by ArtSabintsev** [comment]
Hi,

Thanks for your message. The Android counterpart was created in the spirit of this library, but we have no influence over its development.

As for remote-configuration, the way I've done and seen it done is as follows:
- Store a JSON file on the web with some parameters (sirenEnabled, minimumVersionToPrompt, typeOfPrompt, etc.). Then, before calling `Siren.shared.checkVersion()`, download the remote data from the web, parse it, and check to see if Siren is enabled or not or if any other values will hamper siren from running.

That's the best approach, as it's not opinionated, and allows users to define their own JSON files and logic before executing Siren.

Closing this issue, but feel free to follow up!
