### ISSUE TITLE
Use of unresolved type 'Decodable' SirenLookupModal.swift

### ISSUE THREAD

**Issue by dongpinyun** [ArtSabintsev/Siren#165]
![wechatimg1](https://user-images.githubusercontent.com/26698885/30891968-8730b7e8-a325-11e7-8162-fcaca11e0bc9.jpeg)
![wechatimg2](https://user-images.githubusercontent.com/26698885/30891969-87313a10-a325-11e7-8cee-6b4c92f34b4a.jpeg)

**Comment by ArtSabintsev** [comment]
The master branch is using Swift 4. Please read here for installation instructions for different versions of Swift: https://github.com/ArtSabintsev/Siren#installation-instructions
