### ISSUE TITLE
After the installation of Siren，get error "AFNetworking.h file not found"！

### ISSUE THREAD

**Issue by dongpinyun** [ArtSabintsev/Siren#166]
![wechatimg3](https://user-images.githubusercontent.com/26698885/30955100-026f22d0-a422-11e7-8c4e-092216ad520b.jpeg)
![wechatimg4](https://user-images.githubusercontent.com/26698885/30955098-026db008-a422-11e7-95fb-deb9b938b2ee.jpeg)
![wechatimg5](https://user-images.githubusercontent.com/26698885/30955099-026ee3f6-a422-11e7-99da-00acac008d6b.jpeg)

**Comment by ArtSabintsev** [comment]
Not related. If you're using Objective-C, checkout the Objective-C library: https://github.com/ArtSabintsev/Harpy
