### ISSUE TITLE
Not checking the version, because it already checked recently

### ISSUE THREAD

**Issue by dongpinyun** [ArtSabintsev/Siren#167]
[Siren] The default implementation of sirenDidFailVersionCheck(error:) is being called. You can ignore this message if you do not care to implement this method in your `SirenDelegate` conforming structure.
[Siren] Not checking the version, because it already checked recently.

**Comment by ArtSabintsev** [comment]
You have set one of your classes as `SirenDelegate`. However, you did not implement one of the methods that is called, which is fine, if you _do not_ need that method. 

You can ignore the warning if you don't need it.

To get rid of the second message, delete the app of you device, and try again.
