### ISSUE TITLE
Granular version update management for custom alert

### ISSUE THREAD

**Issue by JussiSuojanen** [ArtSabintsev/Siren#168]
Hi,

At the moment Siren informs about every update on AppStore if I set the alertType = .none. I'd like to have a bit more control about what types of updates I show the custom alert. Would it be possible to add support for revision, patch, minor & major also for custom alerts? Currently the only information is the message in the `sirenDidDetectNewVersionWithoutAlert(message: String)` delegate function.

**Comment by ArtSabintsev** [comment]
Would extending the function's signature to provide the specific version information be a fair solution?

`sirenDidDetectNewVersionWithoutAlert(version: String, message: String)`

**Comment by JussiSuojanen** [comment]
Yes, but I'd rather have an enumeration than an String. This way I don't have to do any String handling to identify the update type.
 
Something like this:
`enum UpdateType {
    case major
    case minor
    case patch
    case revision
}`

**Comment by ArtSabintsev** [comment]
can you open a  PR with the addition you want - we can take it from there. Feel free to close this issue once a PR is up if you go down that route.

**Comment by JussiSuojanen** [comment]
Ok, I try find some time later this week to do the PR.

**Comment by ArtSabintsev** [comment]
Sounds good to me. Keep me posted. I'll keep the issue open for a couple weeks.

**Comment by ArtSabintsev** [comment]
Closing this issue in favor of your PR #171.
