### ISSUE TITLE
Issue: Siren doesn't get correct version number

### ISSUE THREAD

**Issue by SahSih** [ArtSabintsev/Siren#169]
After my app released to App Store, the current version is 6.2, but from my console, I saw Siren still gets previous version number, so it doesn't show any alert for user to update.

My app is in US App Store, I wasn't uncomment "siren.showAlertAfterCurrentVersionHasBeenReleasedForDays = 0" so it should use the default value which is 1.

By the way, my app shows in App Store around 1pm but I still get previous version release information. 

Does anyone has any idea? Please feel free to comment under my post.

**Comment by ArtSabintsev** [comment]
It takes about 24 hours for the App Store JSON to show the correct version, hence the default setting of `1`. Give it time, and it should work.

**Comment by SahSih** [comment]
Thanks a lot, sir!

**Comment by ArtSabintsev** [comment]
you're welcome!
