### ISSUE TITLE
UIAlertController

### ISSUE THREAD

**Issue by dbettermann** [ArtSabintsev/Siren#17]
Hello,

First of all -- great project.

I noticed that the UIAlertController only appears if the window's rootViewController is visible when you open the app. It's not a bug with UIAlertController, but it has to do with UIAlertController being a UIViewController instead of a UIView (like UIAlertView).

Have you figured out how to show the update alert when the app resumes on a view controller that's not the rootViewController?

I've tried using a second UIWindow and then presenting the UIAlertController on that, but I ran into some odd issues.

Thanks in advance!
Dylan

**Comment by getaaron** [comment]
I think you'd run into rotation / resizing issues with that approach.

If you want to present the alert controller from a different view controller (or avoid `UIAlertController` entirely), there's a delegate method you can implement instead. Would that work for your use case?

**Comment by dbettermann** [comment]
I can't remember running into rotation or resizing issues. The issue was that there was a delay between the UIWindow appearing and the UIAlertController presenting. The window's rootViewController would intercept all the touches until the UIAlertController presented a few seconds later.

In short, it seemed like the main thread was deadlocking or thrashing.

I did see the delegate methods, but I don't think they'll work for my use case. I'm trying to make it so I can drop in the library, provide the URLs (non-AppStore apps) via a config file, and have it just work. We want to include this functionality in 100+ apps and it may be a non-developer adding the library.

I'm not expecting Siren to change at all based on my requirements. Just curious if you found a way around this "limitation" when transitioning from UIAlertViews to UIAlertControllers.

**Comment by ArtSabintsev** [comment]
Hey @dbettermann,

Thanks for the kind words. How about having Siren load once the first/second VC pops? In other words, put it in a VC's `viewDidAppear(_:)` method vs. the AppDelegate's UIApplicationDelegate methods.

**Comment by dbettermann** [comment]
@ArtSabintsev I could put the logic in viewDidAppear, but I would have to know which view controller is appearing. :)

Swizzling would work well for this case, but I'm not sure if I want to take it that far.

**Comment by getaaron** [comment]
A correct solution to this problem is dependent on your app's view controller hierarchy. You could use an approach like this:

    func sirenDidDetectNewVersionWithoutAlert(message: String) {
        var viewController = rootViewController
        
        while viewController.presentedViewController != nil {
            viewController = viewController.presentedViewController!
        }
        
        // present a view controller (ie, UIAlertController) from viewController.
    }

This isn't totally foolproof. It doesn't take into account child view controllers, or container view controllers (like `UINavigationController`).

**Comment by dbettermann** [comment]
Thanks @getaaron 

I actually had something like that previously, but I realized that it can get tricky and buggy.

Good news - I was able to get it working by making a small change to my UIWindow approach. So when I call `AppUpdater.checkForUpdates(...)` in the AppDelegate, the UIAlertController always appears.

Feel free to close the issue. Thanks again!

**Comment by ArtSabintsev** [comment]
Glad you got it working @dbettermann! Thanks, @getaaron for the responses!

**Comment by getaaron** [comment]
@dbettermann Can you describe your approach here? It might help out future readers of this issue.

**Comment by dbettermann** [comment]
@getaaron @ArtSabintsev Would you be interested in a pull request?

**Comment by ArtSabintsev** [comment]
Potentially! Show us what you've got!
