### ISSUE TITLE
Device compatibility check not performed

### ISSUE THREAD

**Issue by lauri-koli-vincit** [ArtSabintsev/Siren#173]
I was browsing the code and noticed that `isUpdateCompatibleWithDeviceOS` function is not invoked anywhere.

**Comment by ArtSabintsev** [comment]
Fixed and released as v3.1.1: https://github.com/ArtSabintsev/Siren/releases/tag/3.1.1

Thanks for catching it!

**Comment by lauri-koli-vincit** [comment]
You're welcome!
