### ISSUE TITLE
Can't use SirenError.Known in project 

### ISSUE THREAD

**Issue by Bosian** [ArtSabintsev/Siren#174]
Should SirenError and SirenError.Known be public?
For "func sirenDidFailVersionCheck(error: Error)" conform SirenDelegate
Thank you.

**Comment by ArtSabintsev** [comment]
Good catch. Will make it public now and release a new version

**Comment by ArtSabintsev** [comment]
Done! https://github.com/ArtSabintsev/Siren/releases/tag/3.1.2
