### ISSUE TITLE
Message of alert is getting truncated or showing only one line of message

### ISSUE THREAD

**Issue by Kalikanth** [ArtSabintsev/Siren#177]
First of all sorry i'm new to this. Please tell to solve this issue
in my app i'm presenting the alert. It's truncating the message to one line

let alert = CDAlertView(title:  "Truncating", message:  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s", type: CDAlertViewType.error)

     let okay = CDAlertViewAction(title: "OK", font: nil, textColor: nil, backgroundColor: nil) { (action) in
            
        }
        alert.add(action: okay)
        alert.show()

![screen shot 2017-11-06 at 9 16 06 pm](https://user-images.githubusercontent.com/29298122/32449666-3655bdd6-c338-11e7-9658-8d1906736223.png)

**Comment by Kalikanth** [comment]
![screen shot 2017-11-06 at 9 16 06 pm](https://user-images.githubusercontent.com/29298122/32449501-bd3045fc-c337-11e7-971c-72101263eb96.png)

**Comment by ArtSabintsev** [comment]
This has nothing to do with Siren. This issue is with `CDAlertView`.

https://github.com/candostdagdeviren/CDAlertView

Closing this issue.

**Comment by Kalikanth** [comment]
Sorry for that

**Comment by ArtSabintsev** [comment]
No problem! Good luck!
