### ISSUE TITLE
Lookup with bundleId not found but id is OK

### ISSUE THREAD

**Issue by PH9** [ArtSabintsev/Siren#180]
URL that generated from Siren https://itunes.apple.com/lookup/bundleId=th.co.dtac.mobilertr&country=TH

got result
```
{
  "resultCount": 0,
  "results": []
}
````

Then I looked up for Apple iTunes API and found also able to search with id https://itunes.apple.com/lookup?id=1128716471&country=TH the result is fine.

You can see for the result that show `bundleId` as same as URL above

**Comment by ArtSabintsev** [comment]
Hey,

Your first URL is wrong.

It should be: https://itunes.apple.com/lookup?bundleId=th.co.dtac.mobilertr&country=TH

**Comment by PH9** [comment]
Thank you @ArtSabintsev

**Comment by ArtSabintsev** [comment]
My pleasure - enjoy!
