### ISSUE TITLE
Minor: Apple list of country codes link broken

### ISSUE THREAD

**Issue by simonbromberg** [ArtSabintsev/Siren#183]
Link shown in comment in [AppDelegate.swift](https://github.com/ArtSabintsev/Siren/blob/master/SirenExample/SirenExample/AppDelegate.swift) is:
https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Appendices/AppStoreTerritories.html

This link no longer works.

Here is a working link:
https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/AppStoreTerritories.html

Notice change from "Appendices" to "Chapters".

**Comment by ArtSabintsev** [comment]
Feel free to open a PR :)
