### ISSUE TITLE
Update alert wording to increase conversion rates

### ISSUE THREAD

**Issue by tylerweitzman** [ArtSabintsev/Siren#188]
Hi,
I have two questions / requests on the update alert wording in order to optimize conversion.

(1) I think users would like to see what's new in the update before pressing the update button. Is it possible to have Siren automatically import this in the proper localization from iTunes?

(2) The example code in the read me specifies custom developer wording for the alert, but the readme also states that Siren is localized for many languages, how can I take advantage of the existing localization? Is there a method that uses default wording which are localized?

Thanks!

**Comment by ArtSabintsev** [comment]
Hey!

Thanks for reaching out.

1) No, the update is not localized, formatted, or useful, last I checked. I don't even recall if it's provided anymore.

2) You can only take advantage of the localization if you use the default/out-of-the-box string messaging, which you see to not want to do.

Next, from personal experience working on these apps, user's don't care, at least not your average user. I just had an app go from 0%-82% adoption in 4 days thanks to Siren. The user base is _very_ large.

Hope that helps!

**Comment by ArtSabintsev** [comment]
Just edited the post to clarify a couple things.

**Comment by ArtSabintsev** [comment]
Closing the issue. Feel free to re-open it if you want to follow up.

Happy new year!
