### ISSUE TITLE
Change alert message

### ISSUE THREAD

**Issue by Tramnguyen108** [ArtSabintsev/Siren#189]
How can I change the message of alert on brand swift3.1? Tks in advance

**Comment by ArtSabintsev** [comment]
Hey,

This only works in Swift 4 as I no longer actively develop for Swift 3.x.

```swift
let siren = Siren.shared
SirenAlertMessaging(updateTitle: "New Fancy Title",
                                                   updateMessage: "New message goes here!",
                                                   updateButtonMessage: "Update Now, Plz!?",
                                                   nextTimeButtonMessage: "OK, next time it is!",
                                                   skipVersionButtonMessage: "Please don't push skip, please don't!")
```

Good luck!

**Comment by luisfuertes** [comment]
I had it working.

But with version pod `'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift3.2' # Swift 3.2` appear this error:
`Siren Use of unresolved identifier 'SirenAlertMessaging'`

**Comment by ArtSabintsev** [comment]
Siren 4.0 changes the entire public interface. Please open a new issue if you have a problem that you need assistance with.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
