### ISSUE TITLE
Error when testing - EXC_BAD_INSTRUCTION

### ISSUE THREAD

**Issue by heelstoo** [ArtSabintsev/Siren#19]
I'm getting an error (EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode 0x0)) on the return on this:

func sirenBundlePath() -> String {
        return NSBundle.mainBundle().pathForResource("Siren", ofType: "bundle") as String!
}

Thread 1 says:
0 function signature specialization <Arg[1] = Owned to Guaranteed> of ext.MYAPP.ObjectiveC.NSBundle.(sirenForcedBundlePath in _......."

Any ideas? It seems to only crash when I try to make the app fail (by pointing towards the iTunes Connect appID, since my app isn't in the store yet to test against.

Thanks!

**Comment by ArtSabintsev** [comment]
Hi @heelstoo,

Silly question, but is Siren.bundle in your project? If not, this may be causing that issue. Make sure both Siren.bundle and Siren.swift are in your project. If it is in your project, would you mind providing me with your appID, so I amy attempt to replicate this issue?

Thanks!

**Comment by heelstoo** [comment]
Hey @ArtSabintsev 

Thanks for getting back to me. That's not a silly question at all! I'm brand new to iOS development. I had Siren.bundle in a subdirectory, but I guess that didn't take for some reason. I've copied it to the right place and it appears to have fixed the issue. Thank you so much for your help!

**Comment by ArtSabintsev** [comment]
ah, well welcome to iOS development and thank you for using this library! I'm glad you got it working!
