### ISSUE TITLE
Adjust checkType depending on alertType

### ISSUE THREAD

**Issue by jeffjvick** [ArtSabintsev/Siren#190]
Hi, 

I want to know if there is a way to accomplish the following in Siren without writing my own code using `sirenDidShowUpdateDialog`.

I would like to adjust the checkType depending on if there there is a major or minor update required.

Say I have the following set:
```
siren.majorUpdateAlertType = .force
siren.minorUpdateAlertType = .option
```

And I check .immediately in didBecomeActive:
```
func applicationDidBecomeActive(application: UIApplication) {
    Siren.shared.checkVersion(checkType: .immediately)
}
```

This works how I want it for a major update because it basically doesn't let the user proceed further until they update the app but for a minor update it is very annoying for the user in that each time the app is opened it asks them to update.  I would rather that be .daily or .weekly.  However, if I do that then on a major update the user can kill and restart the app and continue to use it for a day or week.  Neither is what I want.

Is there a way to accomplish what I'm after natively or would I need to make it myself using the delegates?

**Comment by ArtSabintsev** [comment]
I don't really see a way to do that without utilizing this delegate method: https://github.com/ArtSabintsev/Siren/blob/master/Sources/SirenDelegate.swift#L49-L50

and doing your check with `alertType` set to `.none` to avoid presenting the alert. Then, when you do present the alert, you can do a `switch` statement around the `UpdateType` and perform the appropriate check.

Also, feel free to open a PR with a better implementation. One could be turning `siren.majorUpdateAlertType` into a tuple that also takes in how often to prompt. Maybe a new set of variables that deprecates those?

What do you think?

**Comment by jeffjvick** [comment]
I think a tuple for AlertType that also includes a CheckType might be a good solution.  I can poke around the code and see if I have an implementation idea.

At the moment though I'm on a deadline for getting this out so it may be a week or two.  Thanks.

**Comment by ArtSabintsev** [comment]
Sure, I’ll mull it over as well!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by liangmark** [comment]
Hi:

I want to use Siren in my app. But when i installed it by CocoaPods(swift 2.3), I got a mistake, please see the attachment image. Could you help me to solve this  problem？@ArtSabintsev

![snip20180123_6](https://user-images.githubusercontent.com/12019458/35262222-b052f56a-004e-11e8-9312-2801d7586996.png)

**Comment by ArtSabintsev** [comment]
Please open up a new issue.

**Comment by duylinh** [comment]
I can't show alert when update new version on Apple.
MY SOLUTION: 
AppDelegate: 
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        configUpdateVersionBySiren()
}

private func configUpdateVersionBySiren() {
        let siren = Siren.shared
        siren.delegate = self
        siren.alertType = .force
        siren.showAlertAfterCurrentVersionHasBeenReleasedForDays = 0
    }

func applicationDidBecomeActive(_ application: UIApplication) {
        //For setup siren
        Siren.shared.checkVersion(checkType: .immediately)
}

func applicationWillEnterForeground(_ application: UIApplication) {
        Siren.shared.checkVersion(checkType: .immediately)
}

Change file SirenLookupModel.swift
OLD: 
public struct SirenLookupModel: Decodable {
    private enum CodingKeys: String, CodingKey {
        case results
    }

    public let results: [Results]

    public struct Results: Decodable {
        private enum CodingKeys: String, CodingKey {
            case appID = "trackId"
            case currentVersionReleaseDate
            case minimumOSVersion = "minimumOsVersion"
            case releaseNotes
            case version
        }

        public let appID: Int
        public let currentVersionReleaseDate: String
        public let minimumOSVersion: String
        public let releaseNotes: String?
        public let version: String
    }
}

NEW:
public struct SirenLookupModel: Decodable {
    private enum CodingKeys: String, CodingKey {
        case results
    }

    public let results: [Results]

    public struct Results: Decodable {
        private enum CodingKeys: String, CodingKey {
            case appID = "trackId"
            case currentVersionReleaseDate = "currentVersionReleaseDate"
            case minimumOSVersion = "minimumOsVersion"
            case releaseNotes = "releaseNotes"
            case version = "version"
        }

        public let appID: Int
        public let currentVersionReleaseDate: String
        public let minimumOSVersion: String
        public let releaseNotes: String?
        public let version: String
    }
}

**Comment by ArtSabintsev** [comment]
Alright, so it seems that only two people have requested this feature over the course of 8 months (#190 and #203). I think the case is too unique to be added to the library for now. If more people request this feature, I will revisit this request.

I am closing this issue as my philosophy is to build OSS libs for the majority of use cases. Occasionally, I do build convenience features, but as there seems to be very little interest in this specific feature set, I will have to pass on this feature.

**Comment by ArtSabintsev** [comment]
I've implemented this suggestion in #250 - that PR only needs some documentation and an update to the README before it's ready to go.

**Comment by jeffjvick** [comment]
-- adding this here since #250 is closed for comments --

Hi, I finally got free time to add Siren 4.0.0 to our app.   First of all thanks for the changes.  Your new RulesManger for for major, minor, patch, revision fixes my issue.  Now I can force users on major release to update the app while still allowing them to prolong updating by a week on minor/patch updates.

**Comment by ArtSabintsev** [comment]
You’re very welcome!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
