### ISSUE TITLE
Question about managing a database transition

### ISSUE THREAD

**Issue by Tulleb** [ArtSabintsev/Siren#192]
Thank you @ArtSabintsev for all your work.

I am not posting an issue here, but more like a recommendation of advices on how I should manage what I am supposed to do.

I have to change my database in the next version I am about to release. Therefor, I will have to apply a script which will copy my old database to the new one. And at the same time, I will have to forbid users to use the older version of my app once this script has been executed.

So, I wanted to know if there was a way to synchronise the Siren checking with the actual App Store update availability, for me to execute the script and to release the new version at the exact same time.

It is ok if the delay is 1 or 2 hours, but I was reading that Siren can take up to 24h to get the new version from Apple's availability API? So is there any workaround here...?

Thank you once again, and keep up with the good work 👍

**Comment by ArtSabintsev** [comment]
Hey,

There is no way to synchronize it with 100% certainty. By default, Siren waits `1 day` checking with the App Store to make sure the app is available through all CDNs around the world. 

My recommendation is to do a database migration, versus dumping one for the other, if that's possible in your situation.

Hope that helps!

Thanks for being a user!

**Comment by ArtSabintsev** [comment]
Closing this issue due to lack of follow up.
