### ISSUE TITLE
How do I know the current version is the latest?

### ISSUE THREAD

**Issue by lizizi** [ArtSabintsev/Siren#196]
How do I know the current version is the latest?
Is it through this method?
“func sirenLatestVersionInstalled(){
      
    }”

**Comment by ArtSabintsev** [comment]
You need to set the `SirenDelegate`, and monitor the errors that come through the `sirenDidFailVersionCheck` delegate method. Specifically, you'd receive this message if the user is already using the latest version: https://github.com/ArtSabintsev/Siren/blob/master/Sources/SirenError.swift#L44-L45
