### ISSUE TITLE
Incorrect Documentation results in no delegate callback

### ISSUE THREAD

**Issue by RamblinWreck77** [ArtSabintsev/Siren#198]
Hello! This was driving me crazy so I dove in and figured this out.

In the documentation, 

```
extension AppDelegate: SirenDelegate {
	// Returns a localized message to this delegate method upon performing a successful version check
    func sirenDidDetectNewVersionWithoutAlert(message: String) {
        print("\(message)")
    }
}
```

Doesn't work, because sirenDidDetectNewVersionWithoutAlert's arguments are out of date.

```
func sirenDidDetectNewVersionWithoutAlert(message: String, updateType: UpdateType)
```

*Does* get the delegate callback, it appears that this was updated and the documentation was not so it will just silently fail. 

Thanks for a great tool! Just wanted to share this for anyone else!

**Comment by ArtSabintsev** [comment]
@RamblinWreck77 Thanks for pointing this out! This has been fixed.
