### ISSUE TITLE
Show force update for particular version and show user confirmation for other version?

### ISSUE THREAD

**Issue by Karthigak** [ArtSabintsev/Siren#203]
Is there any method to show force update for particular version and not for all the version?
It should happen dynamically. Is there way or Do i have to go with Client-server approach?

**Comment by ArtSabintsev** [comment]
Currently, there is not. There is a request in place for this #190. It's on my to-do list, I just haven't gotten to it. Feel free to take a stab at it.

Closing this issue in favor of #190.
