### ISSUE TITLE
Extract Urls to allow users to use this framework to check update for enterprise ios apps

### ISSUE THREAD

**Issue by laocat2004** [ArtSabintsev/Siren#204]
I have submitted some modifications to extract the urls to allow users to specify the urls outside Siren framework. This modification will allow user to check the update of enterprise ios apps not deployed to apple store.

I have a sample code checked in.

**Comment by ArtSabintsev** [comment]
Hi,

This is an issue, not a Pull Request, so I cannot see your changes. Furthermore, as enterprise iOS apps have no `App Store`, each consumer of this SDK will have a completely different implementation for how to handle app updating. While this can be solved by injecting custom URLs, payloads, and error handling, this is beyond the scope of Siren.

Therefore, any PR that is opened that adds these changes will not be merged. However, I encourage you, and anyone else interested, to freely fork Siren and make any changes that will support your specific updating schema.

Thanks for opening the issue.

Best of luck!
