### ISSUE TITLE
Add change notes

### ISSUE THREAD

**Issue by shaobaili3** [ArtSabintsev/Siren#206]
Hi,

Do you have plan to add the "releaseNotes" to your project from App Store Lookup HTTP request?

I also need to display change notes in the pop up alert for my project, from "SirenLookUPModel.swift" I did not see the "releaseNotes" field was parsed by Codable in your project.

I really want to use your library in my project, but for getting the change logs, I have to parse or retrieve the JSON data again for now. Many may need this function as well.

Thank you!

**Comment by ArtSabintsev** [comment]
Done! Just merged it to the master branch. I'll tag the release later today as I'm working on a few other minor changes.

**Comment by ArtSabintsev** [comment]
Thanks for the feature request.

**Comment by shaobaili3** [comment]
Thanks!

**Comment by ArtSabintsev** [comment]
no problem - enjoy, and thanks for the suggestions!

**Comment by bawelter** [comment]
Release notes are not required so make sure to test when release notes key is not present in the JSON response

**Comment by bawelter** [comment]
Yes I just had the issue when I uprgraded. Probably occurs if you don’t populate any release notes

**Comment by ArtSabintsev** [comment]
Alright, good to know. Thanks for following up. I'll take care of it soon.
