### ISSUE TITLE
"Not checking the version, because it already checked recently."

### ISSUE THREAD

**Issue by yang511** [ArtSabintsev/Siren#207]
How are you?
I published apps 2 times
And I integrated this sdk on 2 versions, too
But when i debug for 2nd version, I got this error message
"Not checking the version, because it already checked recently."
I 'm debugging app with lower build version than 2nd build version
Please let me know what 's mean
Thanks

**Comment by ArtSabintsev** [comment]
This means that for the setting you chose, the user interacted with the version check alert modal. The next one will happen in 1-7 days, depending on your setting choice.

If you drop some of your sample code, I might be able to help.

**Comment by yang511** [comment]
Ah, Today I published 2nd version
