### ISSUE TITLE
No such delegate call in second time run after skip this version.

### ISSUE THREAD

**Issue by JayeshThanki** [ArtSabintsev/Siren#213]
I am not moving ahed when i skip version and re-run app again.
My app navigation flow is continue from delegate methods of Siren.
Now after skip version and re-run second time then there is no such delegate call available and i can not enter in app.

For example:
I am using alert type skip for all.
App Store version: 1.1
Current App version: 1.0

Now first time i launch app with after app store version update, Alert will display with three button.
I press "Skip this version". Then `sirenUserDidSkipVersion` method will call and i can enter in app.
But in second run there is no such delegate call available for enter in app.

If you already resolve this issue then let me know so i can use updated code for this. 
I have already create one delegate method for this.

```
    func showAlertIfCurrentAppStoreVersionNotSkipped() {
        alertType = setAlertType()

        guard let previouslySkippedVersion = UserDefaults.standard.object(forKey: SirenDefaults.StoredSkippedVersion.rawValue) as? String else {
            showAlert()
            return
        }

        if let currentAppStoreVersion = currentAppStoreVersion, currentAppStoreVersion != previouslySkippedVersion {
            showAlert()
        } else {
            delegate?.sirenUserDidAlreadySkipThisVersion()
        }
    }

```

`sirenUserDidAlreadySkipThisVersion` is newly created delegate method.

English is not my mother tongue; please excuse any errors on my part. 🙏

**Comment by ArtSabintsev** [comment]
Sorry for the long response time - I _just_ saw this message.

My question is _why_? Why are you doing it this way?

If a user skips the version, they don't want to see the prompt, and that's it.

**Comment by ArtSabintsev** [comment]
Closing this issue due to lack of follow up.
