### ISSUE TITLE
Version Number checking

### ISSUE THREAD

**Issue by mmdock** [ArtSabintsev/Siren#217]
Before posting an issue, please make sure your issue has not already been resolved or answered elsewhere.

[Technical Note for Version ](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364) checking suggests that version should be 3 numbers:

The build version number should be a string comprised of three non-negative, period-separated integers with the first integer being greater than zero—for example, 3.1.2. The string should only contain numeric (0-9) and period (.) characters. Leading zeros are truncated from each integer and will be ignored (that is, 1.02.3 is equivalent to 1.2.3). The meaning of each element is as follows:

The first number represents the most recent major release and is limited to a maximum length of four digits.
The second number represents the most recent significant revision and is limited to a maximum length of two digits.
The third number represents the most recent minor bug fix and is limited to a maximum length of two digits.

However, the code for Siren checks for 4 numbers.  I am confused as to where the fourth number comes from in terms of apple documentation?

The code checks for: 
`        
```
guard let newVersionFirst = newVersion.first, let oldVersionFirst = oldVersion.first else {
            return alertType // Default value is .Option
        }
```

        if newVersionFirst > oldVersionFirst { // A.b.c.d
            alertType = majorUpdateAlertType
            updateType = .major
        } else if newVersion.count > 1 && (oldVersion.count <= 1 || newVersion[1] > oldVersion[1]) { // a.B.c.d
            alertType = minorUpdateAlertType
            updateType = .minor
        } else if newVersion.count > 2 && (oldVersion.count <= 2 || newVersion[2] > oldVersion[2]) { // a.b.C.d
            alertType = patchUpdateAlertType
            updateType = .patch
        } else if newVersion.count > 3 && (oldVersion.count <= 3 || newVersion[3] > oldVersion[3]) { // a.b.c.D
            alertType = revisionUpdateAlertType
            updateType = .revision
        }`

when in fact that last `else if` shouldn't be needed

**Comment by ArtSabintsev** [comment]
This is for backwards compatibility as you used to be able to have more than three version numbers. It is not required, and that codepath is only entered when needed.
