### ISSUE TITLE
Does this library have the ability to show a change log to the user after they download a new update? If not, could you add it?

### ISSUE THREAD

**Issue by photog0411** [ArtSabintsev/Siren#223]
Does this library have the ability to show a change log to the user after they download a new update? If not, could you add it? Just a simple changlog dialog that pops up the first time the user installs a new update that would be cool. I want to be able to inform my users about what is new in the new version after they download the update but I can't find an easy way to do it manually in my code or any tutorials. I think it's amazing that there's no libraries or tutorials out there how to do this manually with iOS Swift, but on Android there's like a million changelog libraries.

It would be good if we can just specify a version and then a list of "what's new" in a .plist file or a .txt file or something in the project.

**Comment by ArtSabintsev** [comment]
Hi - I’m away from my computer for a few days, however, there is a delegate method that will return the release notes from the iTunes lookup API. That’s what you want.

Hope that helps!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by photog0411** [comment]
> Hi - I’m away from my computer for a few days, however, there is a delegate method that will return the release notes from the iTunes lookup API. That’s what you want.

Does this only return the release notes when they get the window telling them to upgrade, or also when they have already upgraded?

I am looking for it to do both, in case they have already manually downloaded the update (or got automatic update overnight) from the App Store so they can see the release notes of the new version after they run the new updated version,, like a pop up that says something like this:

"Thank you for updating to the newest version! Here's what's new:"

**Comment by ArtSabintsev** [comment]
I’ll have to look tomorrow evening when I’m back at a computer. I’ll get back to you then.

Keep in mind, the sole reason for this app’s existence is to notify a user of an update. Nothing more, nothing less.

What you’re asking for is totally legit, but the SDK can only handle it before the user updates.

I’ll get back to you with the other stuff tomorrow evening.

Also, what you’re doing is totally not kosher. The delegate method will be hit until after the request completes.

**Comment by photog0411** [comment]
I tried it this way but it didn't work

```
    func sirenNetworkCallDidReturnWithNewVersionInformation(lookupModel:  SirenLookupModel) {
    siren.alertMessaging = SirenAlertMessaging(updateTitle: "Please update!",
                                               updateMessage: lookupModel.results[0].releaseNotes!,
                                               updateButtonMessage: "Update Now",
                                               nextTimeButtonMessage: "Remind Me",
                                               skipVersionButtonMessage: "Skip")
```

**Comment by ArtSabintsev** [comment]
Can you print out the contents of the `lookupModel`?

**Comment by ArtSabintsev** [comment]
Now that I'm at a computer I can make a better assessment of what you're trying to achieve.

Siren is first and foremost a tool that alerts an app's users when a new version of an app is available. By default, it shows a `UIAlertController`. Overtime, I've exposed delegates to allow for users' to present their own alerts with custom messaging, amongst other features.

What you want to achieve needs to be done in the following manner:

```swift
    func sirenNetworkCallDidReturnWithNewVersionInformation(lookupModel: SirenLookupModel) {
        let alert = UIAlertController(title: "Please Update", 
                                     message: lookupModel.results[0].releaseNotes, 
                                     preferredStyle: .alert)
        present(alert, animated: true, completion: nil)
    }
```

This can only be done after a version check is performed and only if a new version is available.

There's no other way to achieve the functionality that you want to perform.
