### ISSUE TITLE
Need Advise: Bundle and AppStore have different formats

### ISSUE THREAD

**Issue by z4r** [ArtSabintsev/Siren#224]
Hi,
I just need some advice.

For historical reason our `CFBundleShortVersionString` has a different format than AppStore.
(E.G: `1201 -> 12.0.1`; `1213 -> 12.1.3`)

Currently I solved it forking this repo to make `public` the `currentInstalledVersion` and forcing its value in the `AppDelegate`; but I don't like this solution to propose a PR.

Can we find a safer solution (closure, delegate or something else) to solve this issue?
I'm totally available for the implementation and tests.

**Comment by getaaron** [comment]
Can you just switch your version to the semantic version format? This will also make it easier to work with other tools like fastlane.

**Comment by ArtSabintsev** [comment]
Closing issue due to lack of follow up.
