### ISSUE TITLE
How to set updateMessage left align?

### ISSUE THREAD

**Issue by hstdt** [ArtSabintsev/Siren#226]
In my opinion, the type of updateMessage can be `NSAttributedString`. Then we can pass a `NSAttributedString` to `SirenAlertMessaging`.

```swift
            let paragraphStyle = NSMutableParagraphStyle()
            paragraphStyle.alignment = NSTextAlignment.left
            let messageText = NSAttributedString(
                string: "\n" + updateMessage,
                attributes: [
                    NSAttributedStringKey.paragraphStyle: paragraphStyle,
                    NSAttributedStringKey.font: UIFont.systemFont(ofSize: 14),
                    NSAttributedStringKey.foregroundColor: UIColor.black,
                ]
            )
            
            alertController.setValue(messageText, forKey: "attributedMessage")
```

![image](https://user-images.githubusercontent.com/10215098/45858248-082dea80-bd8f-11e8-98f1-c319b08ea31b.png)

**Comment by ArtSabintsev** [comment]
Hi!

Thanks for the suggestion. Any reason you would want to do this type of messaging?

**Comment by hstdt** [comment]
@ArtSabintsev  To show updateMessages from App Store, but UIAlertController will make detail text align center.

**Comment by ArtSabintsev** [comment]
I think your request is very niche, however, you can easily do this yourself. 

I'd set alert presentation to .none and do the following:

Get the update information from the JSON here.
```
sirenNetworkCallDidReturnWithNewVersionInformation
```

Using the update information from the aforementioned delegate, and from the localized string information from this delegate, you can present an alert in this delegate.
```
sirenDidDetectNewVersionWithoutAlert
```

I may consider consolidating these delegates into two delegates in the future. I will also consider your request. If I do implement it, I'll respond back here. It may be awhile.

Hope this helps!

**Comment by hstdt** [comment]
@ArtSabintsev 

Yes, I can do it. But there are many bad implements.

1. `SirenDefaults.StoredSkippedVersion` key is not public, I need to make a hard code here If user clicked the next time button.
  
![image](https://user-images.githubusercontent.com/10215098/45886871-cd5a9f80-bdec-11e8-809e-4ff3714a8327.png)

2. `skipAction` is not public, I need to call the delegate by my self.
```swift
            let skipAction = UIAlertAction(title: "Skip this version", style: .default) {(_) in
                UserDefaults.standard.set(currentAppStoreVersion, forKey: "StoredSkippedVersion") //Not public
                UserDefaults.standard.synchronize()
                siren.delegate?.sirenUserDidCancel()
            }
```
3. I had to create a new window by myself same as Siren , otherwise `rootViewController` may be deinit sometimes

```swift
rootViewController.present(alertController, animated: true, completion: nil) //sometimes disappeared
```

**Comment by ArtSabintsev** [comment]
Ok, I understand. So if I expose the strings in `SirenAlertMessaging` to be of type `NSAttributedString`, that would fix the issue?

**Comment by ArtSabintsev** [comment]
Checkout https://github.com/ArtSabintsev/Siren/pull/228 - will that work for you?

**Comment by ArtSabintsev** [comment]
Merged that feature. It'll be available in v3.6.0 in just a moment.

**Comment by hstdt** [comment]
@ArtSabintsev 
Sorry for the late reply. But the attributedString not working for here: `newVersionMessage` is back to the type of  `String`.

```swift
let newVersionMessage: String = localizedNewVersionMessage()// Not AttributedString
let alertController = UIAlertController(title: updateAvailableMessage, message: newVersionMessage, preferredStyle: .alert)
```

Attributed detail need to call a `setValue` method.

```
myAlert.setValue(messageText, forKey: "attributedMessage")
```

https://stackoverflow.com/questions/25962559/uialertcontroller-text-alignment

**Comment by ArtSabintsev** [comment]
Don’t worry about that. I did a minor version change, so the compiler’s static analysis will give the appropriate update. 

I hindsight, I should have deprecated the other initializer, however, I also changed the concrete type of the properties, so it would not have been trivial.

Thanks for the follow up!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
