### ISSUE TITLE
Delegate method sirenLatestVersionInstalled 

### ISSUE THREAD

**Issue by danchokobo** [ArtSabintsev/Siren#227]
Hello! I want to know
will be method sirenLatestVersionInstalled called every time, when latest version already was installed?

**Comment by ArtSabintsev** [comment]
Hi!

It depends on the value you set for `VersionCheckType`: https://github.com/ArtSabintsev/Siren/blob/master/Sources/Siren.swift#L523-L534

If you set it to `.immediately`, then the version will be checked with every launch of the app.
