### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by Entalpi** [ArtSabintsev/Siren#23]
How is the Swift 2.0 support? Is anyone working on it?

**Comment by ArtSabintsev** [comment]
Yup, I'm working on it. It's my first Swift 2.0 project.

**Comment by ArtSabintsev** [comment]
I'll put it on a different branch.

**Comment by krummler** [comment]
That would be awesome! But where's the branch? :)

**Comment by ArtSabintsev** [comment]
Not here yet. Soon. I started a new job, so I'm still getting sped up there. :)

**Comment by krummler** [comment]
I'm not really a github expert, but I created a branch and converted it to Swift-2.0:

https://github.com/krummler/Siren/tree/swift-2.0

Hope this helps you!

**Comment by ArtSabintsev** [comment]
Was this done using auto-conversion?

**Comment by krummler** [comment]
Partly, auto-conversion managed to fix some simple changes (i.e. change `println()` to `print()`), most stuff had to be done by hand. 

Xcode7 also warns you more about stuff like unused vars, lets vs vars. So I also fixed warnings where they popped up :).

**Comment by ArtSabintsev** [comment]
ok awesome. My plan is to do the same, and then fundamentally change how a few things are done. 

I'm spending the entire day ramping up on Swift 2 (I got a ticket for it at work - woohoo!)

Therefore, if I have time this evening, I'll start working on an official branch, and use yours for guidance. 

Thanks, my friend!

**Comment by krummler** [comment]
Sounds good.

Hope it's any help to you. Siren is cool, I'm happy to be of service!

**Comment by ArtSabintsev** [comment]
Thanks! Much appreciated! 

I have 3 more localizations coming for it tonight, so it'd be cool if I could push multiple updates tonight!
