### ISSUE TITLE
siren keep popup update prompt old version

### ISSUE THREAD

**Issue by nubuser999** [ArtSabintsev/Siren#232]
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        
        //force update if new version release
        let siren = Siren.shared
        siren.alertType = .force
        siren.checkVersion(checkType: .immediately)
        
        return true
    }

I released 1.0.1 on 4 days ago and updated release 1.0.2  on 3 days ago, 1.0.3 yesterday.
1.03 is now on appstore

I noticed that update prompt "1.02 available" is showing up after update 1.03 on appstore.
siren always show 1.02 available on every app launch now.

Do you have any idea how to troubleshoot this issue?

**Comment by nubuser999** [comment]
Hi I have noticed my mistake sorry.
my project is version 1.#.#

However,  in app store connect, I have named new version 1.##, like 1.01~1.04.
I will create 1.0.5 for app store connect and see this issue fix.

thank you for your time

**Comment by ArtSabintsev** [comment]
Sounds good!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MrutyunjayaPanda** [comment]
hi , I noticed that update prompt "3.0 available" is showing up continously even after force update is implemented to 3.0

**Comment by ArtSabintsev** [comment]
Please open up a brand new issue and follow the instructions there. It’ll make it easier for me to help.

Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
