### ISSUE TITLE
Siren will not notify me when my version is older.

### ISSUE THREAD

**Issue by hadare1** [ArtSabintsev/Siren#233]
Hi, I'm trying to integrate Siren in my app , For some reason it will not show me the alert . 

here is my code snippit : 

      class AppDelegate: UIResponder, UIApplicationDelegate , 
      UNUserNotificationCenterDelegate,MessagingDelegate , SirenDelegate{

     func  setupSiren() {
        let siren = Siren.shared
        siren.debugEnabled = true
        siren.alertType = .force // or .force, .skip, .none
        siren.showAlertAfterCurrentVersionHasBeenReleasedForDays = 30
        siren.checkVersion(checkType: .immediately)
    }

     func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: 
    [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
   
            setupSiren()
            return true
    }
    }

In my console I see that it Siren finds my app : 
[Siren] Decoded JSON results: SirenLookupModel(results: [Siren.SirenLookupModel.Results(appID: ****, currentVersionReleaseDate: "2018-09-18T01:03:50Z", minimumOSVersion: "11.0", releaseNotes: Optional("Bugs fixed"), version: "1.19")])

I changed my version in myapp.xcodeproject to 1.18 like this . 

![image](https://user-images.githubusercontent.com/32154203/46593606-03c73880-cad6-11e8-8f48-7387ce7b1e52.png)

Am I missing something ? 

Thanks

**Comment by ArtSabintsev** [comment]
I think that's because `siren.showAlertAfterCurrentVersionHasBeenReleasedForDays` is set to `30`. 

By default, it's set to 1, which means the alert will begin prompting suers to update after the app has been in the store for 1 day.

Closing this issue, but feel free to follow up.
