### ISSUE TITLE
trackId type changed

### ISSUE THREAD

**Issue by Valgrin** [ArtSabintsev/Siren#238]
Hello,

It appears that the returned JSON from Apple has changed. It causes a parsing issue when requesting the app id.

Looks like the type of the app id has changed from `String` to `Int`

**Comment by kazukisugita** [comment]
Hi.

Same issue happning in JP store. This causes will occure often in future ??

**Comment by ArtSabintsev** [comment]
Looking into this issue and the opened PR (#239) right now.

**Comment by ArtSabintsev** [comment]
This has been fixed on master. v3.8.0 will be released shortly. Feel free to open a new issue if the problem persists.
