### ISSUE TITLE
Error parsing App Store JSON data

### ISSUE THREAD

**Issue by macah1** [ArtSabintsev/Siren#241]
Hi, I'm getting Error parsing JSON Data. I'm using Siren to check against Argentine App Store, so I have `siren.countryCode = "ar"` 
I'm using Siren 3.4.3 .  (installed with pod, using swift 4.1 branch).
this is the app : https://itunes.apple.com/ar/app/quiz-viajero/id1364974795?mt=8

I've enabled debugging and I get this log:

```
[Siren] Error parsing App Store JSON data.
Also, the following system level error was returned: typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "results", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "trackId", intValue: nil)], debugDescription: "Expected to decode Int but found a string/data instead.", underlyingError: nil))
```
What could be happening? 
thanks!

**Comment by ArtSabintsev** [comment]
Apple changed the JSON payload to return `trackId` as an `String`. It used to be an `Int. 

Please upgrade to Siren 3.8.0 as it fixes this issue.

**Comment by arshadsk5** [comment]
can you any please tell me , how to upgrade ? earlier i installed pod as below.

pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift4.1'

**Comment by arshadsk5** [comment]
pod repo update ,
solved the problem.

**Comment by arshadsk5** [comment]
after upgrading the version, i am getting errors in siren files.

**Comment by ArtSabintsev** [comment]
Please make a new ticket with your specific issue and snapshot of your podfile.
