### ISSUE TITLE
Error parsing App Store JSON data (String but found a number instead.)

### ISSUE THREAD

**Issue by Ufosek** [ArtSabintsev/Siren#245]
Hello,

Yesterday I noticed that I got such error:
```
[Siren] Error parsing App Store JSON data.
Also, the following system level error was returned: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "results", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "trackId", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))
```
Earlier I had similar error but logs were different: [https://github.com/ArtSabintsev/Siren/issues/241](url) and after update to 3.8.0 - it was gone and everything was working. Maybe Apple changed something again in API?

I have latest 3.8.0 version. 

Regards

**Comment by ArtSabintsev** [comment]
Please open a new issue with the appropriate information in the new issue template filled in, otherwise, this will take some time to figure out.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
