### ISSUE TITLE
Setting the alertType to .Force doesn't seem to work

### ISSUE THREAD

**Issue by prrrnd** [ArtSabintsev/Siren#25]
```swift
let siren = Siren.sharedInstance
siren.appID = "[APP_ID]"
siren.alertType = .Force
siren.checkVersion(.Immediately)
```

This brings up an alert with "Next time" and "Update" as options, which is the default alert type.
Am I doing something wrong?

**Comment by danielbaldonado** [comment]
I had this problem. There's a check that happens that actually sets the alertType based on what version is being updated. You have to specify which alert Type for each update kind:

```
        siren.majorUpdateAlertType = .Force
        siren.minorUpdateAlertType = .Force
        siren.patchUpdateAlertType = .Force
```

**Comment by ArtSabintsev** [comment]
Good catch on both your parts. Will fix soon.

For now, explicitly state 

```
siren.majorUpdateAlertType = .Force
siren.minorUpdateAlertType = .Force
siren.patchUpdateAlertType = .Force
```

**Comment by ArtSabintsev** [comment]
Will add this in after the Swift 2.0 merger is taken care of.

**Comment by ArtSabintsev** [comment]
Fixed in the Swift 2 branch. Closing for now.
