### ISSUE TITLE
Please upgrade to v3.8.0, as it fixes this issue.

### ISSUE THREAD

**Issue by kailahuy** [ArtSabintsev/Siren#256]
version 3.9.2 still bug, 
"Expected to decode String but found a number instead.

**Comment by ArtSabintsev** [comment]
Hi, thank you for the report. Please open a new issue and follow the directions in there for creating an issue as it will make it easier for me to re-create the situation on my end.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
