### ISSUE TITLE
'Next Time' doesn't respect UpdatePromptFrequency

### ISSUE THREAD

**Issue by kamrankhan07** [ArtSabintsev/Siren#258]
I am using the rule `RulesManager(globalRules: Rules(promptFrequency: .daily, forAlertType: .skip)`, and if I select 'Next Time' and minimize the app and come back, it shoes the alert again. However, when I kill the app and come back again, it will respect the promptFrequency. I checked the code and it sets `shouldPerformVersionCheckOnSubsequentLaunch` to true when you press 'Next Time'. I think 'Next Time' action should respect the frequency too. What do you think?

**Comment by ArtSabintsev** [comment]
Well, launch is effectively launching the app from the background, which is how I think it always worked. That’s something I need to check.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Actually, this is expected functionality. Most people don’t shut down their apps, so backgrounding an app will cause the next time trigger the next time the app is launched.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kamrankhan07** [comment]
I agree with you that it should launch, but after the specified promptFrequency.

**Comment by jeffjvick** [comment]
Hi, I'm hitting this bug as well.  If we set a rule with `promptFrequency` of `.daily` and the user hits "Next time" and then minimizes (backgrounds) and reopens the app it gives them the update prompt again.  I was under the impression that was how `.immediately` was supposed to behave.

Killing the app and restarting it doesn't seem to respect `.daily` either. Contrary to what @kamrankhan07 observed.

The only way I can get the prompt to not appear again is to click on "Update" and then not actually update and open the app again.

Unfortunately I think this will be a show stopper for us to add 4.0.1 to our app as the "Next time" is too aggressive in it's current state.

**Comment by ArtSabintsev** [comment]
Totally understand. It's next on my list of bugs to fix. Keep Siren in a separate branch for the moment before merging it into master and I'll ping you once that's fixed.

**Comment by ArtSabintsev** [comment]
Alright, I think with Siren v4.0.0, the idea of what `Next Time` meant has changed. Why? Because Siren now performs a version check _each time_ the app launches but then uses the rules to determine how often a modal presentation should occur.  

To fix this problem, I simply need to stop treating subsequent launches as a separate use case. This is done by removing the following `UserDefault`:  `shouldPerformVersionCheckOnSubsequentLaunch`. 

Therefore, clicking `Next Time` simply hides the alert without augmenting the original set rules.

**Comment by ArtSabintsev** [comment]
Fixed in https://github.com/ArtSabintsev/Siren/pull/264, which will be released as 4.0.2 in the next few minutes.

**Comment by jeffjvick** [comment]
Sounds good.  Seems like that will work. I can test out the new version.

**Comment by ArtSabintsev** [comment]
It's available now via CocoaPods as v4.0.2.

I'll keep this thread unlocked until I receive confirmation.

Thanks ahead of time!

**Comment by ArtSabintsev** [comment]
Great! Thanks for the confirmation! Locking the issue now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
