### ISSUE TITLE
Examples of specific rules implementations have non conventional rules ordering.

### ISSUE THREAD

**Issue by jeffjvick** [ArtSabintsev/Siren#259]
In the [AppDelegate](https://github.com/ArtSabintsev/Siren/blob/master/Example/Example/AppDelegate.swift) file in the **updateSpecificRulesExample** the example seems to have random ordering for the major, minor, patch custom Rules settings.  Here is how it currently is:

```
/// Major, Minor, Patch, and Revision specific rules implementations.
func updateSpecificRulesExample() {
    let siren = Siren.shared
    siren.rulesManager = RulesManager(majorUpdateRules: .annoying,
                                      minorUpdateRules: .default,
                                      patchUpdateRules: .critical,
                                      revisionUpdateRules: Rules(promptFrequency: .weekly, forAlertType: .option))
```

Something like this might be a more typical setup:
```
    siren.rulesManager = RulesManager(majorUpdateRules: .critical,
                                      minorUpdateRules: .annoying,
                                      patchUpdateRules: .default,
                                      revisionUpdateRules: Rules(promptFrequency: .weekly, forAlertType: .option))
```

Obviously one could have patch updates be forced (.critical) and minor updates be optional (.default) but that would seem to be fairly unconventional.  I might suggest for the example to use custom choices that follows a pattern of increased annoyance.  I noticed this ordering was used in **complexExample** as well.

Maybe the purpose of doing it this way was to show a developer could do it however they wanted but it just confused me as I couldn't imagine why anyone would want patch updates to be forced but minor and major updates not.

**Comment by ArtSabintsev** [comment]
Done - just pushed the changes in both examples.

Thanks for the suggestions!
