### ISSUE TITLE
iOS 8 skipAlertAction bug

### ISSUE THREAD

**Issue by 441088327** [ArtSabintsev/Siren#26]
`NSUserDefaults.standardUserDefaults().setObject(currentAppStoreVersion!, forKey:sirenDefaultSkippedVersion) 
NSUserDefaults.standardUserDefaults().synchronize()`

Did not perform this code

**Comment by ArtSabintsev** [comment]
More details please.

**Comment by ArtSabintsev** [comment]
Fixed in the Swift 2 port, which is on a different branch. 

Thanks for the report!
