### ISSUE TITLE
Rule-Dependent Alert Presentations

### ISSUE THREAD

**Issue by jeffjvick** [ArtSabintsev/Siren#260]
Siren 4.0.0

Having the ability to define different rules for different upgrade levels (major, minor, patch, revision) is great but it appears the PresentationManager is global. It would be nice if we could change the messages depending on the level of the update.  For example, a patch level update might say the default title of "Update Available" but for a major update change the title to "Update Required".  Similarly, for a major update to change the message to something more descriptive about why they are being forced to update.

Is there a way to accomplish this using the existing architecture that I'm overlooking?

**Comment by ArtSabintsev** [comment]
Hey Jeff,

No way to do that out of the box as the library is highly-localized, so it depends on certain strings localizations existing for users in different locales to see messages they are more apt to understanding. Seeing an update localized in your language is the greater goal for Siren. While what you want isn't possible out of the box, you could build your own alerts if you decide to set `alertType = .none` and then build your own alerts based on the results returned in the completion handler.

**Comment by ArtSabintsev** [comment]
Also, please update to 4.0.1 - it has some fixes and some missing documentation as well.

**Comment by jeffjvick** [comment]
Oh, I'm actually on 4.0.1, I didn't realize that.

About the localization though, if we change the default messages in the PresentationManager then localization on those strings isn't going to happen anyway, correct?  So allowing custom PresentationManagers per rule wouldn't really affect the localization effort since we are overwriting the localized strings.

I see how I could roll my own Alerts with the .none setting but I was hoping to avoid that as I'm fine with the look of the current ones, I just wanted to adjust the text.

**Comment by ArtSabintsev** [comment]
I'll add it to my to-do list - that's the best I can do right now. Quite a bit going on in my world!

Thanks for taking the time to test it and provide the constructive feedback - it's super appreciated!

**Comment by ArtSabintsev** [comment]
Hey, so I've had some time to think about this over the last week, and while I do agree that this does feel like a gap in the library, I also have not had anyone request this feature in the last 8 months, so I consider this to be a _really_ niche case. 

On top of that, I haven't thought of an elegant solution. It actually kept me awake for half the night the other day, which led me to think that any implementation would be overly complex as well.

With that in mind, this request boils down to the the 80-20 rule - build for the 80%, and this is definitely not that type of feature. Sorry :\

If you (or someone else) wants custom strings per rule, you'll/they'll have to use `alertType = .none`, and go from there.

I'm closing this issue, but not locking it (for now), in case you'd like to discuss further.
