### ISSUE TITLE
Ability to control alert display timing?

### ISSUE THREAD

**Issue by erichsu** [ArtSabintsev/Siren#265]
I am glad to see new version 4 coming up.
The simple method of `Siren.wail` is fine. Siren add observer to wait `didBecomeActive`.
However, I'd like to trigger version check on my own, for example, after editing photos, user may see update alert.
How about make `Siren.performVersionCheck` method to public?

**Comment by ArtSabintsev** [comment]
I guess, why wouldn’t you want to do it at launch? That seems like the only appropriate place to do a version check. That’s how every iOS and Mac app I’ve used works. What’s the reasoning to do it on action, rather than on start?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erichsu** [comment]
In my use case (iOS App), I may send push notification for campaign or deep link to open App.
I just want to keep these user flow smooth, not just popup a version alert to interrupt an interaction mission. That will be great if we could popup alert while we need it at a good timing.

**Comment by ArtSabintsev** [comment]
So all you'd want is to have the ability to turn off the `didBecomeActive` observer, right? Then, you'd call `wail` when you want it, right?

**Comment by erichsu** [comment]
Exactly.

**Comment by ArtSabintsev** [comment]
Alright, I had some thoughts on this again. Right now, the only way the entire flow is kicked off is when the aforementioned observer is signaled. 

This means I'd need to expose some code publicly to allow you to manually prompt your users. I'll think about how best to go about doing this as I'm not sure I want to just yet as your requirement is an edge case in my mind.

**Comment by BelfDev** [comment]
Making Siren.performVersionCheck method public would also be of great use to my case. I first consult a RemoteConfig for specific versions that should prompt the UIAlertController. Only after I have finished the request I let Siren run its flow. 

I am currently facing issues with the timing which "didEnterBackgroundNotification" is triggered. Obviously, it is triggered before I obtain a response from Firebase -- preventing Siren from prompting the UIAlertController as it was supposed to.

**Comment by ArtSabintsev** [comment]
Got it - ok. I'll have a solution in place this weekend.

**Comment by ArtSabintsev** [comment]
here's my solution: https://github.com/ArtSabintsev/Siren/pull/268

What do yo think?

**Comment by erichsu** [comment]
`shouldPerformVersionCheckonOnStateChange: Bool = false` is good enough for my use case.

However, lazy developer like me could misunderstood what the argument means...
If we don't look at the comments, somebody may not know it implies that will perform version check immediately.

IMHO, It might be better we could convert the boolean value into enumeration.
And enumeration is more flexible and extensible to declare the method `wail`'s behavior.
How about make the options from `Bool` to `enum`?
e.g. 
```swift
enum PerformType {
  case immediately, onEnterForeground, idle(wait: TimeInterval)
}
```

```swift
func wail(with option: PerformType = .onEnterForeground,
    completion handler: ResultsHandler? = nil) {
         resultsHandler = handler
         addObservers()		
    switch option {
    case .onEnterForeground: addObservers()
    case .immediately:
             removeObservers()
             performVersionCheck()
    case idle(let wait): // TODO:...
    }
}
```

**Comment by ArtSabintsev** [comment]
Not a bad idea. Let me think this through a bit! Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
ok, implemented your idea. Check it out now and test it out. If it works, I'll merge it in and tag/release it as `4.1.0`. It also contains a fix for #267.

**Comment by erichsu** [comment]
Awesome! 

I just have a quick test on my project, it works great.

Thanks a lot~

**Comment by ArtSabintsev** [comment]
Thanks a ton!

Going to merge it in now and cut a version.

**Comment by ArtSabintsev** [comment]
Merged.

**Comment by ArtSabintsev** [comment]
4.1.0 is now live. Release notes are here: https://github.com/ArtSabintsev/Siren/releases/tag/4.1.0
