### ISSUE TITLE
Alert stacks on

### ISSUE THREAD

**Issue by mmdock** [ArtSabintsev/Siren#267]
I think issue 91 might have re-emerged, or this is something similar but unrelated (there have been a lot of version updates since that issue.)

@ArtSabintsev in version 4.0.1 of Siren:

For Critical and Annoying:
Open my app, alert shows, *close app*, reopen: correctly  works.
Open my app, alert shows, *put app in background*, bring app to foreground: A second copy of the alert display on top of the previous one.  

Haven't testing any other rule strategies other than Critical/Annoying

**Comment by ArtSabintsev** [comment]
Hey! Pleas try 4.0.2 - that’s the latest version and please report back.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by antoinepemeja** [comment]
Hello,

I use Siren (4.0.2) and I have this issue (in iOS 12.1.3)

For critical, when my app is in background (when I **double** tap on home button) and back in foreground, a new alert pop above a previous alert.

But when the app is in background when I tap just **once** on home button, there isn't the issue.

Thank you @ArtSabintsev

**Comment by ArtSabintsev** [comment]
Ok, I think I know why that’s happening. I’ll look into it this weekend.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
This is fixed in #268, which will get merged in soon.

**Comment by ArtSabintsev** [comment]
Alright, the fix is ready to be merged. It addresses issues in this issue and #265.

**Comment by ArtSabintsev** [comment]
4.1.0 is now live. Release notes are here: https://github.com/ArtSabintsev/Siren/releases/tag/4.1.0
