### ISSUE TITLE
How to stop starting viewDidLoad if the app is NOT the latest version.

### ISSUE THREAD

**Issue by shibatom** [ArtSabintsev/Siren#272]
I'd like to stop starting viewDidLoad on my main ViewController when users app is not the latest version.

My ideal implementation is when users app is not the latest version, the app shows an update alert and keeps to display my launch screen.

Could I ask you how to implement this function by using Siren?

My current code in AppDelegate.

    let siren = Siren.shared
    siren.forceLanguageLocalization = Siren.LanguageType.japanese
    siren.debugEnabled = true
    siren.alertType = .force
    siren.countryCode = "jp"
    siren.checkVersion(checkType: .immediately)
  

In this case, the app can not handle starting viewDidLoad timing by using a result from Siren.

I use Version 3.6.0 of Siren.

Thanks

**Comment by ArtSabintsev** [comment]
Hi,

I no longer offer support for any version of Siren below the latest, which is v4.2.1 at this point in time.

Also, there is no way to stop viewDidLoad. You can use the `force` option, as you are to stop app loading, but you can't keep someone on a launch screen. That's the iOS limitation.

You could make your first screen show the same screen as the launch screen in viewDidLoad until the user goes through the Siren flow.

**Comment by ArtSabintsev** [comment]
Closing this issue, but feel free to follow up if you have more questions.

**Comment by ArtSabintsev** [comment]
Locking the issue as there's been no follow up.
