### ISSUE TITLE
check version fail first publish

### ISSUE THREAD

**Issue by emonfil87** [ArtSabintsev/Siren#275]
publish the first version of my app (1.0) and when I download it and open the app it shows me the message that there is a new version available (1.0), why does this happen if it is the only version I have?

**Comment by ArtSabintsev** [comment]
I need a lot more detail. 

Please open up a new Issue and follow the guidelines listed in the Issue template: https://github.com/ArtSabintsev/Siren/issues/new

Closing this issue as it does not contain enough detail.
