### ISSUE TITLE
How to get AppStore version number?

### ISSUE THREAD

**Issue by HarryPT** [ArtSabintsev/Siren#276]
Thanks for your comfortable and easy to use library.
I was trying to customize alert message with AppStore latest version number but it was impossible.
Could u teach me how to get AppStore latest version number calling one method from this library, please?

**Comment by ArtSabintsev** [comment]
Hey!

Example here:
https://github.com/ArtSabintsev/Siren/blob/master/Example/Example/AppDelegate.swift#L59

Call Siren, and in the completion handler, call `results.lookupModel` to gain access to the model. 

Call `version` on `lookupModel`: https://github.com/ArtSabintsev/Siren/blob/master/Sources/Models/LookupModel.swift#L51

So:

```swift
Siren.shared.wail { (results, error) in
            if let results = results {
                print("App Store Version: ", results.lookupModel.version)
            } else if let error = error {
                print(error.localizedDescription)
            }
        }
```

Hope that helps!

**Comment by HarryPT** [comment]
Thank you for your reply.
But I got this error.
![Screen Shot 2019-03-13 at 22 48 49](https://user-images.githubusercontent.com/36420861/54293279-3d9aee80-45e2-11e9-9220-4ecfabe1e041.png)
Hope your help.

**Comment by HarryPT** [comment]
And I think completion handler will be called when alert button is tapped so it's impossible to get before alert shows.

**Comment by ArtSabintsev** [comment]
Hey,

Sorry - here's the code `results.lookupModel.results.first?.version` - I may add a convenience method for this soon.

Also, you can call `Siren` without showing an alert presentation by passing in `.none`:
 to the rules manager
```swift
        let siren = Siren.shared
        siren.rulesManager = RulesManager(globalRules: Rules(promptFrequency: .immediately,
                                                             forAlertType: .none))

        siren.wail { (results, error) in
            if let results = results {
               print("LookupModel ", results.lookupModel.results.first?.version)
            } else if let error = error {
                print(error.localizedDescription)
            }
        }
```

**Comment by ArtSabintsev** [comment]
This has been exposed in #279

**Comment by ArtSabintsev** [comment]
https://github.com/ArtSabintsev/Siren/pull/279

**Comment by ArtSabintsev** [comment]
Implemented in https://github.com/ArtSabintsev/Siren/pull/279.
