### ISSUE TITLE
Swift 5 Support w/ Cocoapods

### ISSUE THREAD

**Issue by jlaws** [ArtSabintsev/Siren#277]
## Expected Results

No warning to convert Siren.framework to Swift 5

## Actual Results

Xcode created warnings to convert Siren.framework to Swift 5

## Steps to Reproduce

Build the cocoapod in Xcode 10.2

**Comment by ArtSabintsev** [comment]
It’s on my plate for today - thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Here's a working branch: `https://github.com/ArtSabintsev/Siren/tree/swift5`

**Comment by ArtSabintsev** [comment]
I want to make some changes that incorporate the Result type and a few other things, so a formal release will be a little bit off (maybe a week)?

**Comment by ArtSabintsev** [comment]
I just pushed the fix in the current WIP `swift5` branch.

**Comment by ArtSabintsev** [comment]
Done. Will be released in a few mins as Siren v5.

**Comment by jlaws** [comment]
Thanks for the fast turnaround!

**Comment by ArtSabintsev** [comment]
My pleasure!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
