### ISSUE TITLE
Question: Update button appears to the left, Later/Next appears on the right - can we swap these?

### ISSUE THREAD

**Issue by emanharout** [ArtSabintsev/Siren#278]
# If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**:  Yes, 4.2.2
- **What is your app's Bundle ID?**: N/A
- **When was the latest version of your app published to the App Store?**:  N/A
- **Is your app published in the US App Store? If not, what App Store is it published in?**: N/A
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**: N/A

---

So the pod works great, but the "Update" button in the alert appears on the left side. I noticed in the docs/images in the README we see the Update button on the right side, and the Next Time button on the left. Is there any way to mimic this behavior?

Currently my "Later" button appears on the right side.

**Comment by ArtSabintsev** [comment]
Hmm, must have occurred during the refactor. I'll address it in the Swift5 branch shortly.

**Comment by ArtSabintsev** [comment]
Implemented in https://github.com/ArtSabintsev/Siren/pull/279.
