### ISSUE TITLE
Crashes on wail()

### ISSUE THREAD

**Issue by yusuftor** [ArtSabintsev/Siren#280]
I am using the latest version of Siren (v5.0.0), and now when I run my app it crashes on the line `siren.wail()`. Why? It worked in the previous version but not with this latest update. This is my full code for initiating Siren called on `didFinishLaunching`:

```
let siren = Siren.shared
let rules = Rules(promptFrequency: .immediately, forAlertType: .option)
siren.rulesManager = RulesManager(globalRules: rules)
siren.wail() //Crashes here
```

The error says:

>dyld: lazy symbol binding failed: Symbol not found: _$s5SirenAAC4wail12performCheck10completionyAA07PerformD0O_ys6ResultOyAA13UpdateResultsVAA10KnownErrorOGcSgtF

**Comment by ArtSabintsev** [comment]
Are you using Xcode 10.2?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yusuftor** [comment]
Yep

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ergunkocak** [comment]
Also an example would be great on migration to version 5. Like how to migrate this:

        siren.wail { (results: Results?, error: KnownError?) in
            if let results = results {
                // update available go go go
            } else if let error = error {
                print(error.localizedDescription)
            }
        }

**Comment by ArtSabintsev** [comment]
@yusuftor I can't get it to crash in the simulator on 10.2 using that code.

@ergunkocak take a look at the sample app, specifically this line: https://github.com/ArtSabintsev/Siren/blob/master/Example/Example/AppDelegate.swift#L55

**Comment by ArtSabintsev** [comment]
Cannot duplicate it on device either. Please open a new issue with a sample project attached that faithfully reproduces the bug for you.
