### ISSUE TITLE
Date Extension Calculation Mistake

### ISSUE THREAD

**Issue by fahlout** [ArtSabintsev/Siren#283]
With the latest update to my app I noticed that the app was not showing the alert popup at the time that I was expecting it to, which should be 24hours after the release time as taken from the iTunes API.

```json
"currentVersionReleaseDate": "2019-04-09T20:10:40Z"
```

> The T is just a literal to separate the date from the time, and the Z means "zero hour offset" also known as "Zulu time" (UTC).

In fact, I played around with your Date extension code and noticed that even though the current date as calculated using Date() is treated as UTC when doing calculations the date string coming from the iTunes API is treated as the users current time zone when converted to a Date object resulting in a 5 hour offset in my case, which means the alert really pops up 5 hours later than it should.

Making sure that the date formatter uses GMT/UTC as the time zone will make it use the correct time in all calculations. I have attached my playground file and really the only thing that is different from your code is me setting the time zone. I did add some print statements to show my process, but nothing other than the time zone setting that makes any of your code different from what it is in Siren.

<img width="1249" alt="Screen Shot 2019-04-11 at 9 51 17 AM" src="https://user-images.githubusercontent.com/6654714/55967552-1fa3c680-5c40-11e9-9938-e77588949de0.png">
<img width="1249" alt="Screen Shot 2019-04-11 at 9 51 30 AM" src="https://user-images.githubusercontent.com/6654714/55967542-1ca8d600-5c40-11e9-882f-336dfba53821.png">

> In both screenshots the code was modified to show hours instead of days between the dates to show that the dates are off by a certain amount of hours. Actual code uses day component.

As you can see in the first screenshot the dates are off by 5 hours since I am in CDT timezone. The dates highlighted in the red boxes should be the same, which they are once making the change of adding a time zone to the date formatter as shown in the second screenshot.

[Siren-DateExtension.playground.zip](https://github.com/ArtSabintsev/Siren/files/3069231/Siren-DateExtension.playground.zip)

**Comment by fahlout** [comment]
I have created a [pull request](https://github.com/ArtSabintsev/Siren/pull/284) for this as well.

**Comment by fahlout** [comment]
As I keep thinking about it it may be better to make the days since function a bit more generic and take in a time zone that defaults to GMT/UTC.

```swift
static func days(since dateString: String, timeZone: TimeZone? = TimeZone(secondsFromGMT: 0)) -> Int? {
    let dateformatter = DateFormatter()
    dateformatter.locale = Locale(identifier: "en_US_POSIX")
    dateformatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss'Z'"
    dateformatter.timeZone = timeZone
    
    guard let releaseDate = dateformatter.date(from: dateString) else {
        return nil
    }
    
    return days(since: releaseDate)
}
```

**Comment by ArtSabintsev** [comment]
hey! Thanks so much for working on this issue. I'll take this weekend.

**Comment by ArtSabintsev** [comment]
Closing this issue in favor of the PR in #284.
