### ISSUE TITLE
Don't notify to user 

### ISSUE THREAD

**Issue by oTranAnhMinh** [ArtSabintsev/Siren#285]
Hello,

Don't notify to user when there is a new version in the AppStore. Please check and fix it.

Thanks,

**Comment by ArtSabintsev** [comment]
Sorry, could you please elaborate on what you mean or reference some code that may not be working properly? Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Closing this issue due to lack of follow up.
