### ISSUE TITLE
unable  to use  Siren.shared.wail() its says Siren has no member  wail()

### ISSUE THREAD

**Issue by fahadDev6** [ArtSabintsev/Siren#287]
# If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: 
- **What is your app's Bundle ID?**: 
- **When was the latest version of your app published to the App Store?**: 
- **Is your app published in the US App Store? If not, what App Store is it published in?**:
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**:

---

# Before posting an issue, please make sure your issue has not already been resolved or answered elsewhere.

## Common Issue #1:
>"Error retrieving iOS version number as there was no data returned."

Check if your app is available in the US App Store, otherwise add the corresponding country code when setting up Siren.

## Common Issue #2:
> "Support for macOS App Store."

Siren does not and will not support the macOS App Store.

## Common Issue #3:
> "Support for prompting TestFlight users to update to the newest beta build."

Siren does not support this functionality. There is no publicly accessible TestFlight API akin to that of the public App Store API that Siren can utilize to provide this functionality.

# Please delete this text before submitting a new issue.

**Comment by ArtSabintsev** [comment]
Hi,

I see you have an issue around accessing `wail`. Please follow the directions in the `New issue template` and open a new PR with context, sample code, etc.

Thanks!
