### ISSUE TITLE
Siren.shared.wail { results not triggered

### ISSUE THREAD

**Issue by ergunkocak** [ArtSabintsev/Siren#288]
Hello,
As always first of all thanks for the library. Before Migrating to 5.x i did not have this problem.
My apps version on app store is 3.5.9 and my local build has the version number 3.5.9. But siren is alerting me that there is a new version 3.5.9 ???

Here is the code :

        let siren = Siren.shared
        siren.apiManager = APIManager(countryCode: "DE")
        siren.rulesManager = RulesManager(majorUpdateRules: .default,
                                          minorUpdateRules: .default,
                                          patchUpdateRules: .default,
                                          revisionUpdateRules: Rules(promptFrequency: .daily, forAlertType: .none))
        siren.wail { results in
            print("blaaaaa")
            switch results {
            case .success(let updateResults):
                lapp.l("Siren: UpdateType \(updateResults.updateType.rawValue)")

            case .failure(let error):
                lapp.w(error.localizedDescription)
            }
        }

I put a debug breakingpoint in print line but it never enters in closure.
I created a new version in appStore 3.6.0 but it is not released yet. I mean it is not even sent to app review.

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: Yes 5.0.1
- **When was the latest version of your app published to the App Store?**: A week ago
- **Is your app published in the US App Store? If not, what App Store is it published in?**: German App Store
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**: Did not try

**Comment by ArtSabintsev** [comment]
Thanks for the message! 

That is quite strange! 

What is your bundleID?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ergunkocak** [comment]
@ArtSabintsev emailed

**Comment by ArtSabintsev** [comment]
Thanks.

I logged out the results of the model in the completion handler and here is what I see:

```json
 Model(appID: 965186246, currentVersionReleaseDate: "2019-05-02T05:55:34Z", minimumOSVersion: "9.3", releaseNotes: Optional("Während Sie nach weiteren Trading-Chancen suchen kümmern wir uns darum, die nextmarkets Erfahrung besser zu machen.\nEgal wo der Markt gerade steht, nextmarkets ist an Ihrer Seite.\n\nFür Feedback wenden Sie sich bitte an service@nextmarkets.com oder benutzen Sie die integrierte Feedback-Funktion in der App."), version: "3.5.9.")
```

Says 3.5.9 is the newest version, so I've confirmed that what you are seeing is correct.

This is definitely a bug. I will look at it as soon as I can.

**Comment by ArtSabintsev** [comment]
ok, I found the bug, but need to spend a little but of time thinking about how to fix it.

**Comment by ArtSabintsev** [comment]
Closing this issue as  #289 fixes this issue. Will merge it in and release as v5.1.0 shortly.
