### ISSUE TITLE
Document default rule settings

### ISSUE THREAD

**Issue by mtrezza** [ArtSabintsev/Siren#292]
It seems as if the default rule setting is not documented outside of code.

The docs inside and outside of code currently refer to the default rule settings. It would help to find those documented somewhere, on a parameter basis.

**Comment by ArtSabintsev** [comment]
Hi! They are documented at www.sabintsev.com/Siren. The link is at the top of the Siren’s GitHub URL. I can add it to the README if you think that will help?

**Comment by mtrezza** [comment]
Ah alright, that's what I was looking for. Didn't find the link, so maybe adding it more prominently might help, or I just need new glasses.

**Comment by ArtSabintsev** [comment]
Just checked - it’s already in the README under current features. Has a link and says 100% documented

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Glad it’s working for you! Locking this thread due to the issue being resolved!

Have a great day!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
