### ISSUE TITLE
can I use customize view controller instead of UIAlertController?

### ISSUE THREAD

**Issue by msaliroteh** [ArtSabintsev/Siren#293]
I'd like to use Siren in my app written in Swift 4.2. From the examples I see that I can customize the text used in the alert view. But is it possible to customize the UI further than just the text/tint? For example if I don't want to present a UIAlertController and instead want to present my own view controller, is it possible to do that ?

**Comment by ArtSabintsev** [comment]
Hi - yes, you can achieve this by initializing the `RulesManager` with a custom `Rule` that sets `alertType = .none`

https://github.com/ArtSabintsev/Siren/blob/a759b4b9479b9e527e5d787626b6cae5af6d4010/Sources/Models/Rules.swift#L78

From there, you can use the information in the closure to present a custom alert.

Feel free to follow up if you need more assistance.
