### ISSUE TITLE
Results Handler not called

### ISSUE THREAD

**Issue by kamrankhan07** [ArtSabintsev/Siren#294]
When app is minimized, resultsHandler is not called on dismissing alert. My code has some logic/flags that depends on result handler being called back, after I minimize the app, the alert disappears and no callback is received. 
I am using .onDemand perform check method.

```
func addBackgroundObservers() {
        if willResignActiveObserver == nil {
            didBecomeActiveObserver = NotificationCenter
                .default
                .addObserver(forName: UIApplication.willResignActiveNotification,
                             object: nil,
                             queue: nil) { [weak self] _ in
                                guard let self = self else { return }
                                self.presentationManager.alertController?.dismiss(animated: true, completion: nil)
            }
        }

        if didEnterBackgroundObserver == nil {
            didEnterBackgroundObserver = NotificationCenter
                .default
                .addObserver(forName: UIApplication.didEnterBackgroundNotification,
                             object: nil,
                             queue: nil) { [weak self] _ in
                                guard let self = self else { return }
                                self.presentationManager.alertController?.dismiss(animated: true, completion: nil)
            }
        }
    }
```

**Comment by kamrankhan07** [comment]
Also updaterWindow.isHidden will not work, as updaterWindow always creates a new instance. I am also seeing more than 1 alert windows in some scenarios where I use .onDemand perform check.
```
if rules.alertType != .none && updaterWindow.isHidden {
            alertController?.show(window: updaterWindow)

        }
```

**Comment by kamrankhan07** [comment]
For my use case using.onDemand, it suited me to not have any background observers (`addBackgroundObservers()`). This way the alert will not dismiss on resign active, and when app is active again user can interact with the alert. 
I don't know if the following fits with all your other use cases, but this following change suited my use case. 
```
func wail(performCheck: PerformCheck = .onForeground,
              completion handler: ResultsHandler? = nil) {
        resultsHandler = handler

        switch performCheck {
        case .onDemand:
            removeForegroundObservers()
            removeBackgroundObservers()
            performVersionCheck()
        case .onForeground:
            addForegroundObservers()
            addBackgroundObservers()
        }

        // Add background app state change observers.
        //addBackgroundObservers()
    }
```

**Comment by ArtSabintsev** [comment]
Have you tried using `.onForeground` to fix the issue in your use case / scenario?

**Comment by kamrankhan07** [comment]
.onForeground works good, however I want to have more control over when I should check for force update, with .onForeground it will automatically check once app is active again. 
.onDemand is good for my use case but then it causes the alert to disappear when app is not active (or go to background) and completion handler is not called. App Notifications for active and inactive are arbitrary too, if I handle them in my own controller, because of which sometimes I see two alerts one over another. 
I know most of the people will not want user to interact with the app once its time for force update, but I don't always force update the app, sometimes just give optional alert to update and this alert is shown after showing some other popups related to app.

**Comment by ArtSabintsev** [comment]
Yes, this is a super specific case that is unique to you, I think. Unfortunately, I will not be able to implement this change. Feel free to fork siren and make the changes that you mentioned earlier.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
