### ISSUE TITLE
Alert dismissing and not showing again

### ISSUE THREAD

**Issue by msaliroteh** [ArtSabintsev/Siren#295]
I've successfully integrated Siren into my app by updating _AppDelegate.swift_ as such:

```
    func  application(_ application: UIApplication,
                      didFinishLaunchingWithOptions launchOptions:
                                 [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        ...
        self.window?.makeKeyAndVisible()

        let siren = Siren.shared
        siren.rulesManager = RulesManager(globalRules: Rules(promptFrequency: .daily,
                                                             forAlertType: .skip))
        siren.wail()

        return true
    }
```

But the problem is that, when I deploy & launch my app for the first time, I see the Siren alert dialog followed by 2 other alert dialogs (asking user permission to send notifications & use their location).

The subsequent dialogs automatically dismiss the Siren dialog. So the next time that I launch the app I don't see the Siren dialog and the error code it comes back with is _.recentlyPrompted_

I can work around this by changing `promptFrequency: .daily` to `promptFrequency: .immediately` but I really need `.daily` behavior for my app. Any ideas on how to fix this issue?

**Comment by ArtSabintsev** [comment]
Yes, don’t show the siren dialogue right away. Wait until after the system dialogs have been shown, to show siren. You do not have to have siren in the app delegate, that’s just the most optimal place for it based on the type of alerting you want to do

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
