### ISSUE TITLE
Feature request: add localization support for Romanian

### ISSUE THREAD

**Issue by msaliroteh** [ArtSabintsev/Siren#296]
You have an impressive list of languages where the default strings are localized into, but looks like Romaninan (ro) is missing. Would be nice to have that added too. Thanks

**Comment by ArtSabintsev** [comment]
Thanks - Would you mind providing me with the localization if this is a language you speak?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Closing this issue due to lack of follow up and my lack of access to someone who speaks Romanian.
