### ISSUE TITLE
Can't detect latest AppStore version

### ISSUE THREAD

**Issue by HarryPT** [ArtSabintsev/Siren#297]
Thanks for your comfortable and easy to use library.
I was trying to get latest version on AppStore using wall() function but it didn't work.
Current AppStore version is 2.1.0 but wall() returns previous version - 2.0.0
I hope you know reason and help me.

**Comment by ArtSabintsev** [comment]
How recently was 2.1.0 released? Was it in the last 24-72 hours?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HarryPT** [comment]
Thank you for fast reply. :)
Yes, it was in last 24-72 hours. exactly 1 day.

**Comment by ArtSabintsev** [comment]
Yup, that’s why. Give it a tad bit longer - it’s Apple CDN issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
