### ISSUE TITLE
Operand of postfix '?' should have optional type; type is '(String, AnyObject)'

### ISSUE THREAD

**Issue by ceyhuno** [ArtSabintsev/Siren#3]
Compiler error on Xcode 6.1.1 in **Siren.swift** line **319**

**Comment by ArtSabintsev** [comment]
@ceyhuno Not seeing any compiler errors on my end on this line:

`self.currentAppStoreVersion = results["results"]?[0]?["version"]? as? String`

The Sample App I have is compiling and working for for me. What AppID are you seeing this issue with?

**Comment by ceyhuno** [comment]
The Sample App works for me too. But when I copy it to my project (an app written in swift with deployment target 7.1) I get the compiler error. It doesn't even build. I haven't written any code for Siren in AppDelegate.swift.

It is the optional in 'results["results"]?', I think the compiler doesn't understand if it's the whole dictionary which is optional or the value in the dictionary.

**Comment by getaaron** [comment]
@ceyhuno I also don't get a compiler error, even if I change the deployment target to 7.1.

**Comment by getaaron** [comment]
I am able to reproduce the compiler error you mention on Xcode 6.0.1. Are you sure you're actually running the latest version of Xcode? You might want to try a fresh install if so.

**Comment by ceyhuno** [comment]
Yeah I'm sure. I had installed it through App Store. It's 6.1.1 (6A2008a). I'll make a fresh install anyways to prevent further errors.

**Comment by getaaron** [comment]
Can you upload a sample project that reproduces the issue?

**Comment by ceyhuno** [comment]
It is somehow related to using Realm in the project. I have created a repo for the sample project, it includes Realm v0.89.2 -> https://github.com/ceyhuno/SirenWithRealm

**Comment by ArtSabintsev** [comment]
Currently not near a computer - will check it out as soon as I get home. 

Quick question though - Did you make any changes to the Xcode project settings? I know everyone does it all the time, including myself, but maybe Rrealm has a requirement for certain compiler flags to be set that could be causing the issue.

**Comment by ceyhuno** [comment]
Just made the target 7.1, nothing else. 
To add Realm I just copied 2 files(Realm.framework and RLMSupport.swift) and linked "libc++.dylib" dynamic library. 
You can find the instructions here -> http://realm.io/docs/cocoa/0.89.2/ under "Manual Installation".

**Comment by ArtSabintsev** [comment]
Downloaded the library and I see the error now. Will dig into it.

**Comment by ArtSabintsev** [comment]
Even after removing the libc++ dependency and realm, the issue persists.

**Comment by ArtSabintsev** [comment]
Well this is interesting. Apparently, when I remove Siren from your app, and then reinstall it using cocoapods, the error goes away. 

Cocoapods must be setting some sort of compiler flags that silence that warning. What I'm going to do now is make a new project and drag-and-drop Siren into it and see what happens.

**Comment by ArtSabintsev** [comment]
Hmm, so manually dragging Siren into a new project doesn't cause the error to pop up. 

So, to recap, I did the following:

- Downloaded your app and saw that the error existed
- Removed Siren from your app and reinstalled it using Cocoapods, and therefore reopened your project in an XCWorkspace instance.
- Your app compiled without warnings/errors when having Siren installed via Cocoapods
- Created a fresh XCode project and installed Siren manually - eveyrhting compield.

I'm relaly not sure why you're hvaing this issue at this point in time.

**Comment by ceyhuno** [comment]
1. Created a new Swift project for iPhone 
2. Copied Realm.framework and RLMSupport.swift (for version 0.89.2)
3. Linked libc++.dylib library
4. Copied Siren folder
5. Made a build
I get a Swift compiler error for Siren

After that I removed libc++ and Realm and cleaned the project with CMD+Shift+K
Now I don't get a compiler error.

This is weird. Maybe I should mention it to the Realm guys

**Comment by ArtSabintsev** [comment]
It might be worthwhile. I've been reworking part of Siren to make it safer, including modifying how/what i chain optionally. I'm using your project as one of my test cases.

**Comment by ArtSabintsev** [comment]
I updated Siren to 0.2.0. The changes I implemented address now compile in your project.

Try it out, but not through cocoapods, as I'm getting a funky error trying to push the pod. @getaaron mind taking a look?

**Comment by ArtSabintsev** [comment]
Closing this issue.

@ceyhuno feel free to respond in here with nay update you may have re: your status of getting Siren running with Realm.

@getaaron I created this (https://github.com/ArtSabintsev/Siren/issues/5) to keep track of the CocoaPods support request.

**Comment by ceyhuno** [comment]
OK now it works perfectly

**Comment by ArtSabintsev** [comment]
Happy to hear that! Thanks for bringing it to our attention!
