### ISSUE TITLE
target iOS 7 or later

### ISSUE THREAD

**Issue by 441088327** [ArtSabintsev/Siren#30]
![image](https://cloud.githubusercontent.com/assets/1632740/9846545/6c2a7872-5b05-11e5-9b31-943c4cde7dc0.png)

**Comment by ArtSabintsev** [comment]
Hi,

Siren is no longer supporting iOS 7, as iOS 7 makes up 12% of the entire ecosystem. In 2-weeks time, this number will be even lower, due to the release of iOS 9.
