### ISSUE TITLE
Cannot convert value of type '(_) -> ()' to expected argument type 'PerformCheck'

### ISSUE THREAD

**Issue by DavidBenz02** [ArtSabintsev/Siren#300]
<img width="874" alt="Capture d’écran 2019-07-24 à 14 33 07" src="https://user-images.githubusercontent.com/48349015/61770547-1a017380-ae20-11e9-9acb-cb0776e76ce6.png">

I'm using Swift 4.2 and downloaded Siren today.

**Comment by ArtSabintsev** [comment]
Hi,

Per the installation instructions, please use the `swift4.2` branch: https://github.com/ArtSabintsev/Siren#installation-instructions
