### ISSUE TITLE
Feature request: add localization support for Romanian

### ISSUE THREAD

**Issue by msaliroteh** [ArtSabintsev/Siren#302]
I opened this issue previously [here](https://github.com/ArtSabintsev/Siren/issues/296) but that was closed so I couldn't add to it.

I don't speak Romanian but sent the strings to our translation team and just got back the strings (it was of a lower priority for them so it took a while, and I didn't want to rely on Google Translate since their results are not always accurate).

Here are the strings if you would like to add support for Romanian (ro) language:

```
"A new version of %@ is available. Please update to version %@ now." = "Este disponibilă o nouă versiune de %@. Actualizați acum versiunea la %@."

"Update Available" = "Actualizare disponibilă"

"Next time" = "Data viitoare"

"Skip this version" = "Ignor această versiune"

"Update" = "Actualizare"
```

**Comment by ArtSabintsev** [comment]
I just released it as v5.1.2 - thanks again!
