### ISSUE TITLE
Getting error when  presenting siren popup.

### ISSUE THREAD

**Issue by raza08** [ArtSabintsev/Siren#303]
I write code with rules but I'm getting the error  message on my console and pop up an alert is not present, whereas I tried with siren example also, it is also not working with *defaultExampleUsingCompletionHandler()*, every time I get 

`Siren Error] Siren will not present an update alert if it performed one too recently. If you would like to present an alert every time Siren is called, please consider setting the `UpdatePromptFrequency.immediately` the rule in `RulesManager` `

here is my code :

let siren = Siren.shared
        /// Major, Minor, Patch, and Revision specific rules implementations.
        siren.rulesManager = RulesManager(majorUpdateRules: Rules(promptFrequency: .immediately, forAlertType: .force),
                                          minorUpdateRules: Rules(promptFrequency: .daily, forAlertType: .option),
                                          patchUpdateRules: Rules(promptFrequency: .daily, forAlertType: .option),
                                          revisionUpdateRules: Rules(promptFrequency: .daily, forAlertType: .option),
                                          showAlertAfterCurrentVersionHasBeenReleasedForDays: 0)
        
siren.presentationManager = PresentationManager(alertTintColor: nil, appName: "Demo app", alertTitle: AlertConstants.alertTitle, alertMessage: AlertConstants.alertMessage, updateButtonTitle: AlertConstants.updateButtonTitle, nextTimeButtonTitle: "Remind me later", skipButtonTitle: AlertConstants.skipButtonTitle, forceLanguageLocalization: nil)

@SentulAsia @joelparkerhenderson @bonkey @irlabs 
Can you please let me know what I 'm doing wrong here.

**Comment by ArtSabintsev** [comment]
Hi - I’ll look into this when I get to a computer 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Hello!

Please provide me with a sample project that I can open and test in Xcode 10.3. That will help me diagnose this issue.

**Comment by raza08** [comment]
Hello, 
Actually I'm running it on Xcode 11.5 beta version can you please check demo app  example of [Siren](https://github.com/ArtSabintsev/Siren/blob/master/Example/Example/AppDelegate.swift)

**Comment by ArtSabintsev** [comment]
I have a branch for that  - `siren5.1`.

Does the project not work for that?

**Comment by raza08** [comment]
I'm not sure sometimes it's showing alert sometimes not showing, it's weird behavior.

**Comment by ArtSabintsev** [comment]
Ok, since you closed the issue, I will assume it is resolved for now. I’ll take a serious look once the GM build is out.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
