### ISSUE TITLE
How to test even if app not on store?

### ISSUE THREAD

**Issue by JhonnyTawk** [ArtSabintsev/Siren#304]
I am unable to test the Siren, I don't have any version on store or iTunes connect, is there a way to test it?
I am using latest Siren Version.

**Comment by ArtSabintsev** [comment]
Use the bundle ID in the sample app that comes with Siren and build on a simulator. It should work at that point.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JhonnyTawk** [comment]
indeed that's what I did and it didn't work, I used the Bundle Id: "com.apple.AppStoreConnect" and I tried changing the Build and Version number and it didn't work on Simulator

**Comment by ArtSabintsev** [comment]
Can you provide me with a small sample app with your bundleID in the sample project? I’ll happily take a look

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Closing this question due to lack of follow up. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
