### ISSUE TITLE
'UIWindow' has no member 'windowScene'

### ISSUE THREAD

**Issue by zishanj** [ArtSabintsev/Siren#307]
This error appears after I updated to 5.2.1.

> /Pods/Siren/Sources/View Controllers/SirenViewController.swift:21:34: Value of type 'UIWindow' has no member 'windowScene'; did you mean 'windowLevel'?

**Comment by ergunkocak** [comment]
Same problem, i am using xcode 10.2.1

**Comment by zishanj** [comment]
This seems to be available **only** in **iOS 13.0 + Beta** as mentioned [here](https://developer.apple.com/documentation/uikit/uiwindow/3197962-windowscene)

**Comment by zishanj** [comment]
I think we have to update our XCode to 11 to support SDK iOS 13.0 compilation as mentioned on official site:

> Xcode 11 includes Swift 5.1 and SDKs for iOS 13, tvOS 13, watchOS 6, and macOS Catalina 10.15

**Comment by zishanj** [comment]
I don't prefer using beta versions and had to comment out that line to make it work.

**Comment by ArtSabintsev** [comment]
Hmm I thought I blocked all those code out for iOS13. I merged it in because the GM is out.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Ok, following up. I merged the iOS 13 changes into master because the Xcode 11 GM is out, which is effectively the final version of Xcode 11.0 (more often than not). The real official version should be out in 3 days, so until then, revert back to the previous stable version of Siren: `5.1.2`

**Comment by ArtSabintsev** [comment]
Closing this issue as it no longer valid - Xcode 11 is the latest version available in the App Store.
