### ISSUE TITLE
Force update stuck even after update to new version

### ISSUE THREAD

**Issue by maasim94** [ArtSabintsev/Siren#309]
i have checked issue 135, same issue is hepping with my app, i have added 1 day wait time already but app stuck on update pop up even after update to new version.

My app is available to US store.
Bundle id: com.diamond.Bham-Own
latest version: 1.2

it's just stuck!

**Comment by ArtSabintsev** [comment]
I think you mean #308 (which is a newer version of #105). Does the same problem appear in the sample app that is bundled with Siren?

Can you show me all the points where you're calling Siren?

**Comment by maasim94** [comment]
this is method

        func hyperCritical() {
        let siren = Siren.shared
        siren.rulesManager = RulesManager(globalRules: .critical,
                                          showAlertAfterCurrentVersionHasBeenReleasedForDays: 1)
        
        siren.wail { results in
            switch results {
            case .success(let updateResults):
                print("AlertAction ", updateResults.alertAction)
                print("Localization ", updateResults.localization)
                print("Model ", updateResults.model)
                print("UpdateType ", updateResults.updateType)
            case .failure(let error):
                print(error.localizedDescription)
            }
        }
    }

calling in *didFinishLaunchingWithOptions*
`window?.makeKeyAndVisible()`
        /// Siren should ONLY be placed in UIApplication.didFinishLaunchingWithOptions and only after the `window?.makeKeyAndVisible()` call.
        /// Siren initializes a listener on `didBecomeActiveNotification` to perform version checks.
        `hyperCritical()`

**Comment by maasim94** [comment]
![Skype_Picture_2019_10_01T18_40_05_661Z](https://user-images.githubusercontent.com/8789336/65990342-71fdcb80-e49c-11e9-80fd-c22e64ff2831.jpeg)
![Skype_Picture_2019_10_01T18_39_46_457Z](https://user-images.githubusercontent.com/8789336/65990348-74f8bc00-e49c-11e9-90c1-d0e4791aad51.jpeg)

**Comment by ArtSabintsev** [comment]
Wait, do you have a call in `didBecomeActiveNotification`? If so, remove that call. `NotificationCenter` takes care of that.

**Comment by maasim94** [comment]
No I haven't called, but this issue was with versioning. build version was different than AppStore version. Don't know how that happened.
