### ISSUE TITLE
sirenDidShowUpdateDialog Function Not Called

### ISSUE THREAD

**Issue by mikewalkerjr** [ArtSabintsev/Siren#31]
I have implemented the 'SirenDelegate' within my ViewController, and the dialog appears properly, however the 'sirenDidShowUpdateDialog' is not getting called. I have the following in my code:

    func sirenDidShowUpdateDialog() {
        print("did show dialog")
    }
    
    func sirenUserDidLaunchAppStore() {
        print("did launch app store")
    }
    
    func sirenUserDidCancel() {
        print("did cancel")
    }

The 'sirenUserDidLaunchAppStore' and 'sirenUserDidCancel' 'print' statements are called properly, but the 'sirenDidShowUpdateDialog' 'print' statement is not called when the dialog appears.

**Comment by ArtSabintsev** [comment]
Will look into this today - thanks for the note!

**Comment by ArtSabintsev** [comment]
Also, are you testing on iOS 7, iOS 8, or iOS 9, and what version of Siren are you using? 

Just want to make sure it's iOS 8+, and Siren 0.5.0.

**Comment by ArtSabintsev** [comment]
ya, OK I can confirm that code is missing outside of the declaration. I'll add it in during a break today.

**Comment by ArtSabintsev** [comment]
and probably should consider writing some tests.

**Comment by ArtSabintsev** [comment]
Fixed and pushed to cocoapods as 0.5.1.

Thanks for the bug report!

**Comment by mikewalkerjr** [comment]
Thank you. Works great!
