### ISSUE TITLE
use siren  5.2.1

### ISSUE THREAD

**Issue by danishnisar** [ArtSabintsev/Siren#312]
use siren  5.2.1

_Originally posted by @maasim94 in https://github.com/ArtSabintsev/Siren/issues/311#issuecomment-537536134_

I already used siren 5.2.1 but issue is remain same.

**Comment by ArtSabintsev** [comment]
Can you please provide me with sample code on how you implemented Siren? Does the problem exist in the Example app that is available with this library?

**Comment by ibeleliev** [comment]
I updated the library to the latest version now and i got too the disappearing update popup for some runs.
Now i have different issue i can tap on the buttons on the popup but when the alert hides my UI is blocked.

I use it like this: 
```
let siren = Siren.shared
siren.rulesManager = RulesManager(globalRules: .annoying, showAlertAfterCurrentVersionHasBeenReleasedForDays: 1)
siren.presentationManager = PresentationManager(alertTitle: "update.title".localized, alertMessage: "updateMessage.text".localized, updateButtonTitle: "updateButton.title".localized, nextTimeButtonTitle: "nextTimeButton.title".localized)
siren.wail(performCheck: .onDemand, completion: nil)
```

I tried to inspect it with the Debug Visual Hierarchy and i saw that in the app when i tapped on a button (eihter the update or the next time) there were 2 UIWindow's.
![Screenshot 2019-10-04 at 13 45 20](https://user-images.githubusercontent.com/21360208/66202621-e8721780-e6ae-11e9-93f7-be8127268dbd.png)
![Screenshot 2019-10-04 at 13 44 11](https://user-images.githubusercontent.com/21360208/66202646-f45dd980-e6ae-11e9-9b4a-44c53df17f48.png)

I don't know if the files help :)
The issue started when i started using Xcode 11  on the older sdk it was okay.

**Comment by ArtSabintsev** [comment]
Alright, I’ll take a look today. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Alright, I was _finally_ able to reproduce this issue. Attempting to see why the measures I put in place before aren't working.

**Comment by ArtSabintsev** [comment]
Funny enough, it happens one out of every 20 attempts in the sample app. It must be some type of threading issue.

**Comment by ArtSabintsev** [comment]
https://github.com/ArtSabintsev/Siren/releases/tag/5.2.2 this may address the issue.

Closing this issue for now.
