### ISSUE TITLE
Blocking UI when the alert is dismissed

### ISSUE THREAD

**Issue by ibeleliev** [ArtSabintsev/Siren#313]
I removed the predefined text because this behaviour can be seen in the Example app too.

Steps to reproduce:
1. Click on the `Example` project in the `Project Navigator`. In the `Targets` select `Example` if it is not selected. 
2. Under `General` tab, under `Deployment Info` change the `Main interface` option to `Main.storyboard` .
3. Open the `Main.storyboard` in the `Supporting Files` group/folder.
4. Put UISwitch in the scene and add constraints to it.
5. Run the application in simulator.
After the popup for update appears and the user taps on something, the user can't flip the switch. If you comment the line `annoyingRuleExample()` in the `application(_:didFinishLaunchingWithOptions:)`, and run the app again the user can flip the switch.

I tested it with the newest version (5.2.2) and this behaviour is happening to me in the simulator and on real device too.
I don't know if it has something to do with the UIWindow the alert creates because after dismissal the window for the alert is still there in the view hierarchy.

**Comment by Tripwire999** [comment]
I have the same issue on my device running iOS 13.1.2 looking into the code to see if I can fix it somewhere and make a PR

**Comment by ArtSabintsev** [comment]
Ah, the window scene is active? I’ve been biking the window. Can you point me to where you saw that?

I’m having a very difficult time replicating this issue, so it’s hard for me to put in a fix.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ibeleliev** [comment]
![Screenshot 2019-10-07 at 16 47 06](https://user-images.githubusercontent.com/21360208/66317480-40648480-e922-11e9-93df-8b3bb3c5c16f.png)

This is from the example app in the library after tapping button on the alert.

**Comment by ArtSabintsev** [comment]
Can one of you see if nuking/nilling-out the window scene in the cleanup() method fixes the issue? I’m a bit indisposed until later tonight / tomorrow to be able to check.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ibeleliev** [comment]
I can confirm that writing this
```
        if #available(iOS 13, *) {
            UIApplication.shared.keyWindow?.windowScene = nil
        }
```
in the end of the cleanup function fixes the issue in the example app. Since im really not sure if i should use UIApplication in the library code i'm not gonna do PR :)

**Comment by Tripwire999** [comment]
@ibeleliev Tested this on my app, didn't notice any issues here.

**Comment by ArtSabintsev** [comment]
Can you nil it on the custom window that Siren generates?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Would either of you mind trying this branch: https://github.com/ArtSabintsev/Siren/pull/314

**Comment by ibeleliev** [comment]
That way does not fix the issue :( the window is still there in the view hierarchy.
I tried to use print statements before and after setting the windowsScene to nil like this:
```
        if #available(iOS 13, *) {
            print("Before setting the windowScene to nil: \(updaterWindow.windowScene)")
            updaterWindow.windowScene = nil
            print("After setting the windowScene to nil: \(updaterWindow.windowScene)")
        }
```
and this is the result in the console:
```
Before setting the windowScene to nil: Optional(<UIWindowScene: 0x7fe384c07000; scene = <FBSSceneImpl: 0x600000369c80; identifier: sceneID:com.apple.AppStoreConnect-default>; persistentIdentifier = B57FC59F-8A8F-40F0-B33B-9A56A4927033; activationState = UISceneActivationStateForegroundActive; settingsCanvas = <UIWindowScene: 0x7fe384c07000>; windows = (
    "<UIWindow: 0x7fe384c09a30; frame = (0 0; 320 480); gestureRecognizers = <NSArray: 0x600002325ec0>; layer = <UIWindowLayer: 0x600002d66aa0>>",
    "<UITextEffectsWindow: 0x7fe384e14f20; frame = (0 0; 320 480); opaque = NO; autoresize = W+H; layer = <UIWindowLayer: 0x600002d301a0>>",
    "<UIWindow: 0x7fe384c31440; frame = (0 0; 320 480); hidden = YES; gestureRecognizers = <NSArray: 0x6000023109c0>; layer = <UIWindowLayer: 0x600002d35f40>>",
    "<UIWindow: 0x7fe384c334b0; frame = (0 0; 320 480); autoresize = W+H; gestureRecognizers = <NSArray: 0x600002311620>; layer = <UIWindowLayer: 0x600002d36580>>",
    "<UIWindow: 0x7fe384f10de0; frame = (0 0; 320 480); hidden = YES; gestureRecognizers = <NSArray: 0x600002319a70>; layer = <UIWindowLayer: 0x600002d017a0>>",
    "<UIWindow: 0x7fe384f0fc90; frame = (0 0; 320 480); hidden = YES; gestureRecognizers = <NSArray: 0x600002314060>; layer = <UIWindowLayer: 0x600002d01800>>",
    "<UIWindow: 0x7fe384c48e50; frame = (0 0; 320 480); hidden = YES; gestureRecognizers = <NSArray: 0x600002313690>; layer = <UIWindowLayer: 0x600002d06b60>>"
)>)
After setting the windowScene to nil: Optional(<UIWindowScene: 0x7fe384c07000; scene = <FBSSceneImpl: 0x600000369c80; identifier: sceneID:com.apple.AppStoreConnect-default>; persistentIdentifier = B57FC59F-8A8F-40F0-B33B-9A56A4927033; activationState = UISceneActivationStateForegroundActive; settingsCanvas = <UIWindowScene: 0x7fe384c07000>; windows = (
    "<UIWindow: 0x7fe384c09a30; frame = (0 0; 320 480); gestureRecognizers = <NSArray: 0x600002325ec0>; layer = <UIWindowLayer: 0x600002d66aa0>>",
    "<UITextEffectsWindow: 0x7fe384e14f20; frame = (0 0; 320 480); opaque = NO; autoresize = W+H; layer = <UIWindowLayer: 0x600002d301a0>>",
    "<UIWindow: 0x7fe384c31440; frame = (0 0; 320 480); hidden = YES; gestureRecognizers = <NSArray: 0x6000023109c0>; layer = <UIWindowLayer: 0x600002d35f40>>",
    "<UIWindow: 0x7fe384c334b0; frame = (0 0; 320 480); autoresize = W+H; gestureRecognizers = <NSArray: 0x600002311620>; layer = <UIWindowLayer: 0x600002d36580>>",
    "<UIWindow: 0x7fe384f10de0; frame = (0 0; 320 480); hidden = YES; gestureRecognizers = <NSArray: 0x600002319a70>; layer = <UIWindowLayer: 0x600002d017a0>>",
    "<UIWindow: 0x7fe384f0fc90; frame = (0 0; 320 480); hidden = YES; gestureRecognizers = <NSArray: 0x600002314060>; layer = <UIWindowLayer: 0x600002d01800>>",
    "<UIWindow: 0x7fe384c48e50; frame = (0 0; 320 480); hidden = YES; gestureRecognizers = <NSArray: 0x600002313690>; layer = <UIWindowLayer: 0x600002d06b60>>",
    "<UIWindow: 0x7fe384e2c2b0; frame = (0 0; 320 480); hidden = YES; gestureRecognizers = <NSArray: 0x60000231bcc0>; layer = <UIWindowLayer: 0x600002d3cae0>>"
)>)
```
i will try to see more whats going on later. ill write here again if i find something else.

**Comment by Tripwire999** [comment]
@ibeleliev & @ArtSabintsev I've been testing a bit with setting the:
UIApplication.shared.keyWindow?.windowScene = nil

But that definitely brakes something in my app and is NOT a solution unfortunately :(

**Comment by Tripwire999** [comment]
Ok I think the code below might fix it:
`
if #available(iOS 13.0, *) {
          if let windowScene = self.updaterWindow.windowScene {
            for window in windowScene.windows where window.rootViewController != nil && window.rootViewController! is SirenViewController {
              window.rootViewController = nil
              window.resignKey()
              window.removeFromSuperview()
            }
          }
          self.updaterWindow.windowScene = nil
        }
`

**Comment by ibeleliev** [comment]
Yeah something like that could work. 
I did a little bit testing around the code in the cleanup function and i think
each time code that contains `updaterWindow` is called
it creates different window and each statement/function after the "`.`" is executed for different window instance.

**Comment by ArtSabintsev** [comment]
Ok let’s continue the conversation in the PR thread.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
And thank you :) I’ll do some testing today as well 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
I’ll also work on making sure that only wants this created at all times

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
