### ISSUE TITLE
App Crashing iOS 13.1.3

### ISSUE THREAD

**Issue by developer-macrew** [ArtSabintsev/Siren#315]
I have update the library to 5.2.3, And its now crashing in AppDelegate in this line:
Siren.shared.wail()

**Comment by ArtSabintsev** [comment]
Please provide me with more code in your AppDelegate.

Also, is it crashing in the example project?

**Comment by developer-macrew** [comment]
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        window?.makeKeyAndVisible()
               Siren.shared.wail()
               Siren.shared.rulesManager = .init(globalRules: .annoying, showAlertAfterCurrentVersionHasBeenReleasedForDays: 0)
        return true
    }

**Comment by ArtSabintsev** [comment]
As you closed this issue, I'm assuming you figured it out.
