### ISSUE TITLE
Critical update prompt disappearing after time

### ISSUE THREAD

**Issue by delucamike** [ArtSabintsev/Siren#317]
I released an updated version of my app and the update prompt comes up just fine. If I close the app using the home button and return to the app, it comes up fine. However, my issue lies in that if I then come back to the app like 1-2 hours later, the prompt does not appear, allowing you to use the app. It seems like there is some kind of timeout while the app is in the background.

- Swift 5.0
- Siren 5.2.3
- iOS 13.2.3
- iPhone 7 physical device

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    window?.makeKeyAndVisible()
        
    ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
    
    let siren = Siren.shared
    siren.rulesManager = RulesManager(globalRules: .critical, showAlertAfterCurrentVersionHasBeenReleasedForDays: 0)
    siren.wail()

    return true
}
```

**Comment by ArtSabintsev** [comment]
Ah, this is probably part of all of those iOS 13 state management issues. 

In your scenario, just move your code to `didBecomeActive`. Since you're using critical, you want to appear every time anyway. 

Does that help?

**Comment by delucamike** [comment]
Ok thanks, yeah that should be fine.
