### ISSUE TITLE
NSInternalInconsistencyException after pressing Next in Siren popup (iOS 13 only)

### ISSUE THREAD

**Issue by Tripwire999** [ArtSabintsev/Siren#318]
Hi 

So i'm using Siren v5.2.3 and did my first update of our app with Siren installed so the users get a popup asking them to update. I've setup Siren as follows:
```
let siren = Siren.shared
let rules = Rules(promptFrequency: .immediately, forAlertType: .option)
siren.rulesManager = RulesManager(globalRules: rules)
siren.wail()
```

After the popup is shown and the user doesn't want to update right away and taps on next the app randomly crashes somewhere due to the following error message:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'

When the popup isn't shown I never get the NSInternalInconsistencyException and can use the app as normal. I'm debugging this now so I will let you know when I find something.

**Comment by ArtSabintsev** [comment]
Hi - thanks for the message. I don't recall doing any UI presentation on the background thread, but that will be a simple fix if it is indeed Siren causing the issue. Please let me know.

**Comment by Tripwire999** [comment]
@ArtSabintsev Here's the stacktrace of what happens:

[Stacktrace.txt](https://github.com/ArtSabintsev/Siren/files/3921109/Stacktrace.txt)

I can't really make sense of what happens and why it happens. But it seems to always happen when a user presses next in the Siren popup. I have the Main Thread Checker on and some other code to check if UIViews are used on the Main thread but everything seems to be fine no issues there.

**Comment by ArtSabintsev** [comment]
Is it a Siren popup, or any `UIAlertController`?

**Comment by ArtSabintsev** [comment]
The stack trace makes no reference to anything remotely related to Siren, so maybe something else is happening at the same time in the background when Siren is being presented?

**Comment by Tripwire999** [comment]
@ArtSabintsev well it only happens when the Siren popup comes in, it might have something to do with Google Maps running though. I've now made my own popup and version check method which seems to work fine without crashes. Anyways I can easily reproduce it with Siren and can't reproduce it with my own popup, very strange...

**Comment by ArtSabintsev** [comment]
Would you be able to provide me with a small sample project? I have not been able to reproduce this is the same project nor in a personal application of mine.

**Comment by Tripwire999** [comment]
@ArtSabintsev I've been trying to reproduce it in a sample app but I can't. So I guess it might be a combination of me using Google Maps or some other libraries. If I have time I'll see if I can research some more. For now i've created my own implementation which shows a popup on the UIWindow, it's not crashing anymore now.

**Comment by ArtSabintsev** [comment]
ok, thanks for following up! Closing this issue. Feel free to open a new one if the problem returns and is reproducible.
