### ISSUE TITLE
Check version of the app from custom API

### ISSUE THREAD

**Issue by ayachama** [ArtSabintsev/Siren#319]
## If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: 
Yes
- **What is your app's Bundle ID?**: 
com.ancestry.ancestrydna
- **When was the latest version of your app published to the App Store?**: 
4.22
- **Is your app published in the US App Store? If not, what App Store is it published in?**:
Yes
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**:
Yes
---
I know that this isn't forum for asking this question. Can we use siren to check minimum app version from an API that's been maintained by our organization? There are no methods that currently support this in the documentation.

**Comment by ArtSabintsev** [comment]
Hi @ayachama,

No, this is not possible. The only information that is available is what ever comes from the iTunesLookup API JSON Payload.

Thanks for the message!
