### ISSUE TITLE
Crash when no internet

### ISSUE THREAD

**Issue by zmian** [ArtSabintsev/Siren#32]
Siren crashes the app when no internet/service.

HockeyApp Log:

`MyApp.Siren.((performVersionCheck in _5FA0E00E9C2A892EB4899D0EF44B562B) (MyApp.Siren) -> () -> ()).(closure #1) (Siren.swift:273)`

`partial apply forwarder for reabstraction thunk helper from @callee_owned (@in (Swift.ImplicitlyUnwrappedOptional<ObjectiveC.NSData>, Swift.ImplicitlyUnwrappedOptional<ObjectiveC.NSURLResponse>, Swift.ImplicitlyUnwrappedOptional<ObjectiveC.NSError>)) -> (@out ()) to @callee_owned (@owned Swift.ImplicitlyUnwrappedOptional<ObjectiveC.NSData>, @owned Swift.ImplicitlyUnwrappedOptional<ObjectiveC.NSURLResponse>, @owned Swift.ImplicitlyUnwrappedOptional<ObjectiveC.NSError>) -> (@unowned ()) with unmangled suffix "25" (Siren.swift:0)`

**Comment by ArtSabintsev** [comment]
Thanks! Will look into this over lunch.

**Comment by ArtSabintsev** [comment]
Can't reproduce it.

I get the following result when I try running without being connected to the internet:

```
[Siren] Error retrieving App Store data as an error was returned: The Internet connection appears to be offline.
```

Are you running the latest version?

**Comment by getaaron** [comment]
@zmian Are you calling Siren from Objective-C code? Can you show the code that's causing the crash?

**Comment by zmian** [comment]
@getaaron I'm using Swift. 

@ArtSabintsev pls see below

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        Siren.sharedInstance.appID = "app_id_here"
        Siren.sharedInstance.alertType = .Force
        Siren.sharedInstance.checkVersion(.Immediately)
        return true
    }

    func applicationWillEnterForeground(application: UIApplication) {
        // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
        Siren.sharedInstance.checkVersion(.Immediately)
    }

    func applicationDidBecomeActive(application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
        Siren.sharedInstance.checkVersion(.Daily)
    }

**Comment by ArtSabintsev** [comment]
Still can't replicate it for some reason, even with those settings.

**Comment by ArtSabintsev** [comment]
@zmian Can you provide us with a small sample project?

Please use:
- Siren 0.6.0
- Xcode 7.0.1

Upload it to Github and shoot a link in here.

**Comment by zmian** [comment]
Strange stuff. I tried it on another project and it worked fine. I'm assuming something something else is the root cause for this. I'm closing this issue until I have further info to report. Thank you for prompt responses.

**Comment by ArtSabintsev** [comment]
Got it! Thanks for looking into it deeper.

Good luck solving the problem!
