### ISSUE TITLE
Does Update popup appear if an app is a 24*7 running app?

### ISSUE THREAD

**Issue by Happily-Hemu** [ArtSabintsev/Siren#320]
Hi, best library till yet which i have come across. It's not an issue but more of a question. Just want to know that - 
Will the version update popup will appear on a 24*7 running app ??

**Comment by ArtSabintsev** [comment]
Hi, thanks for the message. If by running, do you mean in the abckground or foreground?

- If background/hibernated-state, then yes. When the user opens it from a hibernated state, then it will pop up if enough time has passed.
- If foreground, then no. The app is triggered off of a didBecomeActive notification. 

I hope that helps!
