### ISSUE TITLE
iOS 13 Alert Disappears & makes the screen black

### ISSUE THREAD

**Issue by Rcicen** [ArtSabintsev/Siren#321]
- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: 
Yes
Hi, I have configured the latest version 5.2.3. 

I configured it as a force update. When i'm testing it , after the  first or second launch the alert vanishes but i can interact with the app. However when if i go to the background the app screen becomes black and app cannot be used after that point. 
I have read the closed cases about this but i think the issue is still exists

`Siren.shared.apiManager = APIManager(countryCode: "tr")
        Siren.shared.rulesManager = RulesManager(
majorUpdateRules: Rules(promptFrequency: .daily, forAlertType: .option),
minorUpdateRules: Rules(promptFrequency: .immediately, forAlertType: .force),
patchUpdateRules: Rules(promptFrequency: .daily, forAlertType: .skip),
revisionUpdateRules: Rules(promptFrequency: .weekly, forAlertType: .none),
showAlertAfterCurrentVersionHasBeenReleasedForDays: 5 )

Siren.shared.wail(performCheck: .onDemand, completion: nil)`

**Comment by ArtSabintsev** [comment]
Hi,

Thanks for the report. A few things:

1. Can you reformat your sample code? It's difficult to read.
2. Can you configure the sample app that's part of this repo to work with your `bundleID` and the same setup/configuration you have? Does the problem persist?

**Comment by ArtSabintsev** [comment]
Closing due to lack of follow up.
