### ISSUE TITLE
alert appears but immediately disappears swift 4.2

### ISSUE THREAD

**Issue by tiskender2** [ArtSabintsev/Siren#323]
## If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**:  yes, also tried for swift 4.2
- **What is your app's Bundle ID?**:  
- **When was the latest version of your app published to the App Store?**:  January 2020
- **Is your app published in the US App Store? If not, what App Store is it published in?**: yes
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**: yes

---

**Comment by ArtSabintsev** [comment]
Hi,

Need a lot more info. Also, Swift 5.1 is the currently supported version.

**Comment by tiskender2** [comment]
i am using swift 4.2 . i have used  branch "swift 4.2" and  your code in the example file so  alert appear and dissappear

**Comment by mmdock** [comment]
@tiskender2  you can use the Siren Swift 5.1 version in your swift 4.2 project by configuring that specific pod to compile with a different swift version, so long as you are on an Xcode version that supports both swift 4.2 and swift 5.1.

There are a number of solutions / methods on how to do this.

**Comment by ArtSabintsev** [comment]
Thanks @mmdock. Closing as his answer is the correct one. 

I am no longer maintaining the 4.2 branch - it's there for posterity.
