### ISSUE TITLE
Results fetched, but alert doesn't show when using SceneDelegate instead of AppDelegate

### ISSUE THREAD

**Issue by elrond140** [ArtSabintsev/Siren#324]
## If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: Yes  
- **What is your app's Bundle ID?**: Testing with com.apple.AppStoreConnect
- **When was the latest version of your app published to the App Store?**: 1.4
- **Is your app published in the US App Store? If not, what App Store is it published in?**: Yes
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**: Yes (same)

---

Using Xcode 11.3.1, Swift 5, and testing on iOS 13.3. Tested on both simulator and physical device. Using the Siren Swift 5.1 master branch.
**Note: I am using the bundle identifier com.apple.AppStoreConnect to do testing as I do not have any active apps on the store.** 

Using the **SirenCustomAlertRules()** function from the Siren example project and setting the rules as:
`Rules(promptFrequency: .immediately, forAlertType: .none)`
 and using a brand new SceneDelegate project template, the results from the query are shown in the console, but no alert is actually presented to the user in the app. 

[See my Github repository for this project. ](https://github.com/elrond140/SirenSceneTest)

**Comment by elrond140** [comment]
Console Output: 

```
SirenCustomAlertRules() Called
Siren.Wail results: 
AlertAction  unknown
Localization  Localization(appName: "SirenSceneTest", forceLanguage: nil)
Model  Model(appID: 1234793120, currentVersionReleaseDate: "2019-10-03T21:19:13Z", minimumOSVersion: "12.0", releaseNotes: Optional("- Support for Dark Mode, ideal for low-light environments. Requires iOS 13.\n- Stability improvements and bug fixes."), version: "1.4")
UpdateType  minor
```

**Comment by ArtSabintsev** [comment]
Please change `.none` to another option, as `.none` purposefully suppresses the alert for people who want to build custom alerts.

**Comment by elrond140** [comment]
I changed it to each of the other options and it still doesn't present an alert. Also, I've tried using the other example functions that were included in the Example project, such as defaultExample() and defaultExampleUsingCompletionHandler() with the same results.

**Comment by elrond140** [comment]
[kisaha00's Pull Request](https://github.com/ArtSabintsev/Siren/pull/325/files#diff-0e638f0130e31cb2fab44524b4fcf928) seems to address this issue successfully for my configuration. I recommend finding a way to implement it into the base code for others. Not sure how it should be structured though if someone continues to utilize AppDelegate for presenting windows in iOS 13 instead of SceneDelegate.
