### ISSUE TITLE
always show old version number

### ISSUE THREAD

**Issue by yadanarOway** [ArtSabintsev/Siren#328]
Hi,

I also got above error in Siren.  recently I released version 7.0.4 to my app but it still shows 

> A new version of __ is available. Please update to version 7.0.3 now.

. I checked my version app store and my code. They are already same. I also check my version by this link "http://itunes.apple.com/lookup?bundleId= " ,it shows correct version no. Can you try it for me please? I am in a hurry.

Thank you.

**Comment by ArtSabintsev** [comment]
Can you provide me with your bundleID and the correct country code localization if it's not available in the US App Store?

**Comment by WiiLin** [comment]
@ArtSabintsev I encountered similar problems `Siren (5.4.0)`
I released version `3.4.0`, but APIModel got the previous version number `3.3.1`
I'm sure the `http://itunes.apple.com/lookup?bundleId=` version is `3.4.0`
<img width="694" alt="截圖 2020-02-21 下午3 17 22" src="https://user-images.githubusercontent.com/10156607/75016599-4ec4ce80-54c6-11ea-8d3b-e81268fd2eec.png">

**Comment by ArtSabintsev** [comment]
Hi, I cannot check either of your problems with 5.4.0 unless you provide me with your bundleID and the countryCode for the App Store your app is released in if it's not available in the US App Store.

**Comment by yadanarOway** [comment]
> Can you provide me with your bundleID and the correct country code localization if it's not available in the US App Store?
Thank for your interest ArtSabintsev,   I check my version by this link "http://itunes.apple.com/lookup?bundleId= " , it shows version 7.0.4. but it still work with 7.0.3 in my app. After 10 hours, It automatically solves above case and I get correct version update box. 
I think it does not work force updating immediately on app after released. It takes about 10 hours interval to work properly.

**Comment by ArtSabintsev** [comment]
Right, that’s what the instructions say at the bottom. It usually takes about 24 hours for Apple to update the JSON.

Closing this issue as it seems to be solved.
