### ISSUE TITLE
Public API to close alert and version check?

### ISSUE THREAD

**Issue by allaire** [ArtSabintsev/Siren#33]
Hi,

Would it be possible to have a public API to be able to close the alert with a method?

Also, we rolled our own forced update alert with our API. I would love to be able to use the same method you use to check if the current app version is older than X version. Would it makes sense to open it up as well?

**Comment by ArtSabintsev** [comment]
It's already open :) - check the new delegate method I added in the latest release.

Set the alert type to 'None' and one of the delegates will pass back a message. 

On mobile, so can't tell you which one off top of my head.

Keep me posted.

**Comment by ArtSabintsev** [comment]
This will allow you to roll your own alert with a localized method.

**Comment by ArtSabintsev** [comment]
Use this delegate method: https://github.com/ArtSabintsev/Siren/blob/master/Siren/Siren.swift#L17

It's called when you set the `alertType` to `.None`

```swift
let siren = Siren.sharedInstance
siren.alertType = .None
```
