### ISSUE TITLE
alert appears but immediately disappears swift 5.0

### ISSUE THREAD

**Issue by horsebuzz** [ArtSabintsev/Siren#330]
As the title suggest the alert appears for a moment but disappears instantly and opens a WkWebview.

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: Swift 5.0 version
- **What is your app's Bundle ID?**: 
- **When was the latest version of your app published to the App Store?**: 1 week ago
- **Is your app published in the US App Store? If not, what App Store is it published in?**: Yes

I am using the `hyperCriticalRulesExample` from the example folder as is. Have not changed a thing.

Thank you

**Comment by ArtSabintsev** [comment]
Hi,

When you say _Swift 5.0 version_, is that the version on the master branch or on the` swift5.0` branch?

Thanks!

**Comment by kamrankhan07** [comment]
Its because of `cleanup` method call in `presentAlert` method in `PresentationManager.swift`. This fixed it for me 

```
// This is a safety precaution to avoid multiple windows from presenting on top of each other.
        cleanUp()
        
        // If the alertType is .none, an alert will not be presented.
        // If the `updaterWindow` is not hidden, then an alert is already presented.
        // The latter prevents `UIAlertController`'s from appearing on top of each other.
        if rules.alertType != .none, updaterWindow.isHidden {
            alertController?.show(window: updaterWindow)
        } 
```

In my code, the Siren api was called twice due to login in my code and it was showing alert and hiding it. Regardless, I think the above code change will be better to discard all such cases. We can even remove `updaterWindow.isHidden` check as cleanup() call will make sure that it is.

**Comment by horsebuzz** [comment]
I have typed in following in my pod file and just installed yesterday.

    pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift5.0' # Swift 5.0

**Comment by horsebuzz** [comment]
> Its because of `cleanup` method call in `presentAlert` method in `PresentationManager.swift`. This fixed it for me
> 
> ```
> // This is a safety precaution to avoid multiple windows from presenting on top of each other.
>         cleanUp()
>         
>         // If the alertType is .none, an alert will not be presented.
>         // If the `updaterWindow` is not hidden, then an alert is already presented.
>         // The latter prevents `UIAlertController`'s from appearing on top of each other.
>         if rules.alertType != .none, updaterWindow.isHidden {
>             alertController?.show(window: updaterWindow)
>         } 
> ```
> 
> In my code, the Siren api was called twice due to login in my code and it was showing alert and hiding it. Regardless, I think the above code change will be better to discard all such cases. We can even remove `updaterWindow.isHidden` check as cleanup() call will make sure that it is.

In which function or method should I insert this code? I am a web developer so not familiar with `swift` yet. Still following the tutorials only.

**Comment by kamrankhan-chilindo** [comment]
I think @ArtSabintsev  can review if this is the best approach, then have to make changes in the repository itself. I just found out this issue, this morning while debugging the same issue as you, so for now I directly changed it in pods file. You might not need to do that, may be wait for an update from @ArtSabintsev if he thinks its something to change because I didn't look at all the changes in this repository recently.

**Comment by horsebuzz** [comment]
> I think @ArtSabintsev can review if this is the best approach, then have to make changes in the repository itself. I just found out this issue, this morning while debugging the same issue as you, so for now I directly changed it in pods file. You might not need to do that, may be wait for an update from @ArtSabintsev if he thinks its something to change because I didn't look at all the changes in this repository recently.

Thank you very much.
I will wait for a fix.

**Comment by ArtSabintsev** [comment]
Hey all,

Per the README, the swift5.0 branch is not supported. Only he `master` branch is supported. Does that help?

**Comment by horsebuzz** [comment]
In my `Xcode` project build settings, I only have option for `Swift 5`, no options for higher version.

Can I still use the `5.1` branch or will that cause problem ?

Thank you

**Comment by ArtSabintsev** [comment]
Should be fine! Try it out and keep me posted.

**Comment by horsebuzz** [comment]
Ok, Yes that solved the problem. Sorry for the trouble.

**Comment by ArtSabintsev** [comment]
no problem
