### ISSUE TITLE
App Store data as the JSON results were empty. Is your app available in the US?

### ISSUE THREAD

**Issue by manojkraftly** [ArtSabintsev/Siren#332]
Getting this issues when integrated this library

**Comment by ArtSabintsev** [comment]
Hey,

Per the title: 

- Is your app available in the US? 
- If not, can you set the `countryCode` on `APIManager`?

Also. when was your app released? 

Can you provide me with your bundleID?

**Comment by ArtSabintsev** [comment]
Closing due to lack of follow up. Feel free to open another issue of this problem persists.

Thanks.
