### ISSUE TITLE
Siren Error: No new update available

### ISSUE THREAD

**Issue by tunglong008** [ArtSabintsev/Siren#333]
I am using the latest version of siren for my ios application. I have been using this library ever since the first version release of my app without any issue. This is the first time Siren not able to detect new update of the app when a new version is released on app store. My app is distributed worldwide as well as US app store. Any idea about the cause of this issue?

**Comment by ArtSabintsev** [comment]
Hi,

Please provide me with your bundleID and the date of release. Was it released at least 24-72 hours ago?

Thanks!

**Comment by tunglong008** [comment]
Bundle id is com.coralsec.chumslive. It was released less than 24 hours.

**Comment by ArtSabintsev** [comment]
That's why. It takes about 24-48 hours for a release to propagate through the App Store CDNs.

Feel free to reopen this issue if this persists in another 24 hours.

**Comment by tunglong008** [comment]
The app does prompt the update dialog now. However, sometimes when I close the app and reopen, it still shows no new update available.

**Comment by ArtSabintsev** [comment]
Honestly, without seeing your implementation and playing with your specific app, I have no way of testing it. 

If your bundleID works in the sample app shipped inside this repository with high-fidelity, then I can't do anything else.

**Comment by tunglong008** [comment]
I have tried with the sample app and it shows the same result. I am using the hyperCriticalRulesExample function with additional configuration, which is setting 0 as showAlertAfterCurrentVersionBeenReleasedForDays.

**Comment by ArtSabintsev** [comment]
I'd wait 24 hours. This is in Apple's hands. This library is a wrapper around one API that can be flaky.

**Comment by tunglong008** [comment]
After setting the country code for ApiManager to asia region, it is working now. I want to ask is it safe to set showAlertAfterCurrentVersionBeenReleasedForDays to 0?

**Comment by ArtSabintsev** [comment]
usually, no, it's not, espcially if you use a critical setting. Otherwise, it's fine.

**Comment by tunglong008** [comment]
Does this mean that for app that require immediate update, it is better to set the version number on backend and call the API to check for availability of new version instead of using Siren?

**Comment by ArtSabintsev** [comment]
In your specific case, it might be. I believe the critical use case should be used very sparingly, so you can utilize both solutions depending on your business needs.

**Comment by KeeYan0304** [comment]
Thank you for providing such amazing library. I will be using another solution for this project due to the business requirement.

**Comment by cHaLkdusT** [comment]
Hi all, our team also encountered this issue during one of our production release. We record that iTunes Lookup API returns an outdated details, this is within the time frame 24~48hrs after releasing it to the App Store. However, an interesting scenario is that if we set the country code, it will actually return the correct and latest details (this regardless if it is less than or more than 24hrs). Hope this helps.
