### ISSUE TITLE
Siren not working with Push Notification requestAuthorization popup, it's displaying blank screen

### ISSUE THREAD

**Issue by dharmeshpatoliya** [ArtSabintsev/Siren#338]
## If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: Yes
- **What is your app's Bundle ID?**: Used your example app (com.apple.AppStoreConnect)
- **When was the latest version of your app published to the App Store?**: 
- **Is your app published in the US App Store? If not, what App Store is it published in?**:
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**: It works if I remove push notification request authorization code

`func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        
        window?.makeKeyAndVisible()
        
        UNUserNotificationCenter.current().requestAuthorization(options:[.badge, .alert, .sound]){ (granted, error) in }
               application.registerForRemoteNotifications()
        
        self.ConfigureSiren()
}`

`private extension AppDelegate {

    func ConfigureSiren() {
        let siren = Siren.shared
        siren.rulesManager = RulesManager(globalRules: .critical,
                                          showAlertAfterCurrentVersionHasBeenReleasedForDays: 0)
        
        siren.wail { results in
            switch results {
            case .success(let updateResults):
                print("AlertAction ", updateResults.alertAction)
                print("Localization ", updateResults.localization)
                print("Model ", updateResults.model)
                print("UpdateType ", updateResults.updateType)
            case .failure(let error):
                print(error.localizedDescription)
            }
        }
    }
}`

Please check the video:  https://www.dropbox.com/s/kh5nznavrcul4df/saved%20video.mov?dl=0

**Comment by ArtSabintsev** [comment]
I would say, hold off on using Siren until a user has given a response to Push Notifications. Check to see if a response has bene given as a condition around Siren. See if that helps.

**Comment by dharmeshpatoliya** [comment]
Thanks, do you have any sample code for that? Because I want to implement siren without issue.

**Comment by ArtSabintsev** [comment]
Hi,

Here is how you do a check to see if a user has been opted into Push already: https://dev.to/onmyway133/how-to-check-if-push-notification-is-actually-enabled-in-ios-20o8

I'd wrap that stuff around Siren. So if a user a has already given a yes/no response, on subsequent app launches, you can check to see that they have, and then do the Siren check.
