### ISSUE TITLE
Multiple checkVersion in app?

### ISSUE THREAD

**Issue by allaire** [ArtSabintsev/Siren#34]
Is it fine to have `siren.checkVersion(.Immediately)` in `didFinishLaunchingWithOptions` and `Siren.sharedInstance.checkVersion(.Daily)` in `applicationDidBecomeActive`? I saw in the obj-c project you advice to just use one, but I think it's useful to do a immediate check when the app launch for the first time as well as daily.

**Comment by ArtSabintsev** [comment]
The daily check should do an immediate check the first time around, I think.

Need to check the code, but will do it back when I'm at a computer.

**Comment by ArtSabintsev** [comment]
This guarantees that a version check is performed only once: https://github.com/ArtSabintsev/Siren/blob/master/Siren/Siren.swift#L256-L263.

Even if you have .Daily set, it will do an immediate check if a check has never been performed.
