### ISSUE TITLE
Error parsing App Store JSON data. No value associated with key CodingKeys(stringValue: "results", intValue: nil) ("results").

### ISSUE THREAD

**Issue by asn111** [ArtSabintsev/Siren#340]
- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: 
Yes.
- **What is your app's Bundle ID?**: 
Com.Greyscale.School-App
- **When was the latest version of your app published to the App Store?**: 
24 june 2020.
- **Is your app published in the US App Store? If not, what App Store is it published in?**: 
published in App Store globally.  
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**:
Can't test this. Couldn't find where to add these.
---

**Applying this code** 
 in my App delegate in _didFinishLaunchingWithOptions_ function

```
func initForceUpdate() {
            let siren = Siren.shared
            siren.apiManager = APIManager(countryCode: "\(Locale.current.languageCode ?? "")") // that is "en"

             siren.presentationManager = PresentationManager(alertTitle: "UPDATE",
                                                        nextTimeButtonTitle: "NEXT_TIME")
                let rules = Rules(promptFrequency: .immediately, forAlertType: .force)
               siren.rulesManager = RulesManager(globalRules: rules, showAlertAfterCurrentVersionHasBeenReleasedForDays: 1)
                siren.rulesManager = RulesManager(globalRules: .critical)
        siren.wail { results in
            switch results {
            case .success(let updateResults):
                print("AlertAction ", updateResults.alertAction)
                print("Localization ", updateResults.localization)
                print("Model ", updateResults.model)
                print("UpdateType ", updateResults.updateType)
            case .failure(let error):
                print(error.localizedDescription)
            }
        }
    }
```

**And getting this error**

**[Siren Error] Error parsing App Store JSON data.**
_Also, the following system level error was returned: keyNotFound(CodingKeys(stringValue: "results", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: "results", intValue: nil) ("results").", underlyingError: nil))_

what I am doing wrong. Any help would be appreciated. Thanks

**Comment by ArtSabintsev** [comment]
Hey,

Please don't do this `siren.apiManager = APIManager(countryCode: "\(Locale.current.languageCode ?? "")")`. There's no need. If your app is available in the US, then you're good to go without this line. If it's not available in the US, just choose one app store it's available in, and do that.

I see it working on my end in the Example app. See screenshot. I used `IL` as the countryCode (as an example).

<img width="2560" alt="Screen Shot 2020-06-26 at 9 16 42 AM" src="https://user-images.githubusercontent.com/854860/85861140-d9c41700-b78d-11ea-99ba-91ba430dc544.png">

**Comment by asn111** [comment]
Hi, Thanks for reply, 
if I don't use this `siren.apiManager = APIManager(countryCode: "\(Locale.current.languageCode ?? "")")` it gave me **"[Siren Error] No new update available."** even I have changed my version to 1.0.0(6) and uploaded version is 1.0.0(7)
can you confirm please, does build number change also count as new update for Siren?
In here (6 or 7) is Build number.

**Comment by ArtSabintsev** [comment]
Hi - Please just use one countryCode, and not that string interpolated code that checks Locale - there’s issues with that for whatever reason. 

I have an example highlighted on the left side of the screenshot.

**Comment by ArtSabintsev** [comment]
and I am using your BundleID (see the top-right of your screenshot). Build number is not important.

**Comment by asn111** [comment]
I have used same function as you did. 
and again got this error... 

_[Siren Error] Error parsing App Store JSON data.
Also, the following system level error was returned: keyNotFound(CodingKeys(stringValue: "results", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"results\", intValue: nil) (\"results\").", underlyingError: nil))_

same with the _customMessagingPresentationExample_ and _defaultExampleUsingCompletionHandler_ functions. 

I didn't get what do you meant with this statement. 
**Please just use one countryCode, and not that string interpolated code that checks Locale**
and what is the reason my app is saying **No new update available.**

**Comment by ArtSabintsev** [comment]
Try copy-pasting this code which I have confirmed to work in my example app. If it works there, then the problem is 100% in your code, and I cannot help beyond that.

    /// An example on how to change the App Store region that your app in which your app is available.
    /// This should only be used if your app is not available in the US App Store.
    /// This example function illustrates how this can be done by checking against the Russian App Store

```swift
 let siren = Siren.shared
        siren.apiManager = APIManager(countryCode: "RU") //replace "RU" with one hardcoded value. 

        siren.wail { results in
            switch results {
            case .success(let updateResults):
                print("AlertAction ", updateResults.alertAction)
                print("Localization ", updateResults.localization)
                print("Model ", updateResults.model)
                print("UpdateType ", updateResults.updateType)
            case .failure(let error):
                print(error.localizedDescription)
            }
        }
```

I also made sure my `bundleID` was yours and that the version of the app in the project was _lower_ than that of the one in the app store to trigger the alert.

**Comment by asn111** [comment]
My uploaded version on Appstore is 1.0.0 and I set mine version down to 0.0.1 to test.
when I added the snippet you shared above, it shows me this error.
**[Siren Error] No new update available.**

would it be something that is wrong from my end ?.

**Comment by ArtSabintsev** [comment]
Did you se the verison or the build number? And is it in the App Store live for more than 48 hours or so?

**Comment by asn111** [comment]
yes I did set it down to 0.0.1 and build number to 0 for the sake of testing. And app have been uploaded on 24th of june.

**Comment by ArtSabintsev** [comment]
Which countries is your app live in? Which country code are you using to check? Give me a list of 3 or 4. Because when I used "IL" it worked in the sample app.

**Comment by asn111** [comment]
I have used "RU" and "IL" and "GB" and "PK" all gave **No new update available.** And if I use "EN" it gives me this error. 
the same error again. 
_[Siren Error] Error parsing App Store JSON data.
Also, the following system level error was returned: keyNotFound(CodingKeys(stringValue: "results", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"results\", intValue: nil) (\"results\").", underlyingError: nil))_

**Comment by ArtSabintsev** [comment]
Honestly, not sure what to tell you. It works in the example app. I just did it again.

- See the bundleID and version on the top left
- See the code on the right
- See the simulator for the update alert

Are you sure you're using the latest version of the library and the latest version of Xcode? That's all I can guarantee to support.

<img width="2560" alt="Screen Shot 2020-06-26 at 4 15 16 PM" src="https://user-images.githubusercontent.com/854860/85897410-40662680-b7c8-11ea-8188-27e8ffb08560.png">

**Comment by asn111** [comment]
Yes I am, let me try it on a sample project and then will se what it does, thanks alot for this much support . :)

**Comment by ArtSabintsev** [comment]
No problem! Good luck! Please follow up once you have solved it, because there's not much more I can foresee myself doing to assist.

**Comment by asn111** [comment]
Hi, I don't know the reason but what I only did is cleaned my project and 
used the following code 
```
        let siren = Siren.shared
        let rules = Rules(promptFrequency: .immediately, forAlertType: .force)
        siren.rulesManager = RulesManager(globalRules: rules, showAlertAfterCurrentVersionHasBeenReleasedForDays: 1)
        siren.rulesManager = RulesManager(globalRules: .critical)
        siren.wail { results in
            switch results {
            case .success(let updateResults):
                print("AlertAction ", updateResults.alertAction)
                print("Localization ", updateResults.localization)
                print("Model ", updateResults.model)
                print("UpdateType ", updateResults.updateType)
            case .failure(let error):
                print(error.localizedDescription)
            }
        }
```

And it is working perfectly now.. Thanks for the support. :)

**Comment by ArtSabintsev** [comment]
Hey, glad it works for you! You only need to initialize rules manager one time, finish laser twice, then only the latest initialization will be used.
