### ISSUE TITLE
JSON out of sync with Store

### ISSUE THREAD

**Issue by blairjo** [ArtSabintsev/Siren#343]
Hi, 

Just a quick question if I may.. 

You mention that the JSON returned from the lookup can be slightly ahead of the store CDN version of the app, hence you have added a property showAlertAfterCurrentVersionHasBeenReleasedForDays.

I'm very new to IOS apps so forgive my ignorance, but I'm just wondering whether the discrepancy could be down to the fact that the default lookup is using the US locale? Can you confirm that even with the correct locale there can still be a mismatch between the JSON returned and the CDN ?

Thanks

John

**Comment by ArtSabintsev** [comment]
Hi,

I've seen other locales be even slower than the US one. There's no known rhyme or reason to it, unfortunately.

**Comment by blairjo** [comment]
ok thanks
