### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException

### ISSUE THREAD

**Issue by ergunkocak** [ArtSabintsev/Siren#344]
## If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: yes 5.4.5
- **What is your app's Bundle ID?**: no need for this
- **When was the latest version of your app published to the App Store?**: 2 weeks
- **Is your app published in the US App Store? If not, what App Store is it published in?**: German
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**: Not the issue

---

Getting crash reports from Firebase:

PresentationManager.swift - Line 248
specialized PresentationManager.getFirstForegroundScene() + 248

![Screenshot 2020-09-04 at 22 31 05](https://user-images.githubusercontent.com/610975/92282743-8cd38e00-eefe-11ea-9c5c-bd43d4e26fee.png)

**Comment by ArtSabintsev** [comment]
Thanks! 

- I will look into this in a few days. 
- What version of iOS are you seeing this on? 
- What device? 
- Have you been able to replicate it on a simulator?

**Comment by ergunkocak** [comment]
![Screenshot 2020-09-09 at 19 49 09](https://user-images.githubusercontent.com/610975/92635082-8f0a6380-f2d5-11ea-88f0-434ad10639f4.png)

**Comment by ergunkocak** [comment]
I could not replicate on ios simulator

**Comment by ArtSabintsev** [comment]
Can I see how you implemented Soren via some code snippets or a sample project? I am having a hard time replicating this issue.

**Comment by ergunkocak** [comment]
I could not reproduce either :( . It looks like the crash numbers are going down. Can it be caused by some problem in app store?

**Comment by ergunkocak** [comment]
This how i use siren :

```
Siren.shared.wail { results in
            switch results {
            case .success(let updateResults):
                log.debug("AlertAction \(updateResults.alertAction)")
                log.debug("Localization \(updateResults.localization)")
                log.debug("Model \(updateResults.model)")
                log.debug("UpdateType \(updateResults.updateType)")
                if updateResults.updateType == .unknown {
                    Alerter.newAppVersion(newVersion: updateResults.model.version)
                }
            case .failure(let error):
                log.debug(error.localizedDescription)
            }
        }
```
It is called in:
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool
```
I am guessing from the error that Siren is trying to create a view. But in my case there should not be any need for that while i am displaying my own view. Right?
Shall i move it after displaying home screen maybe?
Best

**Comment by ArtSabintsev** [comment]
Yes, I'd try moving it to be displayed a bit later on, since the issue seems to be window/scene based. Let me know what happens upon doing that in your next release.

Closing this issue - reopen this issue once you have an update.

Thanks!
