### ISSUE TITLE
I am using the latest version of siren for my ios application. I have not using this library since the first version release of my app but now the app have it and i added a new version which is released on app store. My app is distributed worldwide as well as US app store and nothing happens. Any idea about the cause of this issue? so in two words the alert of the new new update did not appear and it return with this error "[Siren Error] No new update available."

### ISSUE THREAD

**Issue by asssem** [ArtSabintsev/Siren#345]
## If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: 
- **What is your app's Bundle ID?**: 
- **When was the latest version of your app published to the App Store?**: 
- **Is your app published in the US App Store? If not, what App Store is it published in?**:
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**:

---

### Common Issue #1:
>"Error retrieving iOS version number as there was no data returned."

Check if your app is available in the US App Store, otherwise add the corresponding country code when setting up Siren.

### Common Issue #2:
> "Support for macOS App Store."

Siren does not and will not support the macOS App Store.

### Common Issue #3:
> "Support for prompting TestFlight users to update to the newest beta build."

Siren does not support this functionality. There is no publicly accessible TestFlight API akin to that of the public App Store API that Siren can utilize to provide this functionality.

# Please delete this text before submitting a new issue.

**Comment by ArtSabintsev** [comment]
Closing this issue. Please resubmit and follow the Issue Template. Thank you.
