### ISSUE TITLE
Can not see the update popup.

### ISSUE THREAD

**Issue by vggoli** [ArtSabintsev/Siren#346]
I followed the documentation. I Instaaled the pods , imported the siren module and added the code in app delegate.
My app is already on the AppStore and it is available only in US App Store. When I ran the app by using the lower version when running I can not see the pop up. 

I can see the error" Unbalanced calls to begin/end appearance transitions for <Siren.SirenViewController: 0x103b3bf90>."

When I checked the function apiManager.performVersionCheckRequest is getting valid values but the alert is not presented.

**Comment by ArtSabintsev** [comment]
Hi, could you please provide me with the following:

- Xcode Version
- iOS Version
- How long your app is in the App Store
- Sample code for how you implemented Siren and where you implemented it
- Bundle ID

**Comment by vggoli** [comment]
Hi
Xcode version is 11.5.
ios version: 13.5
We have our app since august 2018 in the App Store.
Bundle id : com.Surfboard
I am using the following code in didfinishlaunchwithoptions of AppDelegate.swift.

let siren = Siren.shared
//        siren.rulesManager = RulesManager(globalRules: .critical,
//                                          showAlertAfterCurrentVersionHasBeenReleasedForDays: 0)
      
        siren.rulesManager = .init(majorUpdateRules: .annoying, minorUpdateRules: .annoying, patchUpdateRules: .annoying, revisionUpdateRules: .annoying, showAlertAfterCurrentVersionHasBeenReleasedForDays: 1)
        siren.wail()

I used this pod file pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift5.0'

**Comment by ArtSabintsev** [comment]
Alright, first off, please use the version on master, as I do not support older deployments.
Second, another individual opened up a similar ticket, #347, and I will look into fixing it.

**Comment by ArtSabintsev** [comment]
See if this fixes it: https://github.com/ArtSabintsev/Siren/pull/348

**Comment by vggoli** [comment]
I updated the pod using the master. It worked.

Thank you

**Comment by ArtSabintsev** [comment]
great! Happy to hear that!
