### ISSUE TITLE
Opening notification center dismisses critical alert

### ISSUE THREAD

**Issue by Gabriel-Azevedo** [ArtSabintsev/Siren#347]
Hello,

Running the `hyperCriticalRulesExample()` from the Example app on a simulator and swiping down the notification center dismisses the alert. Subsequent notification center opening results in the following error log:

`Example[17107:313693] [Presentation] Attempt to present <UIAlertController: 0x7fedc680d000> on <Siren.SirenViewController: 0x7fedc240fed0> (from <Siren.SirenViewController: 0x7fedc240fed0>) which is already presenting <UIAlertController: 0x7fedc5845800>.`

Is this the correct behaviour? If so, is there a way to avoid that?

**Comment by ArtSabintsev** [comment]
Hi,

Is this new behavior, or is this the first time you are using this library with your app?

**Comment by ArtSabintsev** [comment]
OK, I am able to reproduce this using the example app in Xcode 12. I'll take a look.

Thanks!

**Comment by ArtSabintsev** [comment]
See if this fixes it: https://github.com/ArtSabintsev/Siren/pull/348

**Comment by Gabriel-Azevedo** [comment]
It didn't fix for me. 
I think the problem is that `applicationDidBecomeActive` gets (wrongfully) called by the OS when the notification center is fully opened.

Here's the log:
Start scrolling notification center: 
`applicationWillResignActive`

Finish scrolling, notification center fully open:
`applicationDidBecomeActive`
`applicationWillResignActive`

So when the notification center is dismissed, `applicationDidBecomeActive` is trigger once again but the `updaterWindow.isHidden` is false and the `cleanUp()` method gets called

**Comment by Gabriel-Azevedo** [comment]
Always cleaning up before presenting works, but the `attempt to present` warning continues.

```
cleanUp()
if rules.alertType != .none, let updaterWindow = updaterWindow, updaterWindow.isHidden {
    alertController?.show(window: updaterWindow)
}
```

**Comment by ArtSabintsev** [comment]
wow, so that's an OS level issue. I'll see if we can maybe work around it? Not sure.

**Comment by ArtSabintsev** [comment]
No idea how to fix this one. If you figure it out, let me know!
