### ISSUE TITLE
[iOS14] Status bar color during Siren alert presentation

### ISSUE THREAD

**Issue by giofid** [ArtSabintsev/Siren#351]
Hi @ArtSabintsev, I'm experiencing a problem with status bar style/color. Only in iOS14 the status bar changes color during the Siren alert presentation.

![siren](https://user-images.githubusercontent.com/13570450/97410214-100dd080-18ff-11eb-9aba-ff48cf23f532.gif)
[Siren-master.zip](https://github.com/ArtSabintsev/Siren/files/5450502/Siren-master.zip)

As you can see, the status bar is black before the alert is shown, it becomes wrongly white during Siren alert presentation and it comes back black after the alert disappears.

If I comment the `preferredStatusBarStyle` overriding in `SirenViewController` class, the problem goes away.

What is the purpose of this overriding? Is it possible to remove it?

**Comment by ArtSabintsev** [comment]
It's needed to fix an issue on iOS 13, for which I do not recall the details. I can look into it a bit later.

**Comment by ArtSabintsev** [comment]
Also, I think your screenshots maybe wrong based on your explanation?

**Comment by giofid** [comment]
I replaced the screenshots with a gif. I hope it's much clearer now. As you can see, the statusbar is initially black, it becomes white when alert appears and it comes back black after the alert disappears.

I also attach a slightly modified version of the demo that shows the problem.

Thank you.

**Comment by ArtSabintsev** [comment]
This should be fixed in v5.5.1 and beyond, which was just released. 

Thanks!

**Comment by giofid** [comment]
Thank you @ArtSabintsev. The problem is now fixed!

Can I ask you what's the purpose of retain the window in `SirenViewController`? I tried to comment [this](https://github.com/ArtSabintsev/Siren/blob/1f6ae4635d92c5926bc51d26ab756b4c06121b9f/Sources/Managers/PresentationManager.swift#L240) line and everything keeps working. Is this retain cycle no more needed?

**Comment by ArtSabintsev** [comment]
It was to fix this issue: https://github.com/ArtSabintsev/Siren/issues/305

Also, I may need to revert this change I made in this PR in the future since it was apparently attempting to fix a SceneDelegate issue in iOS 13. I’ll wait to see if anyone reports that issue still existing.
