### ISSUE TITLE
Problems with foreground and background observers

### ISSUE THREAD

**Issue by giofid** [ArtSabintsev/Siren#353]
Hi @ArtSabintsev,
I think there are two problems with foreground and background observers in `Siren`.

1. In an `.onDemand` perform check mode, I can bypass a `critical` alert simply putting the app in background and then in foreground again. Maybe it's better not to add background observers for `.onDemand` perform check mode.
2. At app startup, if a system alert (for example a push notification requestAuthorization popup) is showed concurrently with the Siren alert, the latter doesn't appear at all, or rather it appears below the system alert and suddenly disappears (the user doesn't see it) because `applicationWillResignActiveObserver` is called and the `presentationManager`cleaned up. I am not sure how it can be fixed, maybe `applicationDidEnterBackgroundObserver`is sufficient, 
 `applicationWillResignActiveObserver` could be removed and `UIApplication.didBecomeActiveNotification`changed in `UIApplication.willEnterForegroundNotification`. But again, I'm not sure.

**Comment by ArtSabintsev** [comment]
Hey,

1. I can add a change that just avoids/overrides this scenario in the initializer.
2. The idea here is that you don't present the app update notification unless all the system notifications that you plan on presenting have been presenting. At many companies I've worked with, we've built a priority queue that handles if an alert should be presented depending on priority, with the app update one being the highest or lowest depending on criticality.

Hope that helps!

**Comment by giofid** [comment]
Hi,
thank you for your response.

1. In an `.onDemand` scenario what's the purpose of adding background observers? I would change the `wail(performCheck:completion:)` func in this way
```
func wail(performCheck: PerformCheck = .onForeground,
              completion handler: ResultsHandler? = nil) {
     resultsHandler = handler
     switch performCheck {
     case .onDemand:
         removeForegroundObservers()
         removeBackgroundObservers()
         performVersionCheck()
     case .onForeground:
         addForegroundObservers()
         addBackgroundObservers()
     }
}
```
2. I get what you're saying, but I am still convinced there's something wrong with observers. I would change `Siren` extension in this way
```
private extension Siren {
    /// Adds an observer that listens for app launching/relaunching.
    func addForegroundObservers() {
        guard applicationDidBecomeActiveObserver == nil else { return }
        applicationDidBecomeActiveObserver = NotificationCenter
            .default
            .addObserver(forName: UIApplication.willEnterForegroundNotification,
                         object: nil,
                         queue: nil) { [weak self] _ in
                            guard let self = self else { return }
                            self.performVersionCheck()
        }
    }

    /// Adds an observer that listens for when the user enters the app switcher
    /// and when the app is sent to the background.
    func addBackgroundObservers() {
        if applicationDidEnterBackgroundObserver == nil {
            applicationDidEnterBackgroundObserver = NotificationCenter
                .default
                .addObserver(forName: UIApplication.didEnterBackgroundNotification,
                             object: nil,
                             queue: nil) { [weak self] _ in
                                guard let self = self else { return }
                                self.presentationManager.cleanUp()
            }
        }
    }
}
```

If you want, I can open a PR with this changes to let you see how they work.

**Comment by ArtSabintsev** [comment]
There was a very specific reason this had to be done and I no longer recall why. There's a lot of edge case scenarios, and this solved one of them.

I'm so far removed from this project these days that I don't recall what it is.
