### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by jacastaneda** [ArtSabintsev/Siren#356]
Hello there, i am implementing Siren on my iOS app, but when the prompt is shown and the Update option is touched i get this response from Safari:  "Safari cannot open the page because the address is invalid" can anyone help me please? i think is something related to url schemes but i can not find the solution, any help will be fully appreciated!

**Comment by ArtSabintsev** [comment]
Hi,

A lot of information is needed to solve this problem.

- What's the URL it's trying to open?
- Are you doing it in the simulator? **(If so, it won't work, so test on a device)**
- Is you app in the store?
- Is this your example app that ships with this SDK?
- What's the bundle ID if it's your personal app and it's live in the fore?

**Comment by jacastaneda** [comment]
Hello, i was testing it with simulators (my bad), it works on iOS 13 simulators (opens the app store's app page on the browser), but not on iOS under 13

Here are my responses to your questions:

    What's the URL it's trying to open? -> itms-appss://apps.apple.com/app/idxxxxxxxxxx
    Are you doing it in the simulator? (If so, it won't work, so test on a device) -> yes, i am trying on simulator (this is  enough to know why s not working, thanks a lot)
    Is you app in the store? -> Yes, it is
    Is this your example app that ships with this SDK? -> no, i am using it with a  personal app
    What's the bundle ID if it's your personal app and it's live in the fore? -> the bundle ID is: com.LCPtracker.trackerApp

Thanks a lot for your help @ArtSabintsev

**Comment by ArtSabintsev** [comment]
Hi - thanks for following up!

I'm sorry I don't understand the problem. You said it works on iOS 13, but not on versions before iOS 13, correct?

If it works on iOS 13 when clicking update, then what's the issue? If you want to test actually opening the App Store, you need to test it on the physical device, but if the alert pops up, then everything is working with the library. 

Clicking on the link and the link that is sent back is some thing that is out of the control of the library.￼

Does that make sense?

**Comment by ArtSabintsev** [comment]
Closing due to lack of follow up.
