### ISSUE TITLE
I plan to integrate this pod in my project, Will my iOS app be rejected after submission? I see we have used Itunes Search Api for versioning control

### ISSUE THREAD

**Issue by anshu-raj19** [ArtSabintsev/Siren#364]
In order to provide force update feature, I need a version check in my code. I was thinking to use Itunes search api, I can use it to compare two versions and provide a force upgrade option on version mismatch. Was just a bit skeptical though before going on with this approach, I have heard apple might reject submissions if Itunes search api is used. I could not find exact thread which suggest the case, hence thought of asking it here. Kindly help. Thanks in advance.

**Comment by ArtSabintsev** [comment]
Apple won't ever see this message pop up during the review process, and I have used this tool and it's ObjC predecessor in many apps, both small and large, without any issues. I think you'll be fine!
