### ISSUE TITLE
update notification keeps showing regardless you have latest version installed

### ISSUE THREAD

**Issue by mobashir0155** [ArtSabintsev/Siren#366]
- using siren for swift 3.2
- se.score.ios.Score
- 26 march 2021
- publish in 155 countries:

---

we have set showAlertAfterCurrentVersionHasBeenReleasedForDays = 5, and if user installs the app right after its available, and after 5 days of release "popup" for update starts showing, it says update your app  with latest version number, but when you click on update it takes you to appstore and there you dont see any update option only "OPEN" and when you click on "open" it takes you back to the app and "popup" with update message shows up again, this cycle continues.

---
**here's my setting for siren:**
siren.showAlertAfterCurrentVersionHasBeenReleasedForDays = 1
        siren.revisionUpdateAlertType = .force
        siren.alertType = .force
        siren.forceLanguageLocalization = .Swedish
 --
 **inside "_applicationDidBecomeActive_":**
 Siren.shared.checkVersion(checkType: .immediately)

**Comment by ArtSabintsev** [comment]
Hi, I don't off support for any version of Siren that isn't using the latest version of Swift, especially a version that's 3+ years old at this point. Sorry.

**Comment by faris-mobile89** [comment]
I had the same issue, it happens when the version number in the IPA does not match the version of the app on the App Store.

**Comment by ArtSabintsev** [comment]
> I had the same issue, it happens when the version number in the IPA does not match the version of the app on the App Store.

Please open a new issue and make sure you are using the latest release of the library.

Thanks.
