### ISSUE TITLE
update notification keeps showing regardless you have latest version installed

### ISSUE THREAD

**Issue by mobashir0155** [ArtSabintsev/Siren#367]
Using latest version of Siren
se.score.ios.Score
Apr 7, 2021 
publish in 155 countries:

---
I posted this issue before but then i was using older version of siren, now i updated to latest version and still issue is same as in #366 . whenever i open my app even though i updated to latest version it keeps showing update notification and when open appstore there is already latest version installed.
Here's my setting in Appdelegate.swift:
       ```
let siren = Siren.shared
        siren.rulesManager = RulesManager(globalRules: .annoying,
                                          showAlertAfterCurrentVersionHasBeenReleasedForDays: 1)
        siren.presentationManager = PresentationManager(forceLanguageLocalization: .swedish)
        siren.wail { results in
                    switch results {
                    case .success(let updateResults):
                        print("UpdateType", updateResults.updateType)
                    case .failure(let error):
                        print(error.localizedDescription)
                    }
                }
```

**Comment by ArtSabintsev** [comment]
I tried this in the sample app in this project (e.g., changed the bundle ID to `se.score.ios.Score` and version to `2.0.2`) and I can't recreate this issue. 

Does this problem exist in the sample app?

**Comment by mobashir0155** [comment]
No that's the problem in the sample app when running the latest version we don't see any notification it is working perfect. This problem is only in live version.

**Comment by ArtSabintsev** [comment]
Makes no sense to me. The sample all replicates a real world scenario and it's my only way to test if something is truly wrong in the code. I don't think k I can offer and more help, since I can't reproduce it on my end.
