### ISSUE TITLE
Adding custom rules based on other data than next update's version (JSON key/value)

### ISSUE THREAD

**Issue by sebastien-tribu** [ArtSabintsev/Siren#369]
I understand that the RulesManager is able to track changes based on `MAJOR/MINOR/PATCH/REVISION`. However, sometimes a bugfix on iOS is merely of type PATCH **on the app** but has a huge impact on other platforms (web, backend, etc.). In that sense the app version does not qualify for a MAJOR update, but we _really really_ would want to force the update. Could the RulesManager also inspect and change the settings based on client-defined rules that compares to the JSON? Is there documentation on the looks of the JSON file?

Here's a few custom rules I imagined:
* If revision number is even
* If revision number is above 9000
* If English update notes contains "This update is HIGHLY recommended"

If I were to implement this I would imagine the RulesManager accepting a variadic parameter `customRules` for which each CustomRule is a typealias containing a JSON key and an enum for basic predicate rules for the corresponding JSON value.

Would this be an interesting feature?

Thanks

**Comment by ArtSabintsev** [comment]
I get what you're saying, but this is super custom and I think only really useful for your specific use case. I say that, because in 9 years o managing this SDK in ObjC and Swift, no one has ever asked for this, and to be honest, it seems like there should be a custom configuration file used on your server to help drive how/when Siren works (which is what I've done at a previous employer).

**Comment by sebastien-tribu** [comment]
> a custom configuration file used on your server to help drive how/when Siren works

You're correct, at this time we have a "kill switch" that shows an unavoidable Alert (with only the option to go to the App Store) based on a custom HTTP error code from our server. This is rare but useful when introducing a breaking change in the API. The downside of this is that only the server has control over this and not an upcoming iOS update with important fixes, without necessarily being a breaking change in the API.

What I was hoping for is to be able to control the importance of an update based on the new update, and not based on the current app's behavior.

I'll try another way, thanks.

**Comment by ArtSabintsev** [comment]
Totally understand! You're welcome to fork Siren and add a custom change for yourself,
