### ISSUE TITLE
PresentationManager - iOS 13- error

### ISSUE THREAD

**Issue by g012** [ArtSabintsev/Siren#370]
Hello,

I have a build error with the latest version in PresentationManager.swift, as the function getFirstForegroundScene() requires iOS 13.

Why was this backward compatible code removed ?

```
private extension PresentationManager {
    private func createWindow() -> UIWindow? {
        var window = UIWindow()
        if #available(iOS 13.0, tvOS 13.0, *) {
            guard let windowScene = getFirstForegroundScene() else { return nil }
            window = UIWindow(windowScene: windowScene)
        } else {
            window = UIWindow(frame: UIScreen.main.bounds)
        }
        guard let windowScene = getFirstForegroundScene() else { return nil }

        let window = UIWindow(windowScene: windowScene)
```

Thank you.

**Comment by ArtSabintsev** [comment]
Hey, can you show me the error, and you're 100% using the latest version?

**Comment by g012** [comment]
I don't have any version specified in the Podfile, so I guess yes. It happened right after I updated, the code is in HEAD at least : https://github.com/ArtSabintsev/Siren/blob/master/Sources/Managers/PresentationManager.swift

Here's the shot of XCode showing the error :
![Shot](https://user-images.githubusercontent.com/1038562/120216100-dd320f00-c236-11eb-92e0-e1af2de102bf.png)

**Comment by ArtSabintsev** [comment]
Ah yes. I made it such that the repo requires a minimum of iOS 13 at this point. I did this a few months ago. At the time I had plans to introduce combine, but I got busy at work.￼￼ still, that's the reason this is happening.￼

**Comment by g012** [comment]
Roger. Well, we were planning on moving to iOS 13 too, so I guess that's the signal !
Thank you.

**Comment by ArtSabintsev** [comment]
No problem! Thanks for understanding!
