### ISSUE TITLE
No such module 'Siren'

### ISSUE THREAD

**Issue by sagarsukode** [ArtSabintsev/Siren#371]
I was using
pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift4.1' # Swift 4.1
Xcode: 11.4.1

Now I am using 
pod 'Siren'
Xcode 12.5

Issue is:
It is showing "No such module 'Siren'" in AppDelegate, please check below screen shot:

<img width="972" alt="Screenshot 2021-06-22 at 6 24 39 PM" src="https://user-images.githubusercontent.com/15633194/122928806-d5721000-d387-11eb-815b-2158b968ce5c.png">

Note: 
- I have clean the project and check again
- tried pod deintegrate and pod install
- Clean Derived Data as well
- Clean, closed and reopen the Xcode

**Comment by ArtSabintsev** [comment]
Please switch from using branch swift4.1 to using master.
