### ISSUE TITLE
Xcode beta 3 and 4 support

### ISSUE THREAD

**Issue by isaranjha** [ArtSabintsev/Siren#373]
Getting the following error whenever using .shared. 

`'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

Needs to be addressed with:

`@available(iOSApplicationExtension, unavailable)`

**Comment by ArtSabintsev** [comment]
Will adjust soon - thanks!

**Comment by mltbnz** [comment]
Seems like this is resolved with Xcode's beta 5 release

**Comment by ArtSabintsev** [comment]
Awesome!
