### ISSUE TITLE
Update notification keeps showing regardless you have latest version installed

### ISSUE THREAD

**Issue by gargDigrt** [ArtSabintsev/Siren#376]
Using the latest version of Siren.
Update dialogue is visible even app gets installed directly from the App store.

//My Code

  Siren.shared.wail(performCheck: .onDemand) { results in
            switch results {
            case .success(let updateResults):
                print("AlertAction ", updateResults.alertAction)
                print("Localization ", updateResults.localization)
                print("Model ", updateResults.model)
                print("UpdateType ", updateResults.updateType)
            case .failure(let error):
                print(error.localizedDescription)
            }
        }

**Comment by ArtSabintsev** [comment]
Why are you using `.onDemand`? 

Ideally, choose an option that's listed in the Sample project that works best for your scenario.

**Comment by gargDigrt** [comment]
@ArtSabintsev OK, I'll try this.
