### ISSUE TITLE
Update AlertView show and Auto hide without any click Action 

### ISSUE THREAD

**Issue by pradeeps43** [ArtSabintsev/Siren#377]
Using Siren (5.1.2) this Version .When app launch alert pop show for second and hide itself without any action , on  iOS 14 .

**Comment by ArtSabintsev** [comment]
Please provide me with sample code and/or a video of how you use it. Ideally, if you can reproduce it with the sample project that ships with Soren, that would be helpful.

**Comment by anashkevichp** [comment]
had the same issue with 5.1.0 version installed. 
we call `Siren.shared.wail()` on both `applicationWillEnterForeground` and `applicationDidBecomeActive`. Alert shows for less than a second and then immediately closes. 
maybe calling `wail()` in two places causes this issue 🤷🏼‍♂️

**Comment by anashkevichp** [comment]
UPD: re-checked with the latest (low deployment target) version `5.8.1` and it works fine there. So I think issue might be closed.
