### ISSUE TITLE
Min IOS 15?

### ISSUE THREAD

**Issue by ergunkocak** [ArtSabintsev/Siren#379]
Hi,

First of all thanks for the library, its very very useful.

As far as i see latest version 6.0.0 requires min IOS version to be 15. Is this on purpose or am i missing something :) 

Best

**Comment by ergunkocak** [comment]
Yep it is on purpose :) https://github.com/ArtSabintsev/Siren/releases/tag/6.0.0

**Comment by ArtSabintsev** [comment]
Yup, glad you found out why!
