### ISSUE TITLE
App update availability delay

### ISSUE THREAD

**Issue by dimazen** [ArtSabintsev/Siren#381]
## If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: 5.8.1
- **What is your app's Bundle ID?**: NDA
- **When was the latest version of your app published to the App Store?**: less than 6 hours ago
- **Is your app published in the US App Store? If not, what App Store is it published in?**: US and worldwide
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**:

---

Despite this issue being answered before, there is major issue:
During building of the iTunes request, `country` argument needs to be changed. I understand that the way you name argument comes from an iTunes Search API, but it has been archived for a while. In this way, I can get latest results right away, while with `country` I'm getting an old results.

For example: 
```
$ curl https://itunes.apple.com/lookup\?bundleId\=com.my.bundle\&country\=US | grep 'version'
```
responds me with 
```
... "version":"2.5.3" ...
```
while after a small change I'm getting correct results:
```
$ curl https://itunes.apple.com/US/lookup\?bundleId\=com.my.bundle | grep 'version'
// this is also a valid change
$ curl https://itunes.apple.com/lookup\?bundleId\=com.my.bundle\&country\=no | grep 'version'
```
returns
```
... "version":"2.6.0" ...
```

Can this be addressed, please?

**Comment by ArtSabintsev** [comment]
This only works if an app is available in a specific country. The default is US. There is a property that's let's you change countryCode on APIManager, I think.

I'm on mobile so I can't confirm at the moment.
