### ISSUE TITLE
Getting error in files

### ISSUE THREAD

**Issue by Justinjj10** [ArtSabintsev/Siren#383]
I am using Xcode version 13.1 and I had installed the latest pod file. After installing the pods,  I got errors in library classes after trying to run the project. Got the error "'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead."
<img width="729" alt="Screenshot 2021-12-14 at 12 36 40 PM" src="https://user-images.githubusercontent.com/24618284/145950478-ec499e9a-f2f8-49a1-b94b-1694eeea8aa5.png">
<img width="760" alt="Screenshot 2021-12-14 at 12 36 25 PM" src="https://user-images.githubusercontent.com/24618284/145950491-6475216c-bcf9-4944-8ecb-2dbf61ba7d67.png">

**Comment by ArtSabintsev** [comment]
Hey - siren doesn't work in app extensions, only in the main app.
