### ISSUE TITLE
iOS 13

### ISSUE THREAD

**Issue by fuxlud** [ArtSabintsev/Siren#385]
What should I do to support Siren on iOS14? Importing with Package Dependencies. 
I've tried importing specific brunch (5.8.0), but getting the following error: 

compiling for iOS 13.0, but module 'Siren' has a minimum deployment target of iOS 15.0: 
Command MergeSwiftModule failed with a nonzero exit code.

**Comment by ArtSabintsev** [comment]
Are you sure you pulled in the right version?

Screen cap please or sample project

**Comment by fuxlud** [comment]
<img width="1092" alt="Screen Shot 2021-12-23 at 10 31 48" src="https://user-images.githubusercontent.com/1950116/147212396-a15a9c18-1928-4b50-92e7-3f6e04978215.png">
<img width="689" alt="Screen Shot 2021-12-23 at 10 32 25" src="https://user-images.githubusercontent.com/1950116/147212404-b6db077f-159b-420b-ad0
<img width="628" alt="Screen Shot 2021-12-23 at 10 32 54" src="https://user-images.githubusercontent.com/1950116/147212412-9b08e1a7-6cfb-4cb4-9f98-d76aa06e187b.png">
8-f51395312e92.png">

Thanks for taking the time!

**Comment by fuxlud** [comment]
Closing issue as it works properly on an empty new project.

**Comment by ArtSabintsev** [comment]
Ok great! Thanks for the update!
