### ISSUE TITLE
How to fix the error "Error retrieving App Store data as the JSON results were empty"?

### ISSUE THREAD

**Issue by iskalinov13** [ArtSabintsev/Siren#387]
## If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: 
-  I use the version 5.7.1, because minimum deployment target is iOS 12. 
- **What is your app's Bundle ID?**: 
- kz.forte.kassa
- **When was the latest version of your app published to the App Store?**: 
- 1 month ago
- **Is your app published in the US App Store? If not, what App Store is it published in?**:
- Kazakhstan App Store
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**:
- Did not check
---

I alway get the same error:
[Siren Error] Error retrieving App Store data as the JSON results were empty. Is your app available in the US? If not, change the `countryCode` variable to fix this error.

let siren = Siren.shared
        siren.apiManager = APIManager(countryCode: "KZ")
        siren.wail { results in
            switch results {
            case .success(let updateResults):
                print("AlertAction ", updateResults.alertAction)
                print("Localization ", updateResults.localization)
                print("Model ", updateResults.model)
                print("UpdateType ", updateResults.updateType)
            case .failure(let error):
                print(error.localizedDescription)
            }
        }

**Comment by ArtSabintsev** [comment]
Please make sure your bundleID works in the sample app first.
