### ISSUE TITLE
Siren_Siren.bundle: No such file or directory

### ISSUE THREAD

**Issue by yusuftor** [ArtSabintsev/Siren#388]
Whenever I try to archive my app I get the error: 

```
error: /Users/Me/Library/Developer/Xcode/DerivedData/MyApp-drtjyfprawspkugsppqwsoychoqp/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Release (Production)-iphoneos/Siren_Siren.bundle: No such file or directory (in target 'MyApp' from project 'MyApp')
```

I'm adding Siren via SwiftPM. How can I fix this?

**Comment by ArtSabintsev** [comment]
Please provide me with a sample app with your integration using SwiftPM

**Comment by yusuftor** [comment]
@ArtSabintsev Thanks for the quick reply! In the process of creating a sample app for you I've fixed it. It was due to having two environments - staging and production. It was accidentally archiving as a staging app, rather than production. After changing that, it worked.

As a side note, keep up the great work with this framework. It's super useful :)

**Comment by ArtSabintsev** [comment]
Thanks!
