### ISSUE TITLE
Support SwiftUI?

### ISSUE THREAD

**Issue by kr1s0404** [ArtSabintsev/Siren#389]
Can you show us some usages of how we can use this repo in SwiftUI?

**Comment by ArtSabintsev** [comment]
I'm no longer an active iOS developer, so I don't really know SwiftUI that well. I'd be open to someone contributing a sample project.

**Comment by kr1s0404** [comment]
It's fine! I just managed to solve the question by myself without using a package, but still, thank you for contributing in the iOS development!

**Comment by ArtSabintsev** [comment]
Sounds good!
