### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by mikemee** [ArtSabintsev/Siren#39]
It would be great to have Carthage support. If I create a PR, would you accept it?  

_(Not that I'm a Carthage creation expert, but it would give me extra incentive to try if I know it will be accepted and updated ongoing, thanks!)_

**Comment by ArtSabintsev** [comment]
Will look into it this week!

**Comment by ArtSabintsev** [comment]
Haven't forgotten. Will look at it tomorrow.

**Comment by mikemee** [comment]
Thanks Art!  No rush on my end. Sorry I haven't had time to help. I got a little sidetracked with https://github.com/stephencelis/SQLite.swift/ 😀

**Comment by ArtSabintsev** [comment]
oh wow! I read about this the other day - awesome work!

**Comment by mikemee** [comment]
Ah, you've heard of it. Then I hasten to add that it's not my project - I just helped Stephen out a little with a recent update. The credit is all his!

**Comment by ArtSabintsev** [comment]
Ah, got it! Awesome :+1:

**Comment by ArtSabintsev** [comment]
ok, doing this in the morning, for real.

Found a nice tutorial: https://medium.com/@shenghuawu/support-carthage-for-your-swift-framework-f294c691f9ba#.jnneapgsy

**Comment by ArtSabintsev** [comment]
See https://github.com/ArtSabintsev/Siren/pull/42 for the PR on it. Closing this issue in place of the PR.
