### ISSUE TITLE
Install github slack integration.

### ISSUE THREAD

**Issue by alrocha** [ArtSabintsev/Siren#390]
Hi there! 

When trying to add slack notifications for new releases I get this message
![image](https://user-images.githubusercontent.com/8307263/155231073-79cae212-43d0-4202-98ae-a0e6a4f5e40d.png)

The link given by the Github app is [this one](https://slack.github.com/github/v2/install/854860/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlnZ2VyX2lkIjoiMzEzNzAwODM0MDAyMi4zNjAzNDI1ODE5NDIuY2Y5MGM3NjgwMmY0ODYzNmM2YmY3ZjU2OGY4NjNlOTkiLCJ0ZWFtSWQiOiJUQUxBMkgzVFEiLCJjbGllbnREb21haW4iOiJ2b2lhcHAiLCJ1c2VySWQiOiJVMDIwUEtaQUhDWSIsImNoYW5uZWxJZCI6IkMwMzNZNUFQMzE4IiwidHJpZ2dlcmluZ0FwcCI6IkEwMUJQN1I0S05ZIiwicmVwbGF5Q29tbWFuZCI6dHJ1ZSwiaWF0IjoxNjQ1NTY5MTk2LCJleHAiOjE2NDU1NzI3OTZ9.Dj_tPKwdynIqv729jLLNVpj3w2SvEpMJRUMra0IMx1Q) 

Could be possible to install it?

Thanks in advance!

**Comment by ArtSabintsev** [comment]
Hi, I can't launch that link. Just goes to a dead end. Not sure what I'm supposed to do here.

**Comment by ArtSabintsev** [comment]
Thanks

This would give easy write access to the bot for issues. I don't want a deluge of issues coming in here.

What are you wanting an integration for exactly?

**Comment by alrocha** [comment]
To be aware of new release, we have a dedicated channel in slack configured with the github bot to notify us about new releases of packages, super nice to keep track of the dependencies easily.

**Comment by ArtSabintsev** [comment]
Try now. I don't use slack anymore, so hopefully what I did, works.
