### ISSUE TITLE
Can I have a different text in the alert depending on the type of alert displayed?

### ISSUE THREAD

**Issue by frank137** [ArtSabintsev/Siren#393]
Is there a way to show a different text in the alert depending on the type of alert? 
For example, 

If my Rule says that for a minor update I want the rule to be .annoying and for a major update the rule is .critical, then can I show a different body and title in the alert?

> "Please make sure to update your app" **in the case of .annoying**

> "You need to update your app in order to continue using it" **in the case of .critical.** 

Thanks!

Frank

**Comment by ArtSabintsev** [comment]
Yes, see this example: https://github.com/ArtSabintsev/Siren/blob/master/Example/Example/AppDelegate.swift#L121
