### ISSUE TITLE
How to update StoredSkippedVersion from custom UI

### ISSUE THREAD

**Issue by skyfoxa** [ArtSabintsev/Siren#394]
Hey, is there a way how to update StoredSkippedVersion in UserDefaults when custom prompt is used? We would like to use custom design instead of system alerts, but I'm not sure how to control Skip version flow from there.

**Comment by ArtSabintsev** [comment]
There is not a way to update the value. You can definitely build custom modals that present based of your own rules, but that logic of when to skip/present is something you'll have to build yourself as that's too specific for a general purpose library such as this one.
