### ISSUE TITLE
Siren localization .croatian

### ISSUE THREAD

**Issue by agale92** [ArtSabintsev/Siren#395]
Hi, Pls change localization for croatian:

/* Update alert message: A new version of {APP NAME} is available. Please update to version {NEW VERSION} now.*/
"A new version of %@ is available. Please update to version %@ now." = "Nova verzija %@ je dostupna. Ažuriraj na verziju %@ sada.";

/* Update alert title */
"Update Available" = "Novo ažuriranje je stiglo";

/* Update alert dismiss button title */
"Next time" = "Sljedeći put";

/* Update alert skip button title */
"Skip this version" = "Preskoči ovu verziju";

/* Update alert skip button title */
"Update" = "Ažuriraj";

Thank you.

Best regards

**Comment by ArtSabintsev** [comment]
Hey @jinjic - you did the original localization. Can you comment here.

**Comment by jinjic** [comment]
yes I see there is a minor error in the first line. "Update alert message..." So the suggested line is correct.

In the second line it should be updated to the masculine gender noun. But instead of saying "Update Available" = "Novo ažuriranje je stiglo" as suggested I think we should actually change it to "Update Available" = "Novo ažuriranje je dostupno"

The rest of the translation and suggestions match.

**Comment by agale92** [comment]
yes that's fine.  Pls change text in localization.

/* Update alert message: A new version of {APP NAME} is available. Please update to version {NEW VERSION} now.*/
"A new version of %@ is available. Please update to version %@ now." = "Nova verzija %@ je dostupna. Ažuriraj na verziju %@ sada.";

/* Update alert title */
"Update Available" = "Novo ažuriranje je dostupno";

/* Update alert dismiss button title */
"Next time" = "Sljedeći put";

/* Update alert skip button title */
"Skip this version" = "Preskoči ovu verziju";

/* Update alert skip button title */
"Update" = "Ažuriraj";

**Comment by ArtSabintsev** [comment]
Can you open a PR

**Comment by agale92** [comment]
Hi Art, I can did not create PR for now, because my laptop is broken. I have business laptop but can did not create ssh or authenticate in GitHub, because I have restriction for other web page.

Pls you can do it change code for localisation Croatian.


Thank you wey much.


BR,
Ante Galic

**Comment by ArtSabintsev** [comment]
No problem - I can wait until your laptop is fixed for you to open a PR with the changes and updates tests.

Thanks!

**Comment by ArtSabintsev** [comment]
Fixed just now. Will be pushing a new version momentarily. Thanks again.
