### ISSUE TITLE
Alert doesn't appear the first time you open the app.

### ISSUE THREAD

**Issue by kdouvris** [ArtSabintsev/Siren#398]
Hello. I have an issue with force updates. I want the alert to appear when the app launches and then every time it comes back from the background (so it's "unusable" until you update the app). I am using .wail() with AlertType = force and UpdatePromptFrequency = immediately, but the alert doesn't appear when i launch the app. Version is 5.8.0. Hope you can help me! Thanks in advance.

**Comment by ArtSabintsev** [comment]
Have you tried the sample app? Does it work in there? If so, then something is wrong with your implementation. You can share your own sample project if you need help diagnosing.

**Comment by kdouvris** [comment]
Hi!it’s working fine in the sample app. i use siren in the app of the company i work for so i don’t know if i can share the code.Long story short, i found a way around it and it’s working now, but i found another issue. When opening the notification center the alert disappears. i saw that you fixed this in the master branch but our app uses iOS 14+ so i can’t get the changes you made. Is there a way you can make this fix for older versions too?(like 5.8.0 that we’re using) It would make my life so mush easier if you could! Thanks for the fast response btw!

**Comment by ArtSabintsev** [comment]
Feel free to adapt the fix for iOS14. Due to changes I made to async calls, I had to bump the version.

Per the docs, I only support what's on master due to time issues.

Glad you got it working though! It should be an easy change.

Good luck!
