### ISSUE TITLE
Show update alert in UIViewController issue

### ISSUE THREAD

**Issue by HadyHammad22** [ArtSabintsev/Siren#401]
Try to call Siren.shared.wail() in UIViewController but has no action but it worked good when call it from AppDelegate

**Comment by ArtSabintsev** [comment]
Does it work in the sample app that comes with this library? If so, then the issue is with how you set it up in your app delegate and whatever else may be going on there.

**Comment by HadyHammad22** [comment]
The sample app call siren in app delegate and that also work in my app but I need to call siren in a specific view controller instead of app delegate, Is this available?
