### ISSUE TITLE
Error retrieving iOS version as it returns wrong new version

### ISSUE THREAD

**Issue by TommyCSS** [ArtSabintsev/Siren#406]
I used latest version of Siren and my app is published in specific region, 'id'.

My current app store version is 1.3.4 released less than 3 hours ago and the previous version was 1.3.3.
for every user has v1.3.3 new update alert is not showing. i tried to lower the version on my xcode to 0.0.1, new version alert pop up with text 'version 1.3.3' available. it should be 1.3.4 since its already released less than 3 hours ago

**Comment by ArtSabintsev** [comment]
Per the README, you have to wait 24-48 hours for Apple's CDNs to update.

**Comment by TommyCSS** [comment]
its been 4 days

**Comment by TommyCSS** [comment]
its been 4 day since 1.34 released. alert is still not. showing up for user with v1.3.3

**Comment by TommyCSS** [comment]
its been 4 day since 1.34 released. alert is still not. showing up for user with v1.3.3
should i put 2 days delay in the code?

@ArtSabintsev

**Comment by ArtSabintsev** [comment]
Does it work on the sample project?
