### ISSUE TITLE
Help resolving a version number mistake

### ISSUE THREAD

**Issue by nickvelloff** [ArtSabintsev/Siren#409]
I have been using this for a while and appreciate the work!

I made a dumb mistake, and I'm struggling to find a way out of it. I left a decimal point out of the version number and it made it into the app store. `2.0028` was supposed to be `2.00.28`

Interestingly with versions like `2.00.29` and even `3.00.00` it recognizes `2.0028` as a newer version.
<img width="312" alt="Screenshot 2023-05-03 at 7 35 14 PM" src="https://user-images.githubusercontent.com/885369/236098549-1c5caf37-5251-453d-b775-c20c3f4da916.png">

Given Apple isn't going to allow me to correct this version, I was hoping you could help me out.

Version `3.00.00` <<-- Even this one shows alert to update to `2.0028`
Version `2.00.29` <<-- Shows alert to update to `2.0028`
Version `2.0028` <<-- OOPS!
Version `2.00.27`
Version`2.00.26`
Version `2.00.25`

**Comment by ArtSabintsev** [comment]
hey - the logic for this is found here: https://github.com/ArtSabintsev/Siren/blob/master/Sources/Utilities/DataParser.swift#L69

You may want to see why 2.0028 overrides every new version, even 3.
