### ISSUE TITLE
Supporting older versions of iOS (iOS 13+) 

### ISSUE THREAD

**Issue by ggafos** [ArtSabintsev/Siren#410]
Hi [ArtSabintsev](https://github.com/ArtSabintsev) great work 👏

I was wondering if you plan to push the bug fixes (e.g. https://github.com/ArtSabintsev/Siren/pull/404, https://github.com/ArtSabintsev/Siren/pull/405) which are very crucial also to the latest version that you have (v5.8.1) that supports older iOS versions.
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/3323529/236136954-d60b848e-18a3-49d5-9cf4-44336e1b29c8.png">

<img width="564" alt="image" src="https://user-images.githubusercontent.com/3323529/236137774-8e87682b-b94b-487c-8bb3-966f123a2c92.png">

There is a clear no above but I thought of giving a try...

**Comment by ArtSabintsev** [comment]
Left a comment in your PR.
