### ISSUE TITLE
Siren popup shows even though there's no newer version available

### ISSUE THREAD

**Issue by itamargilvybe** [ArtSabintsev/Siren#412]
I have a SwiftUI app and Siren triggers an alert even when my app is updated to the latest AppStore version.

Here's my code which I implement in AppDelegate's didFinishLaunchingWithOptions:
```
let siren = Siren.shared
        siren.presentationManager = PresentationManager(alertTitle: "Update to the latest version", alertMessage: "To get the latest features", updateButtonTitle: "Update)
        siren.rulesManager = RulesManager(globalRules: .critical, showAlertAfterCurrentVersionHasBeenReleasedForDays: 0)
        siren.wail()
```

I'm running on Xcode 14.3, with iOS 16.0.

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: YES
- **What is your app's Bundle ID?**: 1523233268
- **When was the latest version of your app published to the App Store?**: May 22nd, 2023
- **Is your app published in the US App Store? If not, what App Store is it published in?**: YES
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**: YES

**Comment by ArtSabintsev** [comment]
Hi - what's the latest version? You provided the date not version number. 

Thanks!

**Comment by itamargilvybe** [comment]
It's 7.0.3; so I added a 1 day delay `showAlertAfterCurrentVersionHasBeenReleasedForDays: 0` and it seems to work fine now. Thank you!
