### ISSUE TITLE
iOS request cache - question

### ISSUE THREAD

**Issue by bbialas** [ArtSabintsev/Siren#413]
I just encountered a problem, that my app was released to the App Store, the update was already visible in the App Store, but the request to **https://itunes.apple.com/lookup?bundleId=XXX&country=XXX** was still returning previous app version information.

After checking the server response, I realized that one of the response headers shows that the response is cached on the Apple server and that's the reason.

```
X-Cache: TCP_MEM_HIT from a104-85-249-20.deploy.akamaitechnologies.com (AkamaiGHost/11.1.3-49328623) (-)
Cache-Control: max-age=12989
```

Why not to implement a cache-busting solution into this plugin, to always get the latest result from the Apple server?

It could be done like:
https://itunes.apple.com/lookup?bundleId=XXX&country=XXX**&t=<current_timestamp>**

What do you think?

PS.
When I tested it with this solution, I got a good response with the latest app version data.
I never had this issue before, and I wonder, if this caching is maybe something new introduced by Apple on their servers...

**Comment by ArtSabintsev** [comment]
Hi - feel free to open a PR

**Comment by ArtSabintsev** [comment]
Hi, as mentioned above, I need a PR open to review this. I don't actively do iOS development anymore.

**Comment by bbialas** [comment]
Hello,
I created a PR, please take a look.

Thank you.
