### ISSUE TITLE
When redirect to app store it shows download icon in place of update button

### ISSUE THREAD

**Issue by lokeshiOS** [ArtSabintsev/Siren#423]
For example current version is 2.7 and App Store version 2.8. 
So when alert occur i click on update and it redirect to app store but there it shows download button in place of update.
Please se the attach link - https://drive.google.com/file/d/1Us8xHK62hPFAVL5fzbcbpc9PlqmKhA09/view?usp=sharing
Please help me out of this......

**Comment by ArtSabintsev** [comment]
This is because it takes up to 24-72 hours or so for the update to propagate to all of the app stores CDNs. This should be in the reader as well.

**Comment by lokeshiOS** [comment]
I have uploaded my app 4 week ago in app store, and app store is showing the latest version but its showing download button only no button for update.

**Comment by ArtSabintsev** [comment]
Seems to work as is? Not sure what to tell you. This is an App Store app issue.
