### ISSUE TITLE
FeatureRequest: UpdatePromptFrequency 1 month

### ISSUE THREAD

**Issue by abear247** [ArtSabintsev/Siren#426]
It would be really helpful to have a 1 month prompt frequency. The reason for this would be to do a force prompt only after major updates. I have a 1 day optional prompt after a regular version, but when we do major version changes it would be great to force everyone after a month. This gives us more time to ensure the release is stable, avoid being as disruptive as 1 week, and help us delete backend code as needed (more common after a major change).

**Comment by ArtSabintsev** [comment]
Hey, sorry for the delay in responding. I'm not actively coding these days. 

Looking through the code, I feel like adding a monthly option here (https://github.com/ArtSabintsev/Siren/blob/master/Sources/Models/Rules.swift#L83) will easily address this issue.

Feel free to make a PR with the change and associated tests if there are any and I'll get to it soon.

**Comment by ArtSabintsev** [comment]
Closing as there's no response.
