### ISSUE TITLE
Support for country specific releases

### ISSUE THREAD

**Issue by newarockkid** [ArtSabintsev/Siren#44]
If an app has only been made available to a certain region, then the iTunes look up returns an empty array.

If I add a country parameter to the iTunes lookup url, then it returns the correct response. (e.g https://itunes.apple.com/lookup?id=xxxxxxxx&country=xx)

Just thought it'd be a good thing to have. :)

**Comment by newarockkid** [comment]
Just saw that it was already in there. Apologies.

**Comment by ArtSabintsev** [comment]
No problem - glad you found it!
