### ISSUE TITLE
Can't push 0.2.0 to CocoaPods

### ISSUE THREAD

**Issue by ArtSabintsev** [ArtSabintsev/Siren#5]
Already posted the issue here https://github.com/CocoaPods/CocoaPods/issues/3056

Will close once I can push.

**Comment by ArtSabintsev** [comment]
All fixed. 0.2.0 pushed to cocoapods.

**Comment by getaaron** [comment]
:+1:

**Comment by ArtSabintsev** [comment]
Pushing 0.2.1 in a sec. Really minor change.

**Comment by ArtSabintsev** [comment]
And it's done.
