### ISSUE TITLE
Manual Installation Error

### ISSUE THREAD

**Issue by apikurious** [ArtSabintsev/Siren#50]
There is no proper folder to be manually added into my own project. Need to open the Sample App and pull the Siren.framework into my own project.

**Comment by ArtSabintsev** [comment]
Drag the sub-folder named Siren into your project. It has the framework and bundle file in there.

**Comment by ArtSabintsev** [comment]
Here's a link: https://github.com/ArtSabintsev/Siren/tree/master/Siren

**Comment by apikurious** [comment]
It only has a .bundle and .swift file and the framework doesn't appear in the list when I try to link frameworks and libraries or embedded binaries.

**Comment by ArtSabintsev** [comment]
It should work. Why not use CocoaPods, Carthage, or SwiftPM? Siren supports all three.
