### ISSUE TITLE
sirenDidFailVersionCheck

### ISSUE THREAD

**Issue by black-lotus** [ArtSabintsev/Siren#51]
I had an error but i don't know what exaclty it is
Can anyone help me to find out
Here is the log from console tab

```
sirenDidFailVersionCheck Error Domain=Siren Error Domain Code=1001 "No new update available." UserInfo={NSLocalizedDescription=No new update available.}
[Siren] No new update available.
```

Many Thanks

**Comment by ArtSabintsev** [comment]
@black-lotus 

It's not really an error. In a recent update, I added more logs and the ability to handle errors via a delegate. This means that there's no new update, so no version check was performed.

More info in https://github.com/ArtSabintsev/Siren/pull/48 and https://github.com/ArtSabintsev/Siren/pull/49

**Comment by ajayiivo** [comment]
Hello,
my application is live on US app store .
Also, set the country code = en_US
but i am getting error.
below is my code
 let siren = Siren.shared
    siren.delegate = self
    siren.debugEnabled = true
    siren.countryCode = "en_US”
   siren.alertType = .option
    
    siren.majorUpdateAlertType = .option
    siren.minorUpdateAlertType = .option
    siren.patchUpdateAlertType = .option
    siren.revisionUpdateAlertType = .option
    siren.checkVersion(checkType: .immediately)
Getting error :
sirenDidFailVersionCheck(error:) Error Domain=Siren Error Domain Code=1005 "Error retrieving iOS version number as there was no data returned." UserInfo={NSLocalizedDescription=Error retrieving iOS version number as there was no data returned.}
Please help me in this .
thank you

**Comment by ArtSabintsev** [comment]
Siren defaults to the US app store, so please remove the `countryCode` reference. 

Please open a new issue instead of hijacking an existing closed issue.

Thank you.

Locking this issue.
