### ISSUE TITLE
Warnings when launching app store from UIAlertAction completion handler.

### ISSUE THREAD

**Issue by bakeddean** [ArtSabintsev/Siren#58]
Running sample app in iOS 9.3 produces the following warnings in the console:

2016-05-04 14:53:59.978 Sample App[13254:43700378] _BSMachError: (os/kern) invalid capability (20)
2016-05-04 14:53:59.979 Sample App[13254:43700738] _BSMachError: (os/kern) invalid name (15)

Stackoverflow suggests using dispatch_async to fix this:
 
```
let action = UIAlertAction(title: title, style: .Default) { (alert: UIAlertAction) in
            self.hideWindow()
            dispatch_async(dispatch_get_main_queue(), {
                self.launchAppStore()
            })
            self.delegate?.sirenUserDidLaunchAppStore()
            return
        }
```

**Comment by ArtSabintsev** [comment]
Thanks for the message. 

What version of Xcode are you using?

Also, the launch AppStore must be on the main thread because it leads to a UIApplication method that launches the AppStore app.

**Comment by bakeddean** [comment]
Ok. I'm using Xcode 7.3. It may be just one of those strange messages that disappears in the next version of Xcode.

**Comment by ArtSabintsev** [comment]
I'm still on 7.3. 

This seems to be the fix: http://stackoverflow.com/a/33465083/814861

Will do it soon.

**Comment by ArtSabintsev** [comment]
ok fixed.

**Comment by ArtSabintsev** [comment]
Thanks!
