### ISSUE TITLE
Attempting to load a UIAlertController when VC is deallocating

### ISSUE THREAD

**Issue by yoavschwartz** [ArtSabintsev/Siren#59]
I am trying to perform a check immediately when the app open, so I call check immediately from `didFinishLaunchingWithOptions`. I keep getting the following error: 
`Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior`

I also tried calling it from the View Controller in `didAppear` and get the same error.

**Comment by ArtSabintsev** [comment]
Please check the Sample App in this project to get an idea on how to present Siren. If you have other modals being presented on launch, hold off on checking the version until your entire launch process has completed.

**Comment by ArtSabintsev** [comment]
Closed due to no response. Assuming issue is fixed.
