### ISSUE TITLE
Alrert title is name of target, not that of bundle display name

### ISSUE THREAD

**Issue by royherma** [ArtSabintsev/Siren#60]
Anyway to override the title in the default alert controller?

**Comment by pavankataria** [comment]
Set the app name to whatever you wish the name to have. Although I do wonder why the author of this package doesn't grab the name of the app from the app store since it's common to change the project name after first creating it and changing the project name can have ramifications.

**Comment by getaaron** [comment]
You can also present your own alert (or any UI you want) in `sirenDidDetectNewVersionWithoutAlert(_:)`.

**Comment by ArtSabintsev** [comment]
@pavankataria The reason I don't do it is because it's an edge-case feature that's never been asked for in the 4-years I've been supporting Harpy and Siren.

**Comment by ArtSabintsev** [comment]
I lied - we do do it :)

https://github.com/ArtSabintsev/Siren/blob/master/Siren/Siren.swift#L228 (for the appName)

We don't change the title due to localization issues.

**Comment by royherma** [comment]
Yep, `appName` is what i was looking for! 

Thanks guys

**Comment by ArtSabintsev** [comment]
Our pleasure! Sorry for the long response time - I was on vacation.
