### ISSUE TITLE
Error when trying to retrieve App Store data

### ISSUE THREAD

**Issue by troligtvis** [ArtSabintsev/Siren#61]
I'm getting this error when I run the app. 
[Siren] JSON results: ["resultCount": 0, "results": <__NSArray0 0x15de15b60>()]
[Siren] Error retrieving App Store data as an error was returned.

I don't know where to specify my App Id now when that property is private. My app is active on the app store so this don't happen because of it doesn't exist there. 

What am I missing?

**Comment by ArtSabintsev** [comment]
On vacation, will respond soon.

Siren uses the Bundle ID now. Is your Bundle ID the same as the one in the store for your app target that is throwing this error?

**Comment by troligtvis** [comment]
Yes it is the very same, I even tried the 0.7.0 version so I can input the
app Id. But it still gave me the error, so maybe there is something else
that is the problem?
fre 20 maj 2016 kl. 07:28 skrev Arthur Ariel Sabintsev <
notifications@github.com>:

**Comment by ArtSabintsev** [comment]
What's your Bundle ID and what's the current version of the app that's in the store? Also, an AppStore link would be helpful.

Thanks!

**Comment by ArtSabintsev** [comment]
I see your PR. Closing this issue.

**Comment by troligtvis** [comment]
Sorry for late answer. Here is the appstore link -> https://itunes.apple.com/se/app/friendo-events/id1069606352?mt=8

Is it 'safe' to share the bundle id public? I mean security reasons and such.

**Comment by ArtSabintsev** [comment]
Yes, it's perfectly safe.

**Comment by ArtSabintsev** [comment]
I deleted it for you after I grabbed a copy

**Comment by ArtSabintsev** [comment]
and that's not the bundle ID, that's the URL. I need the `com.myDomain.myApp` - that's the bundle ID.

**Comment by troligtvis** [comment]
Ah ok, here is the bundle ID, com.friendoapp.Friendo

I don't know if I made some other changes that could cause the problem to occur.

**Comment by croccio** [comment]
is your app available in one or some country and not all around the world? 
If YES set the countryCode.

For example my app is available only in italy, so i i use this 

        let siren = Siren.sharedInstance
        
        siren.debugEnabled = true
        
        siren.alertType = SirenAlertType.Force
        
        siren.revisionUpdateAlertType = SirenAlertType.Skip
        siren.patchUpdateAlertType = SirenAlertType.Option
        siren.minorUpdateAlertType = SirenAlertType.Force
        siren.majorUpdateAlertType = SirenAlertType.Force
        
        siren.checkVersion(.Immediately)

it doesn't not work.
lib call this service to verify app version https://itunes.apple.com/lookup?bundleId=com.paybay.qui

as you can see in response results's length is zero.

if you add "countryCode' 

        let siren = Siren.sharedInstance
        
        siren.countryCode = "it" //BECAUSE MY APP IS AVAILABLE ONLY IN ITALY
        
        siren.debugEnabled = true
        
        siren.alertType = SirenAlertType.Force
        
        siren.revisionUpdateAlertType = SirenAlertType.Skip
        siren.patchUpdateAlertType = SirenAlertType.Option
        siren.minorUpdateAlertType = SirenAlertType.Force
        siren.majorUpdateAlertType = SirenAlertType.Force
        
        siren.checkVersion(.Immediately)

lib call this service https://itunes.apple.com/lookup?country=it-IT&bundleId=com.paybay.qui and as you can see your app is returned.

let me know ;)

**Comment by troligtvis** [comment]
Thank you, that solved it! 

I used only the forceLanguageLocalization 
`siren.forceLanguageLocalization = SirenLanguageType.Swedish`
with countryCode it works great! 
`siren.countryCode = "se"`

**Comment by ArtSabintsev** [comment]
Awesome! Glad you got it working! 

Is 'sv' different from 'se'? The app has Swedish set as 'sv'.

**Comment by croccio** [comment]
sv = el salvador (te quiero mi amor XD XD)
se = swedish

**Comment by ArtSabintsev** [comment]
whoops - I'll fix the localization stuff in a new PR in the next hour.

**Comment by ArtSabintsev** [comment]
According to this document, thttp://www.loc.gov/standards/iso639-2/php/English_list.php, which Apple links to in their own documents, `sv` stands for Swedish under the ISO 639-1 standard. That's why I used `sv`.

Can you show me a doc that says it's `se`?

**Comment by troligtvis** [comment]
I think both works but in different situations. 

In the app store it is "se"

**Comment by ArtSabintsev** [comment]
Can you send me an app store link with that example?

**Comment by troligtvis** [comment]
I send one before but it became redacted. But here it is -> https://itunes.apple.com/se/app/friendo-events/id1069606352

**Comment by ArtSabintsev** [comment]
ok cool - I'll make the change in Siren and Harpy.
