### ISSUE TITLE
Altering AppID and Test with  0.8

### ISSUE THREAD

**Issue by mosn** [ArtSabintsev/Siren#65]
How can I set the appID for testing ? My app is not in app store yet and I need to set the `AppID` but as instruction says, the `AppID` is now fetched from the API. 

Any solution for how to test with other AppID's

**Comment by ArtSabintsev** [comment]
You no longer have to set the App ID. Siren now uses the Bundle Identifier. I'll take a look at the README again, because I thought I removed that information: https://github.com/ArtSabintsev/Siren#important-notice-as-of-v080

**Comment by mosn** [comment]
Thanks for the prompt response. 
How can I test the Siren if my app is not in the app store yet ?

**Comment by ArtSabintsev** [comment]
Use a different bundle id. Check the Sample App Project file for the iTunes Connect Mobile App Bundle ID, which is used for testing purposes. Their app is in the store and at v3.2, while the sample project's version is 1.0.0.

You can install Siren in your project, and temporarily change the bundle id for testing purposes.
