### ISSUE TITLE
CFNetwork SSLHandshake failed (-9801) errors

### ISSUE THREAD

**Issue by jsoendermann** [ArtSabintsev/Siren#66]
Hi,

when I try to use Siren in my app, I get SSL errors on startup:

```
CFNetwork SSLHandshake failed (-9801)
CFNetwork SSLHandshake failed (-9801)
CFNetwork SSLHandshake failed (-9801)
CFNetwork SSLHandshake failed (-9801)
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9801)
```

Do I have to add a URL to my App Transport Security exceptions for Siren to work?

**Comment by ArtSabintsev** [comment]
Hmm, I've never had to do that. What's your ATS settings look like?

**Comment by ArtSabintsev** [comment]
and yes, that will probably fix the problem.

**Comment by jsoendermann** [comment]
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSAllowsArbitraryLoads</key>
				<true/>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

Which Domain would I have to add to make it work?

**Comment by ArtSabintsev** [comment]
Hmm, you should be fine with those settings. I'm surprised it didn't work. I'll have to get back to you on that.

**Comment by jsoendermann** [comment]
Thanks!

**Comment by getaaron** [comment]
I can't reproduce this. Are you using something like Charles or Wireshark?

**Comment by ArtSabintsev** [comment]
Closing the issue as it's not reproducible

**Comment by ArtSabintsev** [comment]
Re-opening for feedback, but there's not much we can do on our end.

**Comment by ArtSabintsev** [comment]
As there's been no feedback in about a week, I'm closing this issue.
