### ISSUE TITLE
forceLanguageLocalization doesn't change the language.

### ISSUE THREAD

**Issue by nmizoguchi** [ArtSabintsev/Siren#67]
The alert shows english text even after setting to other SirenLanguageType (I'm using PortugueseBrazil).

**Comment by ArtSabintsev** [comment]
I'll look into it.

**Comment by ArtSabintsev** [comment]
Confirmed that this is a problem. I'm working on writing some tests to pinpoint if other languages are affected as well.

Thanks for bringing it to my attention.

**Comment by ArtSabintsev** [comment]
I'll tackle this issue once I've finished writing the tests in #68.

**Comment by nmizoguchi** [comment]
I'm the one who should be thanking you for saving me a lot of time! :) I'm Glad I could help in some way.

**Comment by ArtSabintsev** [comment]
I fixed the issue in here: https://github.com/ArtSabintsev/Siren/pull/68/commits/ba1fa107fd77e53fec0a6442286d794ecee7b751

It's currently in the Tests PR I'm working on. Will pull it in later today.

Arthur

**Comment by ArtSabintsev** [comment]
Closing this issue, as I've fixed the problem in #68, which will be merged soon.
