### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by Tulleb** [ArtSabintsev/Siren#74]
Hello and thanks for this framework,

Is there a Swift 3 branch on its way?

I can't use it with Xcode 8 and Swift 3 beta and Cocoapods... Or couldn't find how to.

Thanks!

**Comment by ArtSabintsev** [comment]
Hey - I'll get it soon enough. It's on my to-do list for the next week (just a rough port).

It'll be on a branch. I'll post more info when it's done.

**Comment by Tulleb** [comment]
Ok great! Thanks a lot. Would you like some help with a PR?

**Comment by ArtSabintsev** [comment]
Nah, I'll just do the auto-conversion later today, and see what breaks. Shouldn't be anything. O'll keep monitoring it with every release of Xcode 8 beta. Once it gets stab;e enough I'l update the source. 

Lookout for it later this evening (US-EST)

**Comment by Tulleb** [comment]
Ok, thanks once again @ArtSabintsev!
If you could make all your work in a "swift3" branch, it would already allows us to test it with CocoaPods and help you out meanwhile Xcode 8 get released.

**Comment by ArtSabintsev** [comment]
Sure, was planning on doing that.

Do I need to add a subspec, or will you be pointing to the branch directly via `:branch => '...'`

**Comment by Tulleb** [comment]
I'll point directly at it with `:branch`.

**Comment by ArtSabintsev** [comment]
ok, cool. Will do it within the next hour.

**Comment by ArtSabintsev** [comment]
Check PR 75. The branch is `swift3`. I'll update the main README with cocoapods/carthage rules for pulling that branch in just a moment.

Closing this issue.

**Comment by Tulleb** [comment]
#75
