### ISSUE TITLE
Swift 3 and SwiftPM support

### ISSUE THREAD

**Issue by TofPlay** [ArtSabintsev/Siren#77]
Hi,
If your component is [SwiftPM](https://swift.org/package-manager) compatible it's will be great you add 
add [![SwiftPM Compatible](https://img.shields.io/badge/SwiftPM-Compatible-brightgreen.svg)](https://swift.org/package-manager/)  on top of your `README.md` and add section for the installation with SwiftPM.

**Comment by ArtSabintsev** [comment]
Sure, I'll do that in next hour.

**Comment by ArtSabintsev** [comment]
Done!

Thanks!
