### ISSUE TITLE
String issue when installing via pod

### ISSUE THREAD

**Issue by pradeep-chauhan** [ArtSabintsev/Siren#85]
Pods/Siren/Siren/Siren.swift:534:15: Initializer for conditional binding must have Optional type, not 'String'

**Comment by ArtSabintsev** [comment]
Which branch?

- master
- swift2.3
- swift3

**Comment by pradeep-chauhan** [comment]
swift 2.3

--  
Pradeep Chauhan
(Mob.) +91-9829158345
website: https://branded.me/pradeep-chauhan
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ArtSabintsev** [comment]
Alright, I'll take a look tonight when I'm back at a computer

**Comment by ArtSabintsev** [comment]
I am not seeing this issue in Siren's `swift2.3` branch in Xcode 8b6. The sample project compiles and runs without any issues.

- Are you using Xcode 8b6?
- What version of CocoaPods are you using? 
 - I'd recommend pointing to cocoapods/master (and not using 1.1.0.beta.1 if you're doing development in Xcode 8. 
- What does the line of code importing siren in your Podfile look like?

**Comment by pradeep-chauhan** [comment]
It’s resolved by last night.
is there need to add my app url for app store or it will automatically do all this things.


--  
Pradeep Chauhan
(Mob.) +91-9829158345
website: https://branded.me/pradeep-chauhan
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ArtSabintsev** [comment]
It will automatically grab the bundle ID for you and do everything in the background.

Thanks for following up.

Closing the issue.

**Comment by vaibhav-varshaaweblabs** [comment]
I'm getting the same issue with Swift 2.3 branch and XCode Version 7.3.1 (7D1014)

**Comment by ArtSabintsev** [comment]
Swift 2.3 is compatible with Xcode 8, not 7.3.1.

**Comment by swangy** [comment]
is there a version that compiles on xcode 7.3.1?  master branch DEFINITELY doesnt work on xcode 7

**Comment by ArtSabintsev** [comment]
Yes, version 0.9.5 compiles in Swift 2.2 in Xcode 7.3.1.

**Comment by J-Arji** [comment]
I'm getting the same issue with Swift 2.3 branch and XCode Version 7.3 (7D175)

Please help me as soon as possible

**Comment by ilhammalik** [comment]
how i can solved this i'm using swift 2.3
Initializer for conditional binding must have Optional type, not 'String'
        guard let url = components.URL, // This problem 
            urlString = url.absoluteString
            where !urlString.isEmpty else { // https://openradar.appspot.com/25382891
                throw SirenErrorType.MalformedURL
        }

**Comment by pradeep-chauhan** [comment]
You check with if..else or use guard.   
Please avoid force wrapping.

--  
Pradeep Chauhan
(Mob.) +91-9829158345
website: https://branded.me/pradeep-chauhan
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
