### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by gbertb** [ArtSabintsev/Siren#86]
![image](https://cloud.githubusercontent.com/assets/650530/18222296/270bd498-7148-11e6-8d33-d97b83e86a13.png)

**Comment by ArtSabintsev** [comment]
Which branch?
Which version of Xcode?

Is this from the sample project or from a cocoapods/Carthage/SwiftPM/manual install?

**Comment by gbertb** [comment]
2.3 branch
xcode Version 7.3.1

**Comment by ArtSabintsev** [comment]
2.3 branch only works in Xcode 8, to my knowledge.

**Comment by ArtSabintsev** [comment]
Use the master branch for Xcode 7

**Comment by ArtSabintsev** [comment]
Closing the issue. Feel free to reopen it if you still have problems
