### ISSUE TITLE
Support for iOS8

### ISSUE THREAD

**Issue by tbaranes** [ArtSabintsev/Siren#88]
Just discover that Siren 1.0.0 doesn't support iOS8.0 anymore, is there a technical reason for that?

I know Apple suggests to support only the last two major version, but it would be great to have at least one release supporting Swift 3 and iOS8 for all the developers that can't drop that version yet 👼

**Comment by ArtSabintsev** [comment]
Oversight. Will fix in the next hour!

**Comment by ArtSabintsev** [comment]
Done.

https://github.com/ArtSabintsev/Siren/releases/tag/1.0.1
