### ISSUE TITLE
Siren.Type does not have a member named 'SharedInstance' 

### ISSUE THREAD

**Issue by samuelbeek** [ArtSabintsev/Siren#9]
Hi, 

I got this error when copying the code from the readme.md file 
![schermafbeelding 2015-02-25 om 10 46 55](https://cloud.githubusercontent.com/assets/248098/6368308/b88ececa-bcdb-11e4-8a6b-032fa20ef869.png)
When I changed it to 

        let siren = Siren.sharedInstance

it worked perfectly.

**Comment by ArtSabintsev** [comment]
That's interesting. Which version of Xcode are you using?

**Comment by samuelbeek** [comment]
6.1.1

**Comment by ArtSabintsev** [comment]
Oddly enough ,the sample app has it right, but the README has it wrong. Fixing it now. Thanks for your help!
