### ISSUE TITLE
Not really an issue, a question about Swift PM

### ISSUE THREAD

**Issue by malcommac** [ArtSabintsev/Siren#92]
Hi,
I'm looking at your lib and I've a question - as an author of another lib - how have you specified to copy .bundle file in generated lib by SwiftPM?

**Comment by ArtSabintsev** [comment]
Haven't really tested Swift PM in a long time and no one has complained of it not working, so I assumed it just worked.

**Comment by malcommac** [comment]
Because I've tried to run test (swift test) and it does not work due to missing .swift bundle.
Thank you anyway :)

**Comment by ArtSabintsev** [comment]
No problem - good luck!
