### ISSUE TITLE
Swift 2.3 not work

### ISSUE THREAD

**Issue by LuciusLu** [ArtSabintsev/Siren#94]
I set pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift2.3' in cocoapod file,
and it result me Using Siren (0.9.5) version, it not work in swift2.3 xcode8

**Comment by ArtSabintsev** [comment]
I cannot reproduce this issue.

Can you show me the eaxct errors that come back for `pod install` for:

```
pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift2.3'
```

**Comment by LuciusLu** [comment]
@ArtSabintsev 
OH~Sorry, it working now.
Maybe I just upgrade xcode7 to xcode8 then make this problem.
Please close it, I like your project, please continue to update.
