### ISSUE TITLE
Not updating app from app store

### ISSUE THREAD

**Issue by pradeep-chauhan** [ArtSabintsev/Siren#95]
I have implemented Siren and when updates is available it is showing popUp and onClick update it is going to app store but there is no option for update. its showing only open button.
my previous version is 1.0.2 and new version is 1.0.3

**Comment by CoolHandLuke88** [comment]
I've noticed that app store has bug where it doesn't update the version. It may be bug on the app store. I don't even use this framework for updating, but curious of using the library. Just heads up if anyone else can confirm.

**Comment by ArtSabintsev** [comment]
It's a bug on the App Store side. If the app just gets updated on the App Store side, siren automatically knows about it. Unfortunately, it takes about 20 to 30 minutes for the app to actually be made available on the App Store side even after the JSON says it's available. This is why it may act like a false positive sometimes.

**Comment by pradeep-chauhan** [comment]
My app was live around 4.57 AM and i was check my app at 9.30 the issue is same.

--  
Pradeep Chauhan
(Mob.) +91-9829158345
website: https://branded.me/pradeep-chauhan
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ArtSabintsev** [comment]
So is the issue that the App Store says OPEN instead of UPDATE? If so, that's an App Store bug.

**Comment by ArtSabintsev** [comment]
Closing this issue due to lack of communication. Feel free to comment if you have any updates.

**Comment by lensbox** [comment]
Hello,
I've tried using your library for the first time on iOS10 and I have the same problem.
The error code says : 
[Siren] Error retrieving iOS version number as there was no data returned.
[Siren] Error parsing App Store JSON data.

Do you know what is happening ? Thank you.

**Comment by getaaron** [comment]
@lensbox what's your app's ID?

**Comment by lensbox** [comment]
If it is the bundle id you need, it is com.chamberlan.myChamberlan.

**Comment by getaaron** [comment]
http://itunes.apple.com/lookup?bundleId=com.chamberlan.myChamberlan does not return any results. Is your app in the App Store?

**Comment by lensbox** [comment]
Version 1.0 is here, only available in the french store for now : https://itunes.apple.com/us/app/chamberlan/id1097726117?l=fr&ls=1&mt=8

**Comment by ArtSabintsev** [comment]
Did you set the conutryCode? https://github.com/ArtSabintsev/Siren/blob/master/Siren/Siren.swift#L236

**Comment by lensbox** [comment]
In fact, I did not. Now everything is working fine. Thanks a lot !
This library is really useful !

**Comment by ArtSabintsev** [comment]
Great - Happy to hear it!

**Comment by gbertb** [comment]
Here's a relevant thread from the apple forums:

https://forums.developer.apple.com/thread/52767

basically apple's response:
_The App Store is global in nature, and it may take time for an update to an app to be available in any given store front in any given region.
 
I would recommend versioning your server endpoint so that a a version of an app is tied to a version of your server release. For example, you may want to use URLs such as https://example.com/v1/endpoint rather than https://example.com/endpoint. Each version of your app can call the appropriate endpoint, and your server can also report that a new version is available.
 
This also makes it friendlier to your customers who may not be in a position to update at the moment they want to use your app._

**Comment by yudhishtadhayalan** [comment]
[Siren Error] No new update available.
 👆🏻 👆🏻 If it shows like this...


For example current version is 1.2 and App Store version also the same 1.2 
Then it shows [Siren Error] No new update available.

Decrease the app version and check again..

In your Xcode.. decrease the version in to 1.1 and check It will surely works..  :)
  
                              
Yours lovingly,
Legend iOS Developer 😆😆😆

**Comment by ArtSabintsev** [comment]
Thanks for your feedback.

Closing this issue as it was resolved over 2 years ago.
