### ISSUE TITLE
Change Carthage build to use Carthage.xcodeproj instead of Sample App.xcodeproj

### ISSUE THREAD

**Issue by mikemee** [ArtSabintsev/Siren#96]
When I include Siren via Carthage and do `carthage update`, it builds Siren with this message:

```
*** Building scheme "Siren" in Sample App.xcodeproj
```

Other libraries using Carthage have messages like:

```
*** Building scheme "SVProgressHUD-Framework" in SVProgressHUD.xcodeproj
*** Building scheme "RMStoreFramework" in RMStore.xcodeproj
```

I'm guessing this a simple change somewhere from `Sample App` to `Siren`. (If I get a chance, I'll find it and do a PR.)

**Comment by ArtSabintsev** [comment]
Thanks, please do that. I don't use Carthage and support a long time ago. Haven't tested it since.

**Comment by ArtSabintsev** [comment]
Any update, @mikemee? I'm assuming all I have to do is rename the project.

**Comment by ArtSabintsev** [comment]
Closing this issue for now, as it seems to be a stylistic issue. Will re-open if/when I hear back.
